### ISSUE TITLE
Add Open Graph, Twitter Cards, etc

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#107]
Docs pages should have all the appropriate Open Graph, Twitter Cards, etc. `<meta>` tags so that other web tools can show nice previews & summaries.

It looks like Hugo has some built-in templates for this (https://gohugo.io/templates/internal/#the-internal-templates), which you can use in the base layout (https://github.com/ipfs/docs/blob/master/layouts/_default/baseof.html).

If those aren’t good enough, add a custom partial for the metadata in https://github.com/ipfs/docs/tree/master/layouts/partials and use that in the base layout.

(You can check the source of the built-in templates for guidance/inspiration at https://github.com/gohugoio/hugo/tree/master/tpl/tplimpl/embedded/templates)

**Comment by jessicaschilling** [comment]
This is a good point that we should take into consideration for the docs site re-vamp. @ericronne and @cwaring -- can you please incorporate this into your requirements for #195 and #197 as appropriate? Thank you!

**Comment by jessicaschilling** [comment]
Closing this issue since it's now captured in the features list at https://hackmd.io/qCel8CPkRtCZsAA-Oxeupw?both .
