### ISSUE TITLE
Concept Doc: Incorporate CID Inspector into CID concept doc

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#108]
We should incorporate the live [CID inspector application](http://cid-utils.ipfs.team) directly into the [CID concept doc](https://github.com/ipfs/docs/blob/master/content/guides/concepts/cid.md). You can find the source for the inspector at https://github.com/ipfs/cid-utils-website.

**Comment by jessicaschilling** [comment]
Link to inspector: https://cid.ipfs.io/#zb2rhiVd5G2DSpnbYtty8NhYHeDvNkPxjSqA7YbDPuhdihj9L

**Comment by jessicaschilling** [comment]
There's already a CID inspector link but it's extremely difficult to find. Called out with a subheading and added some text scaffolding to explain why the inspector is nifty.
