### ISSUE TITLE
explicit descriptions of go-ipfs and js-ipfs on ipfs.io/docs

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#11]
explicit descriptions of go-ipfs and js-ipfs on ipfs.io/docs and their status of interop etc

**Comment by Mr0grog** [comment]
Marking this as completed by:
- https://docs.ipfs.io/reference/go/overview/ ([source file](https://github.com/ipfs/docs/blob/2c96150e94a3be90aa2bed4ef3e51d1c51fa254d/content/reference/go/overview.md)) and
- https://docs.ipfs.io/reference/js/overview/ ([source file](https://github.com/ipfs/docs/blob/2c96150e94a3be90aa2bed4ef3e51d1c51fa254d/content/reference/js/overview.md))

There’s certainly plenty that could be improved on those pages or in the intro/getting started docs, but I think we can close this as a general issue.

Please comment if we should re-open.
