### ISSUE TITLE
Fix id hrefs: #apiv0p2plistenerls

### ISSUE THREAD

**Issue by d180cf** [ipfs/docs#116]
Right now the hrefs are broken: https://ipfs.io/docs/api/#apiv0p2plistenerls

Should be: https://ipfs.io/docs/api/#api-v0-p2p-listener-ls

**Comment by Mr0grog** [comment]
@d180cf I think you might be looking at the wrong site. The links seem to all be working for me here: https://docs.ipfs.io/reference/api/http/

Are you looking at https://ipfs.io/docs/api/ ? That site is deprecated and in need of redirects to the new one :\

**Comment by d180cf** [comment]
I see. Thanks for the pointer!
