### ISSUE TITLE
Discussion: Enabling Translations of docs.ipfs.io

### ISSUE THREAD

**Issue by lidel** [ipfs/docs#117]
Now that we have [IPFS Translation Project](https://github.com/ipfs/i18n) we should start _thinking_ about enabling i18n for docs.ipfs.io.

- Should we do it at all? Is it the right time?

If so, some initial assumptions:
- We support language only if  translation for it is 95% done (`minimum_perc = 95` in `.tx/config`)
- Documentation site should remain easy to maintain, as random text may change often. 
   -  We don't want to move english text to separate locale file, ideally it should remain in plaintext form, to make it easy for people to PR updates.
   - Potential solution: add thin i18n attributes and generate source locale during the build. Some prior art for that approach: [tableflip/i18n-browserify](https://github.com/tableflip/i18n-browserify#i18n-with-gettext-and-browserify), [ipld-explorer-components](https://github.com/ipfs-shipyard/ipld-explorer-components/pull/1/files#diff-6c024b45e843a6c1c07a1e31b494b5b1R14)

Would love to hear your thoughts. 

cc @ipfs/documentation

**Comment by lgierth** [comment]
> Documentation site should remain easy to maintain, as random text may change often

Yes this is a crucial point. We'll have a very very hard time keeping non-english versions of the docs up-to-date, if the tooling doesn't support this very well. The only thing worse than no documentation is outdated and wrong documentation.

**Comment by jessicaschilling** [comment]
Adding this to the "OKR: Features List" bucket since translation/i18n for our docs is a key aspect of spec'ing out our next-generation docs platform. @ericronne and @cwaring -- can you please take note of the discussion in this issue and make sure it gets included in both the user-facing features list and the tech stack work? Thank you!

**Comment by jessicaschilling** [comment]
Closing this issue now that we've got i18n capabilities as a core consideration of our next-generation docs platform.
