### ISSUE TITLE
Workshops & Learning Materials

### ISSUE THREAD

**Issue by daviddias** [ipfs/docs#123]
From @flyingzumwalt at https://github.com/ipfs/community/issues/168

> Assemble workshop material that can be used at nodeschool-style in-person workshops.
> 
> Some reference materials:
> 
>     * #167: Outline a Curriculum for Learning IPFS-related Topics
> 
>     * [ipfs/go-ipfs#171](https://github.com/ipfs/go-ipfs/issues/171): `ipfs tour`
> 
>     * [ipfs/go-ipfs#1764](https://github.com/ipfs/go-ipfs/issues/1764): Detailing the Tour functionality
> 
>     * [NodeSchool](http://nodeschool.io/)
> 
>     * [Better community building for IPFS](https://github.com/ipfs/community/issues/64)
> 
> 
> Whichever format we use to present the info, the thing I really care about is curriculum design. For each workshop we need to identify the
> 
>     * Key Concepts
> 
>     * Learning Objectives
> 
>     * Learning Activities
> 
>     * Conceptual Framework
> 
> 
> The more we can do to be clear about those things, the easier it will be to produce great learning materials that are easy to maintain over time.
> ## Optional Formats: Nodeschool workshopper/adventure and RailsBridge
> 
> We could create these as nodeschool workshoppers or adventures. Alternatively we could follow the format used by RailsBridge.
> 
> refs #161

**Comment by jessicaschilling** [comment]
Closing this issue, since much of its core intent has been superseded by ProtoSchool. 😄 We can definitely re-address in the future as need and opportunity dictate!
