### ISSUE TITLE
Hard to find the docs/specs for core api

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#13]
Currently the “docs” link on ipfs.io links to docs for http api. Very hard to find the docs/specs for core api 

The plan:
1. [ ] Make a landing page README in https://github.com/ipfs/interface-ipfs-core/tree/master/API that provides a clear path into the documentation for all the modules
2. [ ] Update the readme in https://github.com/ipfs/interface-ipfs-core/ to call out the fact that there are docs, include a link to /API/README.md
3. [x] Update ipfs.io/docs to include a link to the core API docs

**Comment by flyingzumwalt** [comment]
At the very least, it should link to the info in https://github.com/ipfs/interface-ipfs-core/tree/master/API

**Comment by flyingzumwalt** [comment]
The plan:
1. Make a landing page README in https://github.com/ipfs/interface-ipfs-core/tree/master/API that provides a clear path into the documentation for all the modules
2. Update the readme in https://github.com/ipfs/interface-ipfs-core/ to call out the fact that there are docs, include a link to /API/README.md
3. Update ipfs.io/docs to include a link to the core API docs

**Comment by Mr0grog** [comment]
I think this has all mostly been done, and https://docs.ipfs.io links to interface-ipfs-core under “Reference → Commands & API → JS & Go Libraries”

If there’s work specific to interface-ipfs-core, I think we should just open issues/PRs there (unless it’s tightly coupled with something that has to happen on the docs site here.)

Please comment if I’ve mis-judged this and we should re-open.
