### ISSUE TITLE
Move DOCS_STYLEGUIDE to this repo?

### ISSUE THREAD

**Issue by daviddias** [ipfs/docs#134]
Currently at https://github.com/ipfs/community/blob/master/DOCS_STYLEGUIDE.md

**Comment by meiqimichelle** [comment]
+1 to @Mr0grog's explanation and reasoning -- the content styleguide should apply anywhere we write, not just in this docs repo. Perhaps that file could use a re-name in that case -- I'll pop over and suggest that -- but in the meantime, I'm closing this issue. Please re-open if I've missed something.
