### ISSUE TITLE
CID inspector link in CIDv1 section is broken

### ISSUE THREAD

**Issue by raulk** [ipfs/docs#143]
https://docs.ipfs.io/guides/concepts/cid/#version-1 points to: http://cid-utils.ipfs.team/#zb2rhiVd5G2DSpnbYtty8NhYHeDvNkPxjSqA7YbDPuhdihj9L, which returns a 404.

I guess this means that the server behind http://cid-utils.ipfs.team is broken, because it would be a bad sign if this content disappeared 😛

**Comment by Mr0grog** [comment]
This was fixed in #145 :)
