### ISSUE TITLE
libp2p module organization

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#15]
libp2p module organization, naming conventions & readmes unification

**Comment by diasdavid** [comment]
Signing myself up for this one too.

**Comment by diasdavid** [comment]
Some work already done here: https://github.com/libp2p/js-libp2p#packages

**Comment by diasdavid** [comment]
I believe @lgierth is working on standardising names :)

**Comment by diasdavid** [comment]
Follow on https://github.com/libp2p/libp2p/issues/16
