### ISSUE TITLE
Link dnslink part to dnslink.io

### ISSUE THREAD

**Issue by jbenet** [ipfs/docs#156]
Made a standalone website for dnslink recently -- http://dnslink.io. We should link to it from the dnslink section of these docs -- https://docs.ipfs.io/guides/concepts/dnslink/

**Comment by jessicaschilling** [comment]
Hi @jbenet -- added a link in PR #230 with you as approver if you don't mind a quick look 😄 
Thanks!

**Comment by jessicaschilling** [comment]
PR #230 closes this issue.
