### ISSUE TITLE
Place for contributors to start

### ISSUE THREAD

**Issue by victorb** [ipfs/docs#16]
Right now, there is no place for introducing the different areas where people can figure out how to contribute. The people that should be the target for this is people who want to contribute to IPFS but they don't know the ecosystem yet, and are not sure where their contributions would be the most valuable.

Things that we could do:
* [ ] Have webpage that dynamically fetches issues with the tag "difficulty-easy" or other tags that indicates that this issue would be simple to fix
* [ ] Write which areas we're currently having the most problems with/most bugs in
* [ ] Show other areas where we always appreciate contributions
* [ ] Applications that can be written as demo material
* [ ] Provide areas where we need help with testing

Some existing guides, would be nice to have a combination of all these features on one page:
* https://www.docker.com/contribute
* https://bugzilla.mozilla.org/buglist.cgi?quicksearch=sw:%22[good%20first%20bug]%22&limit=0
* https://www.joshmatthews.net/bugsahoy/
* http://www.firsttimersonly.com/
* https://www.codetriage.com/
* https://github.com/neovim/neovim/blob/master/CONTRIBUTING.md#getting-started
* https://gohugo.io/community/contributing/
* https://github.com/pouchdb/pouchdb/blob/master/CONTRIBUTING.md
* https://github.com/pouchdb/pouchdb/blob/master/TESTING.md
* https://starters.servo.org/
* https://github.com/servo/servo/blob/master/docs/HACKING_QUICKSTART.md
* https://whatcanidoformozilla.org/
* https://wiki.mozilla.org/Contribute
* https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Introduction

**Comment by Mr0grog** [comment]
@VictorBjelkholm is this done now that we have https://docs.ipfs.io/community/contribute/how_to_help/ ?

If no, can we break this down into more specific issues to improve that page (or some new page)? e.g. ‘dynamically fetches issues with the tag "difficulty-easy" or other tags that indicates that this issue would be simple to fix’ sounds rad; let’s make an issue specifically for that.

**Comment by jessicaschilling** [comment]
Going to close this issue with the understanding that we've explicitly added some pathways for contributors in the readme at https://github.com/ipfs/docs , as well as in https://docs.ipfs.io/community/contribute/how_to_help/ -- but we do need to keep those up to date, and make sure that as we ramp up our overall docs effort, that we make an effort at earmarking items that are welcoming and simple for new contributors.
