### ISSUE TITLE
Libp2p examples

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/docs#17]
We should rework the current example and add other examples to libp2p.

**Comment by whyrusleeping** [comment]
Examples/Documents/Tutorials I think we should add for this:

- Create a host
  - This is the basis of basically every direct use of libp2p. This guide needs to be really good
- Spin up a dht node
  - Requires having a host, messing with the dht directly is fun
- Direct floodsub usage
  - Use floodsub directly through the go-floodsub package without ipfs, requires a host.
- Custom protocol handler
  - We have an example for this already, lets polish it
- Write a pinger
  - Just a host with the ping protocol attached. Simple, but might be a cool tutorial to have (could show implementing ping)
- Plug in a new transport
  - Show creating a swarm with custom protocols, then make a host from it
- Advanced host creation tutorial
  - show using a different repo, different swarm options, using the routed host, etc. Lots of options here
- Write an http proxy with libp2p
  - Cool demo, should be pretty simple

**Comment by hsanjuan** [comment]
@whyrusleeping great, I was going to ask you about this!

> Create a host 
> Custom protocol handler
I think the echo example covers these (multiple examples will cover this).

I can definitely do:
* write a pinger - although the echo example again does pretty much the same as the ping service
* write an http proxy

For the rest I will need to learn, so probably takes me a bit longer. We'll check again if I have time in a few days.

**Comment by whyrusleeping** [comment]
@hsanjuan Even though the echo example covers this, i wanted a guide explaining what the host is, what it does, and how a very simple one gets put together, so i wrote that up in libp2p/go-libp2p#187 

Feel free to write any of the other examples, writing a simplistic [ping protocol](https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/ping/ping.go) from scratch will be a good 'what can i do with this host thing?' guide. The moving beyond that, writing an http proxy over libp2p will be a really cool 'what *useful* thing can i do with this?'.

**Comment by whyrusleeping** [comment]
@hsanjuan with the ping protocol one, it might be cool to show writing it from scratch, connecting to an existing ipfs node, and pinging it.
