### ISSUE TITLE
Broken IPFS Documentation Link at the Top of Google Search

### ISSUE THREAD

**Issue by graylan0** [ipfs/docs#171]
Google has a link to "Install IPFS" and it is broken. 
![Screenshot_2019-05-22_02-53-33](https://user-images.githubusercontent.com/34530588/58153581-66241200-7c3d-11e9-90b8-ac059092f48c.png)
https://docs.ipfs.io/introduction/install/ is the address

**Comment by daviddias** [comment]
@mburns, @olizilla can we have a redirect to avoid having all these users see a _no link named of death_ when trying to install IPFS?

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/1211152/58153738-1dd21780-7c70-11e9-9f9d-facb1ecff927.png">

**Comment by jessicaschilling** [comment]
I think the Google spiders have cleaned this one up on our behalf ... I've run a variety of G searches as me, other users, incognito, etc for "install IPFS" and it's consistently pointed me at https://docs.ipfs.io/guides/guides/install/ . Closing this issue for now -- though @graylan0, if you see it in the wild again, please inform! Thanks.
