### ISSUE TITLE
Fonts from google provide get started markdown

### ISSUE THREAD

**Issue by genofire** [ipfs/docs#174]
/ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme
->

/ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/quick-start

->

/ipfs/QmX7M9CiYXjVeFnkfVGf3y5ixTZ2ACeSGyL1vBJY1HvQPp/mdown

this strapdown loads the ubuntu fonts from google :(

**Comment by jessicaschilling** [comment]
Hi @genofire -- We are actually in the midst of spiking on upgrades to our existing docs platform (or perhaps a new one) that would deprecate our existing visual presentation (see #179 and #180 for details). With that in mind, I'll close this issue, but please, let's chat if you think we need to change things in the meantime as an urgent matter. Thanks!
