### ISSUE TITLE
OKR Epic: Front-page quiz

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#184]
**Add content and metrics mechanism for one-question “you’d like to” quiz on ipfs.io with guidance on next steps.**

See [Q3 2019 IPFS OKRs spreadsheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909).

Or, see [all open issues associated with this epic](https://github.com/ipfs/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22OKR%3A+Front-Page+Quiz%22).

**Comment by ericronne** [comment]
:boom:
