### ISSUE TITLE
OKR Epic: ProtoSchool

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#185]
**ProtoSchool-specific enhancements related to improved analytics and user feedback collection.**

See [Q3 2019 IPFS OKRs spreadsheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909).

**Comment by jessicaschilling** [comment]
@terichadbourne - Can we figure out the best way to integrate your existing means of tracking these individual ProtoSchool tasks inside the docs Zenhub board? Thanks!

**Comment by terichadbourne** [comment]
I'll work on trying to get things to talk to each other next week. In the meantime, you can see [issues related to ProtoSchool's Q3 OKRs](https://github.com/ProtoSchool/protoschool.github.io/issues?q=is%3Aopen+is%3Aissue+label%3Aq3-okr) in our website repo.

Our [full proposed Q3 OKRs](https://github.com/ProtoSchool/roadmap/pull/12/files?short_path=7fb0092#diff-7fb00928a494b70a67039559577ba81a) (which also include things on the community front unrelated to documentation) live in our roadmap repo.

**Comment by terichadbourne** [comment]
@jessicaschilling Mind if I close this one in favor of the epic that lives in the ProtoSchool repo? That one will allow us to assign ProtoSchool issues to it while filtered by repo.

**Comment by jessicaschilling** [comment]
Dooooo eeeet!
