### ISSUE TITLE
Add IPFS Camp core course content to top-level docs

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#187]
When videos from IPFS Camp 2019 are ready, add videos (minus Q&A session?) to top-level docs:
- Core Course D (Oli)
- Core Course A (MFS - Alan)

Videos are appearing here as they're published: https://github.com/ipfs/camp/

**Comment by ericronne** [comment]
Materials …

Core course D - The life cycle of data in dweb:
- [Outline](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_D)
- [Video](https://www.youtube.com/watch?v=fLUq0RkiTBA&list=PLuhRWgmPaHtSsHMhjeWpfOzr8tonPaePu&index=3&t=0s)

Core course A - Understanding how IPFS deals with files:
- [Outline](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A)
- [Video](https://www.youtube.com/watch?v=Z5zNPwMDYGg)

Where specifically are we adding this @jessicaschilling?

**Comment by jessicaschilling** [comment]
@ericronne We've accommodated space for this in our v2 nav structure, but for triage in the existing site, what about as external links from the Concepts in the nav?
![image](https://user-images.githubusercontent.com/1507828/65062212-ccdde180-d938-11e9-84e8-2bc1884d51e2.png)

**Comment by jessicaschilling** [comment]
Added links to nav of legacy site and incorporated the four courses to the beta:
- Courses A and D are broad enough to touch multiple "essentials" topics, so added tip callouts to them in their respective topic pages, plus prompts in the top-level essentials page
- Courses B and C added to nav in the "How-tos" section
