### ISSUE TITLE
Audit: Determine criteria for content audit

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#189]
Decide on ranking/evaluation criteria for content audit: 
- Discuss what we did for Cluster audit
- Determine what went well and what didn't go as well
- Determine whether we need any different criteria for ipfs.io audit (either because of lessons learned from Cluster audit, or because we have different needs for ipfs.io)
- Set up the working document for this effort (either another spreadsheet, or something else if something else would work better)

**Comment by pkafei** [comment]
The purpose of the content audit is to create an inventory of all of the content that we already have and to avoid wasting time creating duplicate content. 
https://docs.google.com/spreadsheets/d/18U8HhckD3ja5tdvwP50Bbw-kZj6SFjD10KI_1c5byrw/edit#gid=0

During the audit broken links, misspellings and other small fixes will be recorded and then fixed. @jessicaschilling

**Comment by jessicaschilling** [comment]
@pkafei -- awesome, thanks! I'm going to close this issue. Ready to get started on the audit itself (#190)?
