### ISSUE TITLE
Features List: Finalize wishlist for docs site features/UX/UI

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#195]
Everyone fills in the collaborative document set up in issue #193 with features they like/love/want in our future-state IPFS docs platform! (We need to timebox this, or it will go on until the end of days.)

We also need to be sure to incorporate thoughts on platforms listed in issue #31.

**WORKING DOCUMENTS HERE:
Visual survey in Mural: https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564058594791/301124cc83bda18ae561953cf817fb3cd96444ed
Features list in HackMD: https://hackmd.io/qCel8CPkRtCZsAA-Oxeupw?both**

**Comment by jessicaschilling** [comment]
P.S. ... I was kindly informed by @meiqimichelle that @eshon has a lot of recent knowledge and opinions on docs platforms features. @ericronne, do you mind checking in with her when you get the chance as to whether she might like to take part in this effort (or even just do a debrief with high-level insight)? Thank you!

**Comment by ericronne** [comment]
The new [filecoin docs site](https://filecoin-project.github.io/metadocs/) is built in view, but word on the street is that they may experiment with Docusaurus soon. If so, will be great to glean learnings from their experience.
🍿 

thanks @eshon!

**Comment by ericronne** [comment]
Here's a visual survey in [mural form](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564058594791/301124cc83bda18ae561953cf817fb3cd96444ed), for inspiration

**Comment by jessicaschilling** [comment]
Calling this one done, since @ericronne and I will be collating/summarizing/ranking this wish list as #194 in-person next week.
