### ISSUE TITLE
Tech Stack: Gather possible options

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#197]
Research landscape of possible options for next-generation docs platform and collate options in a central location (spreadsheet, GitHub issue, etc), with details on relevant parameters/pros/cons.

**Comment by ericronne** [comment]
@cwaring do you think [the list you've been curating](https://docs.google.com/spreadsheets/d/1KuLxE3Sq0Ju95f3FyLUQQA1vr3N-Se-dZcLyiCOqGz8/edit#gid=0) is now fleshed out enough to make a call? If so, i can set up a call for us to make the call asap.

**Comment by cwaring** [comment]
There are two clear front runners for me but for different reasons: https://docusaurus.io/en & https://gatsbyjs.org. Although I've still got some concerns about versioning, internationalisation and theming so I will propose a spike build after discussing the options in more detail during our next call.

**Comment by jessicaschilling** [comment]
Hi @cwaring -- I'm going to close this issue, since AFAIK you've moved from the data-collecting stage to the analysis and spike-building stage on this effort. Those are in issue #198. :) Thanks!
