### ISSUE TITLE
Sprint prep meeting Friday 3/10/2017

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#20]
There will be sprint prep meeting held to discuss the upcoming DOCS sprint. Let's shoot for:

Friday 10-Mar 17:00 UTC.

Notes: https://hackmd.io/GzDGCZgDgZnBaApgM1AE3gFhgBlPAQwE5ENwBWKcggI2GQHYGiYg

This meeting should last between 30 minutes to an hour.

**Comment by hsanjuan** [comment]
I can't make it tomorrow (at least for most part of the meeting).

I will say that it would make me happy to work on [go] libp2p documentation.

**Comment by flyingzumwalt** [comment]
FYI someone just recommended this to me: http://www.writethedocs.org/guide/

**Comment by flyingzumwalt** [comment]
... and yes I will be on this call.

**Comment by dignifiedquire** [comment]
I am afraid I won't make the call. Please record it

**Comment by lgierth** [comment]
Record part 1: https://ipfs.io/ipfs/QmQvkkRTaedvthu7ZpFKZk3q7Mj8yTWnJYKxyLKAceQY1R

**Comment by lgierth** [comment]
Waiting for recording part 2 and will close then

**Comment by flyingzumwalt** [comment]
Part 2: https://ipfs.io/ipfs/QmSQrcwi93ampynAQsjy4DC6biqAoBZdAGWugvyi472a3Y

Pinned with pinbot

**Comment by lgierth** [comment]
Thanks! See you on Monday for the sprint sync, and then Wednesdays and Fridays for standups.
