### ISSUE TITLE
Quiz: Create question/answer tree

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#204]
Create an outline for the question/answer tree that will manifest itself on the ipfs.io front-page quiz.

**NOTE: Version 1 (single-question quiz) HackMD iteration document is here: https://hackmd.io/TkDgbYTARWOcKUYX3-inhQ?both**

- Version one of the quiz needs to consist of just one question/answer based on "what do you want to do with IPFS?" or "how do you think IPFS could help you?". This single-question quiz will enable us both to gauge popularity of our more common use cases among the public, as well as to set up and test analytics on our docs site.
- However, this single-question quiz needs to be easily expanded at a later date into a larger quiz that can serve as a larger, more tutorial-oriented, "choose your own adventure" architecture for IPFS docs as a whole
- We don't need the entire tree for this part of the exercise, just assurance that our little single-question quiz won't mess up the rest of the tree

Note: This may be impacted by (or will influence!) the persona goals landscaping task in issue #201, since those task goals will likely be directly reflected in the first quiz question.

**Comment by jessicaschilling** [comment]
Pasting in content from @tapaswenipathak originally from (closed) PR #217, since this will be a useful starting point for the later, longer-form "choose your own adventure" quiz that will be a later release of the front-page quiz.

Outline For The Question/Answer Tree
====================================

Say we go with these questions -

* What do you want to do with IPFS?
* How the project spreads the mission of IPFS?
* What is the problem statement that you are solving?
* How do you solve the problem statement?
* What is the uniqueness you or your implementation bring on the table using IPFS?
* What do you think would be the impact factor of your work?
* How do you think IPFS could help you?
  * What teams do you think you would require support from?
	* Do you have any suggestions for us after reading the documentation?

Visual state for unanswered question
====================================

As this is a quiz IPFS should encourage the users on the implementation taking
the impact factor of IPFS more spreaded. The questions should be marked as
optional and mandatory. We shouldn't force the users on answering what they
doesn't want to.

Visual state for answered question and moving forward with next questions
==========================================================================

There should be a percetage bar of quiz completed. The quiz until submitted
should be in draft state so that the user can change their comments and expand
that items we asked. 

Indicator of what elements for having useful metrics 
=========================================================================

As IPFS would like knowing how the customers are using IPFS and how much is for
good. 

- How the user is spreading what IPFS stands for?
- How the user is enhancing IPFS? Do their ideas give IPFS more insights on they
can solve real work problems?
- How closer is the user problem statement with IPFS mission statement?
- What technical advancement IPFS require from customer implementations?
- How can IPFS take feedback from the users? How much of is that useful or can
	be simply thrown?
- How IPFS can help with documentation and support helping their customers?
- How much IPFS is able to associate itself with the users?

**Comment by jessicaschilling** [comment]
We're iterating on the wording and choices for the MVP (single-question) quiz version here:
https://hackmd.io/TkDgbYTARWOcKUYX3-inhQ?both

**Comment by ericronne** [comment]
The level of activity on the help section of the ipfs discussion board is an interesting metric, and may help us craft a question or two ([sorted here by most viewed](https://discuss.ipfs.io/c/help?order=views)). Very dev centric, of course, but most of our focus at this point should be on developers, no? At any rate, this board is a great finger on the pulse of the community.

At a dead heat for most popular are topics about [creating a private ipfs network](https://discuss.ipfs.io/t/how-to-create-a-private-network-of-ipfs/339/7) and [ipfs vs torrent](https://discuss.ipfs.io/t/ipfs-vs-webtorrent-what-the-value-of-using-ipfs-instead-of-torrent-files/64), followed by [confusion about pinning](https://discuss.ipfs.io/t/trying-to-better-understand-the-pinning-concept/754), [deleting content](https://discuss.ipfs.io/t/can-i-delete-my-content-from-the-network/301), and chatter about how to [avoid hosting illegal material](https://discuss.ipfs.io/t/avoid-hosting-of-illegal-material/48).

**Comment by jessicaschilling** [comment]
Nice confirmation that pinning is among folks' concerns. Let's definitely steer one question toward an answer involving pinning -- we've already got the "data permanence" question, does that feel like a broad enough entry point?

I'd say another one to think about would be "creating a private IPFS network." Why might folks be wanting to do that?

**Comment by jessicaschilling** [comment]
Calling this one done, since we're moving along nicely on issue #205 (mockup) and #201 (personae).
