### ISSUE TITLE
Q3 2019 OKRs: Research/test plan (umbrella issue)

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#207]
This issue is an umbrella for creating, executing and reporting on a research and test plan related to our primary Q3 OKR deliverables:
1. Passive metrics collection for the front-page quiz on ipfs.io (implementation of the quiz is under #205)
2. Usability testing for the front-page quiz on ipfs.io (implementation of the quiz is under #205, with testing execution under #247)
3. Initial round of moderated validity testing for our IPFS goal-based personae effort (persona testing and launch is under #203)
4. Card sort (#191) based on content inventory of current-state docs site

While in-stream reporting on each of those deliverables should happen within their respective GitHub issues, all results should be captured in the [test plan working document](https://docs.google.com/document/d/1c2TFeXLFW29a8HYwUq6K9-n8fDg2WhERRIi1CWHMC-8/edit) that is being managed in this issue.

This issue can be closed when all the testing in the [test plan](https://docs.google.com/document/d/1c2TFeXLFW29a8HYwUq6K9-n8fDg2WhERRIi1CWHMC-8/edit) is complete and learnings have been captured adequately: noted in the test plan, captured in GitHub issues for future fixing, or some combination of the two.

**Comment by momack2** [comment]
ex - num total clicks of the accordion per day, decrease in bounces, etc

**Comment by jessicaschilling** [comment]
Starting a working document for the test plan here:
https://docs.google.com/document/d/1c2TFeXLFW29a8HYwUq6K9-n8fDg2WhERRIi1CWHMC-8/edit
@cwaring and @ericronne -- let's collaborate on getting all our respective thoughts down on this paper.

**Comment by jessicaschilling** [comment]
All issue dependencies closed, and all results noted in the [summary document](https://docs.google.com/document/d/1c2TFeXLFW29a8HYwUq6K9-n8fDg2WhERRIi1CWHMC-8/) and/or in individual GitHub issues. Summary document is now also in main docs repo readme for future reference. Closing this issue -- thanks all!
