### ISSUE TITLE
Helpful gateway errors

### ISSUE THREAD

**Issue by lgierth** [ipfs/docs#21]
Errors and timeouts on the gateway are way too obscure. Even something as simple as a 404 sounds scary: "Path Resolve error: no link named "foo" under Qmdf6iGuPoQ7jmGM48nWoy46F5EwMiXYVif968cpwQXDrU".

We can make these a lot more friendly and useful for seeing how ipfs works. (And just nicer to debug.)

- [ ] Gateway should be extracted into [ipfs/go-ipfs-gateway](https://github.com/ipfs/go-ipfs-gateway)
- [ ] Gateway needs refactoring to cleanly distinguish errors
- [ ] Implement ipfs/go-ipfs-gateway#5

**Comment by hsanjuan** [comment]
I might try to extract gateway to it's own repo. Is this as easy as it sounds @lgierth ?

**Comment by lgierth** [comment]
Yeah it should be straightforward once the core-api has patch add-link, rm-link, and set-data, which I'll to first thing this sprint (in fact reviving this work right now).

Cool :+1:

**Comment by lgierth** [comment]
This continues to be tracked in ipfs/go-ipfs-gateway#5
