### ISSUE TITLE
Duplicate Install Page

### ISSUE THREAD

**Issue by pkafei** [ipfs/docs#215]
IPFS documentation currently has two install pages:
https://docs.ipfs.io/guides/
https://docs.ipfs.io/guides/guides/install/

https://docs.ipfs.io/guides/guides/install/ is the [more recent Install page](https://github.com/ipfs/docs/blob/master/content/guides/guides/install.md) and has more information on how to get IPFS on various platforms (Mac, Windows), and it also has instructions on how to install from source.

**Comment by tapaswenipathak** [comment]
@pkafei Can I take the ticket? or is the ticket internal?

**Comment by lanzafame** [comment]
@tapaswenipathak If you have access to the ticket, it is open and you are free to take it on 👍🙂

**Comment by ericronne** [comment]
Thanks for raising your hand @tapaswenipathak! This issue surfaces some weirdness with the structure of the docs site. For example, we have a `Guides` section which lives inside of a section named `Guides`. Confusing.

Ignoring the weirdness for now, i recommend that for https://docs.ipfs.io/guides/ we follow the pattern used on the [Commands & API ](https://docs.ipfs.io/reference/api/) landing page: H2 sub-page links followed by a brief description for pages that aren't links to another site.

So the Guides landing page content would be:
## [Install IPFS](https://docs.ipfs.io/guides/guides/install/)
(Paragraph description*)
## [Transferring a File](https://github.com/ipfs/go-ipfs/blob/master/docs/file-transfer.md)
## [Replicating Large Datasets](https://github.com/ipfs/archives/tree/master/tutorials/replicating-large-datasets)
## [Addressing in Browsers](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md)
## [Interactive Tutorials](https://proto.school/#/tutorials)

*This paragraph should be rewritten to briefly summarize what the user will find on the install page. Please feel free to have a go at that @tapaswenipathak! 😄 🙏

**Comment by tapaswenipathak** [comment]
Thanks @ericronne for writing your thoughts, PR attached.

**Comment by tapaswenipathak** [comment]
Thanks @ericronne for writing your thoughts.

**Comment by ericronne** [comment]
Suggested some mods in the [PR](https://github.com/ipfs/docs/pull/218#issuecomment-514759748) (along with @jessicaschilling :)

**Comment by tapaswenipathak** [comment]
I think should be closed now.

**Comment by jessicaschilling** [comment]
Made a few minor copy edits in PR #218 for consistency; removed text recommending command-line, since it's too detailed for the scope of this document; retained the double "guides" in file path, so as not to break menu structure (and we will be addressing this in overall docs platform revamp anyway soon). Thanks!
