### ISSUE TITLE
Implement improved API reference presentation in docs beta

### ISSUE THREAD

**Issue by pkafei** [ipfs/docs#225]
Implement the means of presenting API reference materials that we decide upon in #339.

**Comment by Stebalien** [comment]
Requirements:

* Open source.
* Docs hosted on IPFS (serverless). The rust docs implement client-side search that works pretty well.

---

In terms of _search_, Control+F is actually pretty reliable given that all our commands _are_ on the same page. Search primarily becomes an issue when content is split across multiple pages.

A couple of simple improvements we could make:

* Add a TOC.
* Collapse some parts of the documentation by default (e.g., the example requests).

**Comment by jessicaschilling** [comment]
I think just judicious addition of expand-collapse could go a long way here.

**Comment by Stebalien** [comment]
Yep. Note: I'd prefer a TOC over expanding/collapsing individual sections as the latter may break Ctrl+F.

**Comment by lanzafame** [comment]
Another aspect to this that I would love to see, is that every API resource/command section header should be a linkable anchor, i.e. docs.ipfs.io/reference/api/http#add should like to `/api/v0/add` section and clicking on the header will put the anchored version of the url in the url bar so when it comes to sharing links to the docs, it is easy to share exactly what you intend on forums and such. This is especially important if we are staying with a single page.

**Comment by hsanjuan** [comment]
Historical fact: It had a TOC and it was removed because it was effectively moved to the side-menu.

+1 to keeping Ctrl+F working.

They already have anchored links: https://docs.ipfs.io/reference/api/http/#api-v0-add. It's missing the anchor character thing that you can click to produce that link (but you can use the menu item). Anyway, that's an easy fix at: https://github.com/ipfs/http-api-docs

**Comment by jessicaschilling** [comment]
Closing, since this issue has been consolidated into the overall effort for improving/automating API/CLI documentation in #393. Comments have been migrated there!
