### ISSUE TITLE
Hotfix: Delete Basic Usage Link 

### ISSUE THREAD

**Issue by pkafei** [ipfs/docs#226]
`basic usage` links to [broken page](https://docs.ipfs.io/start/usage). Apparent fix is to delete `basic usage`.

**Comment by jessicaschilling** [comment]
@pkafei Where is this link? Screenshot or URL please?

**Comment by pkafei** [comment]
The link [is here](https://docs.ipfs.io/reference/go/overview/), and below is the screenshot. 
![Screen Shot 2019-07-25 at 6 44 33 PM](https://user-images.githubusercontent.com/1463964/61892603-76da5800-af0c-11e9-8d84-248bb515f0e9.png)

**Comment by jessicaschilling** [comment]
Thanks, @pkafei and @tapaswenipathak! Digging a little deeper, I think that the "basic usage" link originally pointed (in the old docs system?) to the content that now lives at https://docs.ipfs.io/introduction/usage/ . That said, even if we fixed the link, it would still be confusing -- that link points to the most basic getting-started guide, which isn't Go-specific. If a user is getting as far as the "Working with Go IPFS" page, they'll want reference docs specific to go-ipfs.

Going to make a minor editorial change to @tapaswenipathak's PR #234 for clarity, merge that in, and close this issue. Thanks!
