### ISSUE TITLE
Automate CLI documentation

### ISSUE THREAD

**Issue by Stebalien** [ipfs/docs#227]
Request: I'd like to be able to run `make` in this repo and regenerate _all_ documentation, including the CLI documentation. #212 added a script to generate docs but it would be great if:

1. This could be hooked up to `make`.
2. We could update a single version number somewhere to update to a new go/js IPFS release.

**Comment by jessicaschilling** [comment]
Flagging this as a potential hotfix, though I'm not sure who'd be able to implement this. @cwaring, any thoughts?

**Comment by jessicaschilling** [comment]
See issue #340 for the other half of this effort: Investigating the best way to get this done in VuePress.

**Comment by jessicaschilling** [comment]
Closing, since this issue has been consolidated into the overall effort for improving/automating API/CLI documentation in #393. Comments have been migrated there!
