### ISSUE TITLE
Hotfix: IPFS Public Archives

### ISSUE THREAD

**Issue by pkafei** [ipfs/docs#237]
[Public Archives](https://archives.ipfs.io/) is a broken link which displays a `ERR_SSL_PROTOCOL_ERROR` when clicking on it. You can find Public Archives below the Community heading on the https://docs.ipfs.io/ page.

Are the IPFS archives located in this Github repo https://github.com/ipfs/archives?

**Comment by jessicaschilling** [comment]
@pkafei -- thanks for flagging this! Looks like this happened as a result of the work being done here:
https://github.com/ipfs/archives/issues/179

That issue's work basically involves moving the content of archives.ipfs.io to https://awesome.ipfs.io/categories/datasets/ and then setting up a 301 (permanent) redirect from the former to the latter, so I'll just do it manually in our case by changing the "Public Archives" link to go to https://awesome.ipfs.io/categories/datasets/.
