### ISSUE TITLE
Create interface-ipfs-core for go-ipfs

### ISSUE THREAD

**Issue by diasdavid** [ipfs/docs#24]
https://github.com/ipfs/interface-ipfs-core/issues/66

**Comment by lgierth** [comment]
Need to implement/resolve ipfs/go-ipfs#3490 and ipfs/go-ipfs#3493

**Comment by lgierth** [comment]
This is not a docs issue -- go-ipfs core api work is tracked in ipfs/go-ipfs#4498 now
