### ISSUE TITLE
[CONTENT MIGRATION] Migrate and update the implementation status page

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#253]
The [implementation status page](https://github.com/ipfs/ipfs/blob/master/IMPLEMENTATION_STATUS.md) hasn't been changed since June 2018. Likely due for an update, and ought to be brought in to the main docs (currently it's linked to from the left nav).

ETA: Good examples provided by @eshon:
https://passbolt.com/roadmap
http://esri.github.io/ (less roadmap-specific, but interesting)

**Comment by ericronne** [comment]
Boo emojis don't render in issue titles :green_apple: :lemon: :tomato: :chestnut: 😞

**Comment by ericronne** [comment]
Is this table useful?

**Comment by ericronne** [comment]
Could it be _automated_? 😯

**Comment by jessicaschilling** [comment]
As a result of our card sort exercise, this may want to turn into a somewhat larger exercise, in which we create a table/chart depicting ...
- What IPFS does and doesn't do (i.e. there's no built-in blockchain)
- What implementations include what IPFS functionalities (this part is what incorporates the original reason for this issue)

This is likely to expand beyond the scope of a hotfix, so at minimum -- closing this hotfix issue is dependent upon assembling a plan for the assembly and deployment of this table/chart.

**Comment by johnnymatthews** [comment]
Not sure what the _implementation status_ is meant to represent. The original doc has disappeared. Could it just be incorporated into the [IPFS overview homepage](https://docs-beta.ipfs.io/)?

**Comment by jessicaschilling** [comment]
I think you can close this one.
