### ISSUE TITLE
Hotfix: OpenBSD link broken

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#254]
on the Go docs pg

![x](https://user-images.githubusercontent.com/9259185/63970269-4f296300-ca69-11e9-8ce0-ded9629bf29e.png)

**Comment by jessicaschilling** [comment]
The page in the docs where the broken link appears is
https://docs.ipfs.io/reference/go/overview/

There's also a broken link to building on OpenBSD on the go-ipfs docs readme:
https://github.com/ipfs/go-ipfs/tree/master/docs

@Stebalien, do you have any insight on this? I'm not seeing an "openbsd.md" document in any IPFS-related repo.

**Comment by Stebalien** [comment]
Let's just remove that. `make` should "just work" on openbsd.

**Comment by djdv** [comment]
For posterity looks like this was my doing 👀
https://github.com/ipfs/go-ipfs/pull/6338
