### ISSUE TITLE
Better integrate browser-addressing content with docs.ipfs.io

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#256]
Currently the `Addressing in Browsers` nav option on docs.ipfs.io links directly to [this helpful article](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md) on github. In order to create a more cohesive user experience, let's create an introductory page on the docs site, which then links to the full article. (This introduction should then be added to the article, as well.)

**Comment by ericronne** [comment]
@lidel 🙌

**Comment by lidel** [comment]
@ericronne  Is it safe to PR it under "Guides", or should I pause until after content juggling planned on friday?

**Comment by ericronne** [comment]
Whichever is most convenient for now is fine. It will very likely find a new home after friday :)

**Comment by ericronne** [comment]
@lidel did you get a chance to work on this one yet? It can go under "Guides" for now, thx!

**Comment by jessicaschilling** [comment]
hi @lidel ... just pinging you on this one. Do you still have time? Thanks!

**Comment by lidel** [comment]
I am really sorry, totally missed previous mention notification for this. 
I'll PR this doc when I am back next week.
