### ISSUE TITLE
[CONTENT MIGRATION] Migrate instructions for replicating large data sets

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#257]
[These instructions for replicating large datasets](https://github.com/ipfs/archives/tree/master/tutorials/replicating-large-datasets) are now several years old, but a nav button on the docs site links to them:

![image](https://user-images.githubusercontent.com/1507828/71021978-a3aa2a00-20bc-11ea-9d02-b1f7f3cded3c.png)

- [ ] Update the material (eg with content from — or pointers to — Cluster)
- [ ] Migrate the content to the docs VuePress site

**Comment by johnnymatthews** [comment]
I'm gonna close this issue. The post is pretty old and not particularly useful.
