### ISSUE TITLE
Improve the MFS documentation on docs.ipfs.io

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#259]
**_This issue is part of [Epic 3B: Fixes from legacy issue queue](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+3b%22+)._**

The [mfs page](https://docs.ipfs.io/guides/concepts/mfs/) on the docs site is sparsely populated, and includes a video from 2015. Thankfully, we've generated a 🚢-load of great content in the ensuing years. 

Cull information from these sources to make this page a pithy introduction to mfs, and a handy catalog of mfs-related educational material.

**Comment by ericronne** [comment]
A couple of resources:
- [Protoschool course](https://proto.school/#/mutable-file-system)
- [Understanding how the InterPlanetary File System deals with Files](https://github.com/ipfs/camp/tree/master/CORE_AND_ELECTIVE_COURSES/CORE_COURSE_A), from ipfs camp

**Comment by jessicaschilling** [comment]
This also ties in with older issue #89 for adding content from the poster sessions that happened in Berlin.

**Comment by 0zAND1z** [comment]
We are working on replicating the MFS file tree across the IPFS network. 

I'll watch this thread closely for any development and would love to contribute wherever possible.

**Comment by jessicaschilling** [comment]
@0zAND1z -- This issue isn't slated for immediate work, but we'd love to collaborate with you if you're interested in contributing (that also means we're able to get better info out to more people, more quickly)! What sort of contribution would you have in mind?

**Comment by jessicaschilling** [comment]
Closing this issue in order to consolidate it into work to be done in #89.
