### ISSUE TITLE
Summarize IPFS stack

### ISSUE THREAD

**Issue by lgierth** [ipfs/docs#26]
This is not about multiformats and libp2p, but about the components that make up the upper part: IPFS.

- fs-repo
- exchange
  - blockstore
    - datastores
  - bitswap
- data structures
  - ipld
  - dag-pb / merkledag
  - unixfs
- dnslink
- fs path / dweb link
- ipns
- gateway

**Comment by ZenGround0** [comment]
Thanks for the list Lars!

**Comment by lgierth** [comment]
Here's a diagram from js-ipfs: https://github.com/ipfs/js-ipfs#ipfs-core-architecture

**Comment by Mr0grog** [comment]
Do you think this should be part of #60 or separate?

**Comment by jessicaschilling** [comment]
Closing, since this is now included in #170.
