### ISSUE TITLE
Confirm accuracy of IPNS docs page, and expand it

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#260]
**_This issue is part of [Epic 3B: Fixes from legacy issue queue](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+3b%22+)._**

Is the info on the [IPNS concept](https://docs.ipfs.io/guides/concepts/ipns/) docs page still accurate? Double check that, and expand the page to make it a richer primer.

Additional content fodder …
- IPNS [specs](https://github.com/ipfs/specs/blob/master/naming/README.md)
- IPFS camp deep dives on [fast ipns](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/26-fast-ipns.md), [link rot](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/34-ipns-link-rot.md), and [rotating keys](https://github.com/ipfs/camp/blob/master/DEEP_DIVES/16-revocation-rotating-of-ipns-keys.md)
- [The definitive guide to publishing content on the decentralized web](https://medium.com/textileio/the-definitive-guide-to-publishing-content-on-ipfs-ipns-dfe751f1e8d0)
- [What is InterPlanetary Naming System(IPNS)?](https://hackernoon.com/understanding-ipfs-in-depth-3-6-what-is-interplanetary-naming-system-ipns-9aca71e4c13b)

**Comment by ericronne** [comment]
(expansion would fall outside of `hotfix` territory, so that can be split out into a separate issue, if need be)

**Comment by jessicaschilling** [comment]
Closing due to overlap with #90. Adding notes from this issue to that issue.
