### ISSUE TITLE
Hotfix: Confirm accuracy of DNSlink docs page

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#261]
[This page](https://docs.ipfs.io/guides/concepts/dnslink/) is about a year old; still 👍?

**Comment by jessicaschilling** [comment]
I know we recently added the line at the top redirecting folks to dnslink.io -- would love to hear thoughts from the folks who contributed to that guide (@jbenet, @whyrusleeping, @daviddias, @lgierth, @victorb) as to what we should do with this summary page going forward.

**Comment by ericronne** [comment]
Closing in favor of migration plan to be discussed in #268
