### ISSUE TITLE
feat: expand feedback widget response options

### ISSUE THREAD

**Issue by cwaring** [ipfs/docs#266]
Feedback captured from @ericronne:

> If it's quick to implement, could we offer a different message based upon whether they clicked yes or no? That might ease the blow for the no clickers, especially. If so, perhaps something like …
> 
> **Yes**
> "Glad to hear it! Thanks for your feedback."
> 
> **No**
> "Sorry about that. We're working to improve our documentation. In the mean time, please feel free to [file an issue](https://github.com/ipfs/docs/issues) to help us better understand the problem."

ref: #250 #265

**Comment by ericronne** [comment]
ah, but the understanding was that there would be _no additional feedack_, you see?
it was **you** who opened the floodgates by providing a "thank you" message!

… fine. ;)

**Comment by terichadbourne** [comment]
I'd be happy to give people the option to submit detailed feedback. However, because of "in the meantime," this phrasing... 

> "Sorry about that. We're working to improve our documentation. In the mean time, please feel free to file an issue to help us better understand the problem."

... says to me, "We are already fixing our documentation in the way we think is best. AFTER we do that we'll look at the feedback you submit." Could we instead rephrase to something like... 

"Sorry about that. We'd love to incorporate your feedback as we work to improve our documentation. Please feel free to file an issue to help us better understand the problem."

**Comment by terichadbourne** [comment]
This may have already been mentioned elsewhere, but if we could make it work with our processes I'd find it more user-friendly to open an optional text box submission in the browser for that feedback rather than ask them to file an issue, which feels much harder.

**Comment by jessicaschilling** [comment]
@terichadbourne — that wording is awesome, totally agree. 

As for the “why no text box”... yep. We can’t add that without going much deeper down a technical rabbit hole, so asking to file an issue for now. Really like how you added the referring page in the title of the resulting issue in how you do that for ProtoSchool, plus the pre-templated issue; we should take a similar if not identical approach with this one.

**Comment by cwaring** [comment]
> ah, but the understanding was that there would be _no additional feedack_, you see?
> it was **you** who opened the floodgates by providing a "thank you" message!
> 
> … fine. ;)

haha yeah, I first tried disabling the buttons after a selection but it didn't feel natural so this was the next best option.

**Comment by cwaring** [comment]
> This may have already been mentioned elsewhere, but if we could make it work with our processes I'd find it more user-friendly to open an optional text box submission in the browser for that feedback rather than ask them to file an issue, which feels much harder.

@terichadbourne yes I mentioned this in the [PR notes](#265#issue-314078849) but I agree it would be nice to also capture long-form comments. This can be done using a 2nd event if we wanted as an `event.label` can hold up to 500 bytes of information, which would provide a low barrier to entry and also anonymous.

However the option to file a pre-populated issue may worth the additional friction because we can then use the Github workflow to assign labels and follow up on any problems directly.

I suggest we discuss the pros/cons in the call today! :)

**Comment by cwaring** [comment]
The decision from our call today was to create an issue template and generate a pre-populated link directing people over to our issue queue, similar to what has been done in the [footer of a Protoschool lesson](https://proto.school/#/mutable-file-system/01).

As our primary audience are developers it feels safe to assume a high volume will already have Github accounts, which will decrease the barrier to entry. With the added benefits of integration into our task pipeline, to follow up with individuals and prevent spam polluting our analytics account.

**Comment by terichadbourne** [comment]
Just pasting screenshots of a similar feature I found on the notes website for my class, which uses a "Suggest an Edit" button at the top of every page that expands to a text box when clicked. : 

![image](https://user-images.githubusercontent.com/19171465/64544633-57995d80-d2f5-11e9-92a0-93a16ec6c313.png)

![image](https://user-images.githubusercontent.com/19171465/64544909-d68e9600-d2f5-11e9-903c-df9b311902a5.png)

Notes: 
- The button changes color on hover/click
- The main content pushes down so it can still be viewed while writing about it
- There are notes about kinds of feedback that are useful
- You can exit without submitting 
- In this case the site already knows who I am so it's pre-filling both the page I'm commenting on and my handle and email address (we'd just have the page info in our case)

**Comment by jessicaschilling** [comment]
Closing this issue per discussion on https://github.com/ipfs/docs/issues/266#issuecomment-528479779.
