### ISSUE TITLE
Explain how to install ipfs with ipfs

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/docs#27]
ref: https://github.com/ipfs/go-ipfs/issues/1952

**Comment by Mr0grog** [comment]
@whyrusleeping is this done with ipfs/go-ipfs#4390 or are you suggesting we should add a section to [`content/introduction/install.md`](https://github.com/ipfs/docs/blob/bef3dfa40523d1a9dc9018cf5047bf5767f9fa95/content/introduction/install.md)? (In which case, would you please re-title this to be a little more specific?)

**Comment by jessicaschilling** [comment]
@whyrusleeping -- this one got dredged out of the sands of time (March 2017). If it's not actually deprecated, please open a new issue and clarify? Many thanks!
