### ISSUE TITLE
[CONTENT IMPROVEMENT] No package core/corenet from examples

### ISSUE THREAD

**Issue by kpp** [ipfs/docs#270]
Example: https://docs.ipfs.io/guides/examples/api/service/readme/
Code from example:

```go
package main

import (
	"fmt"

	core "github.com/ipfs/go-ipfs/core"
	corenet "github.com/ipfs/go-ipfs/core/corenet"
```

**Comment by jessicaschilling** [comment]
@Stebalien or @whyrusleeping -- are you able to advise? Many thanks!

**Comment by Stebalien** [comment]
This is terribly out of date.

**Comment by jessicaschilling** [comment]
Does anyone have the bandwidth available to address, or are we better pulling the content entirely in the near term (would prefer not to, of course, but ...)?

**Comment by Stebalien** [comment]
Not in the short term (that I know of). If a contributor wants to tackle this, I'd recommend looking at how github.com/ipfs/ipget does this.

**Comment by jessicaschilling** [comment]
Attaching this to #291 for prioritization.

**Comment by jessicaschilling** [comment]
Ref #366 - that's the issue to rework the "Make your own IPFS Service" page, which is currently hidden.

**Comment by jessicaschilling** [comment]
Closing, as we are working this in #366.
