### ISSUE TITLE
no link named "go-ipfs" under CID

### ISSUE THREAD

**Issue by kpp** [ipfs/docs#276]
error

```
ipfs resolve -r /ipns/docs.ipfs.io/go/pkg/go-ipfs/core/coreapi: no link named "go-ipfs" under QmZGs3M2n6EWw8jvfcQjMqfmTr45As23wopQVZcb5shwtM
```

in

https://docs.ipfs.io/go/pkg/go-ipfs/core/coreapi
https://docs.ipfs.io/go/pkg/go-ipfs/core/coreapi/interface
https://docs.ipfs.io/go/pkg/go-ipfs/core/coreapi/interface/options

**Comment by jessicaschilling** [comment]
@olizilla and @Stebalien -- can you please have a look, as I think this issue with godoc2md may have happened as a result of #220? It's a breaking issue, so prioritization would be greatly appreciated.

In the meantime, cached versions from 10 September exist:
https://webcache.googleusercontent.com/search?q=cache:mYQlQ2ZlN6sJ:https://docs.ipfs.io/go/pkg/go-ipfs/core/coreapi/+&cd=1&hl=en&ct=clnk&gl=us
https://webcache.googleusercontent.com/search?q=cache:VmUBSWrrpggJ:https://docs.ipfs.io/go/pkg/go-ipfs/core/coreapi/interface/+&cd=1&hl=en&ct=clnk&gl=us
https://webcache.googleusercontent.com/search?q=cache:iAdbIblF7-QJ:https://docs.ipfs.io/go/pkg/go-ipfs/core/coreapi/interface/options/+&cd=4&hl=en&ct=clnk&gl=us

**Comment by Stebalien** [comment]
https://github.com/ipfs/docs/pull/277

**Comment by Stebalien** [comment]
Could someone with a faster internet connection test that (before merging)?

**Comment by jessicaschilling** [comment]
@kpp -- thanks for bringing to our attention!
