### ISSUE TITLE
Epic 4A: Review and ID IPFS Camp content

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#294]
## 4A. Complete review of IPFS Camp content identifying how it can be applied to create new ProtoSchool tutorials, enhance existing ones, or improve the docs.ipfs.io site
<img src="https://img.shields.io/static/v1?label=Priority&message=P0&color=red">

**_Find all issues associated with this epic [here](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+4a%22+)._**

### Deliverables
Generate the review and turn into prioritized GitHub issues (in ProtoSchool and docs repos)

### Owners
- @terichadbourne 

### Context
Please see the Documentation & Developer UX Working Group's [Q4 2019 OKRs](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909) for information on how this epic fits into the team's larger goal structure for the quarter.

**Comment by terichadbourne** [comment]
Heads up that I'm deleting this and replacing with an epic that lives in the ProtoSchool repo so I can work while filtered.
