### ISSUE TITLE
Epic 4C: Create/improve docs pages based on IPFS Camp content

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#296]
## 4C. Create or improve docs pages/entries using content adapted from IPFS Camp
<img src="https://img.shields.io/static/v1?label=Priority&message=P2&color=yellow">

**_Find all issues associated with this epic [here](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+4c%22+)._**

### Deliverables
Ship revised docs pages

### Owners
- @terichadbourne (identification)
- @mohnjatthews (integration)

### Context
Please see the Documentation & Developer UX Working Group's [Q4 2019 OKRs](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909) for information on how this epic fits into the team's larger goal structure for the quarter.

**Comment by jessicaschilling** [comment]
cc @mohnjatthews, since I can't assign him yet 😊

**Comment by terichadbourne** [comment]
Notes on IPFS Camp content are being collected here: https://github.com/protoschool/protoschool.github.io/issues/261

**Comment by jessicaschilling** [comment]
Closing this epic, since all actionable items have been accounted for in issues in either the docs or ProtoSchool repos. Thanks!
