### ISSUE TITLE
Add guide on using ipfs-update

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/docs#3]
We should have a guide on installing ipfs, updating it, and the best practices (and troubleshooting) therein.

**Comment by hsanjuan** [comment]
Ok i'll draft this. Should this live in go-ipfs? on the website?

**Comment by lgierth** [comment]
I'd say website

**Comment by hsanjuan** [comment]
I think I did this because there is a section: https://ipfs.io/docs/install/#installing-with-ipfs-update
