### ISSUE TITLE
Creating basic examples on how to use go-ipfs Programatically (with the Core API)

### ISSUE THREAD

**Issue by daviddias** [ipfs/docs#300]
Examples such as https://docs.ipfs.io/guides/examples/api/service/readme are out of date and the Documentation of the go core API has a big TODO -- https://github.com/ipfs/interface-go-ipfs-core#documentation --. This means that, AFAICouldFind, there are no set of basic examples on how to spawn your own go-ipfs node from a Go Program.

It would be extremely helpful to have at least 1 to 2 examples that show users how they can use go-ipfs from their go programs. For inspiration:

- Tutorial IPFS 101 https://github.com/ipfs/js-ipfs/tree/master/examples/ipfs-101
- Tutorial Building a File Sharing Application  https://github.com/ipfs/js-ipfs/tree/master/examples/exchange-files-in-browser

**Comment by jessicaschilling** [comment]
Great point. The existing team doesn’t have the bandwidth to swarm on this right now, unfortunately; do you have an inclination to knock out a rough draft (I’m more than happy to copy edit), or do you have recommendations for someone who can take this work in? Thank you!

**Comment by daviddias** [comment]
Understood. I was looking for an example I could use myself. It is currently unclear to me how much of the CoreAPI for go-ipfs -- https://github.com/ipfs/interface-go-ipfs-core -- is ready/done/released. Once I get something to work cleanly, I'm happy to allocate a couple of hours getting a 101 example written.

**Comment by jessicaschilling** [comment]
Yay, thanks! I found those legacy examples last week while working on something else, but based on accuracy of the legacy examples already on docs.ipfs wanted to take a closer look before releasing back into the wild. If you’ve found ones you want to release right away lmk — it’s reasonably quick for me to do that legwork.

**Comment by daviddias** [comment]
Update: I started working on this example. Code being written here https://github.com/ipfs/go-ipfs/pull/6695

**Comment by jessicaschilling** [comment]
Awesome, please keep us posted 😊

**Comment by daviddias** [comment]
Hiiii docs team! Got something for you https://github.com/ipfs/go-ipfs/pull/6695 

It's complete and ready for review. Would love to get this shipped soon and potentially also ship a blog post to let our users know that they can use IPFS in this way as well.

**Comment by jessicaschilling** [comment]
From @daviddias re where to put this guide in the legacy nav: note that we're addressing the js-ipfs examples in the new beta nav. But will hide the "make your own service" link per screenshot.
![image.png](https://images.zenhubusercontent.com/5ce5bf88b1698b1ceb4ce811/7202cf56-199b-4d10-8052-869cf48513d2)

**Comment by daviddias** [comment]
It has beeeen meeeerged \o/ https://github.com/ipfs/go-ipfs/tree/master/docs/examples/go-ipfs-as-a-library :D

**Comment by daviddias** [comment]
Got you a blog post as well https://github.com/ipfs/blog/pull/322 :D

**Comment by jessicaschilling** [comment]
Link added in legacy docs site! Queued up in the beta as well. Thank you!
