### ISSUE TITLE
Draft content for "is this helpful" widget

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#304]
**_This issue is part of [Epic 2B: Release enhanced "is this helpful" feedback mechanism](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+2b%22+)._**

Draft the content to be used in the next-generation "is this helpful" widget, including ... 
- Considerations raised in #266 .
- Definition of metrics to be collected, and how they might be collected

**Comment by jessicaschilling** [comment]
cc @mohnjatthews, since I can't assign him yet 😊

**Comment by ericronne** [comment]
Drafting "in situ" over at #305, will update this once content is finalized.

**Comment by jessicaschilling** [comment]
I think we're good to close this, since the discussion's all happening in #305.
