### ISSUE TITLE
Create visuals for "is this helpful" widget

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#305]
**_This issue is part of [Epic 2B: Release enhanced "is this helpful" feedback mechanism](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+2b%22+)._**

Design visuals (wireframes may or may not be needed first) for next-generation "is this helpful" widget, including generating any artifacts needed for front-end implementation.

**Comment by ericronne** [comment]
Removed #304 dependency, since i'm drafting this content in visual form. I'm "wiring" it up in the context of the current site design, in order to hammer out the interaction details in a realistic way in advance of the beta-site design. It doesn't seem like a good use of time to implement this on the current docs site, but i defer to @cwaring on that point.

This issue should remain open until the final design and content is finalized, and ready for implementation on the beta site.

**Comment by ericronne** [comment]
## Default
_Here i've promoted the "Edit this page in GitHub" feature out from footer-bound obscurity, giving frustrated-but-motivated users handy access to the source file._

**Content**
Was this information helpful?
[ Yes ]  [ No ]
Edit this page on GitHub

![was this helpful](https://user-images.githubusercontent.com/9259185/66229067-9f1dca00-e6a6-11e9-90d2-514aa78cdc18.png)

## "No" clicked
_Feedback form expands, enabling users to describe how the page failed to help them. "Or if you prefer, file an issue on GitHub" also appears, as a secondary option._

**Content**
Sorry to hear that
How can we improve it?
(text box, submit button)
Or if you prefer, [file an issue](https://media0.giphy.com/media/12hpC2gDGPBxRu/giphy.gif?cid=790b7611a5d91785f0cf3fd0dd52ce47e7e9b2114493b83f&rid=giphy.gif) on GitHub.

![nope](https://user-images.githubusercontent.com/9259185/66229072-a47b1480-e6a6-11e9-9b35-15d965f92af8.png)

## Yes clicked or form submitted
**Content**
Thanks for your feedback!

![thanks](https://user-images.githubusercontent.com/9259185/66229078-a8a73200-e6a6-11e9-8a9c-6cc270d75e8a.png)

**Comment by jessicaschilling** [comment]
This is excellent. Does @cwaring have room to put this on a boat? Is the boat too full?

**Comment by ericronne** [comment]
Regardless of whether we implement the expanded-feedback feature on the current site, let's go ahead and shift the "Edit this page on github" link up on the page (per our weekly chat this morning), thusly …

![move the link](https://user-images.githubusercontent.com/9259185/66763220-186aa900-ee6d-11e9-89a6-03fd844f9946.png)

**Comment by cwaring** [comment]
Also suggested on today's catchup: a minimum first pass implementation would be to add action links to "file an issue" and/or "edit this page" after somebody gives feedback.

**Comment by jessicaschilling** [comment]
@ericronne, do you mind revising the mockups based on @cwaring's most recent comment when you get the chance? Thank you!

**Comment by ericronne** [comment]
LGTM

![image](https://user-images.githubusercontent.com/9259185/67218642-5414ee00-f3ec-11e9-8ed2-0544de48763a.png)
