### ISSUE TITLE
Implement "is this helpful" widget

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#306]
**_This issue is part of [Epic 2B: Release enhanced "is this helpful" feedback mechanism](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+2b%22+)._**

Duplicate "is this helpful" widget from legacy site, including wiring up any metrics collection.

**Comment by jessicaschilling** [comment]
Artifacts are finished in #305 and are ready to implement whenever the time is right!

**Comment by terichadbourne** [comment]
Screenshot from vuejs.org where they add a smidge more context on why you'd edit on GitHub:

![image](https://user-images.githubusercontent.com/19171465/67218461-672bbc00-f3f4-11e9-95e9-c1231029989a.png)

**Comment by jessicaschilling** [comment]
@terichadbourne - Love that language! Let's do the same on the docs beta. 
@ericronne @cwaring , there's no point in changing the visuals mocked up in #305, but instead of just "Edit this page on Github", let's maybe do the following:
"Found an error or want to contribute to IPFS docs? (link)Edit this page on GitHub.(/link)"

**Comment by jessicaschilling** [comment]
Closing this issue via https://github.com/ipfs/ipfs-docs-v2/pull/41 😊
