### ISSUE TITLE
Draft deprecation plan steps for legacy site

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#308]
**_This issue is part of [Epic 1B: Define legacy site deprecation plan](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+1b%22)._**

Use this issue as a scratchpad for drafting steps in the deprecation plan; the intent is to provide a place for the entire time to add notes that come to mind as research/testing/implementation of the beta site progresses.

Once we feel reasonably comfortable with its completeness, move on to crating a more final plan under #309.

**Comment by jessicaschilling** [comment]
cc @mohnjatthews, since I can't assign him yet 😊

**Comment by jessicaschilling** [comment]
Open question: Will we preserve this ipfs/docs repo and migrate VuePress files into it, or will we deprecate this repo in favor of the beta one?

**Comment by cwaring** [comment]
I suggest that we continue to use this repo for management and then transfer remaining open issues to [ipfs-docs-v2](https://github.com/ipfs/ipfs-docs-v2) when we are ready to switch, deprecating this one. That way we retain the development history in the new repo.

**Comment by jessicaschilling** [comment]
Closing this issue, since much of this has been discussed in various meetings and I'm currently assembling the results under #308.
