### ISSUE TITLE
Consolidate deprecation brainstorm into defined plan

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#309]
**_This issue is part of [Epic 1B: Define legacy site deprecation plan](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+1b%22)._**

**DELIVERABLE DOCUMENT IS HERE: https://hackmd.io/-JU3CcXgSgmcXWszyku2PA**

Consolidate the notes generated under #308 into a deprecation plan. This plan should include a checklist for everything that needs to be done for successful migration and closing of old platform, including alerts on old content, redirects, broken-link searches, etc, PLUS timeline for such. Timeline need not be calendar-based, but should be reasonably defined in relative/sequential terms (e.g. action x should take three weeks).

**Comment by jessicaschilling** [comment]
cc @mohnjatthews, since I can't assign him yet 😊

**Comment by jessicaschilling** [comment]
I've taken a pass at a deprecation/migration checklist: https://hackmd.io/-JU3CcXgSgmcXWszyku2PA
@johnnymatthews and @cwaring -- can you please have a look to see if this is solid enough for us to close this issue? Thank you!

**Comment by johnnymatthews** [comment]
Just made some modifications, mainly:

1. Yes, we should keep sitemaps and SEO stuff for consistency.
2. For the ipfs/docs repo, let's archive the current one, and rename ipfs/ipfs-docs-v2 to ipfs/docs. That should fix most broken links. Plus, when you rename a repo GitHub does automatic redirects for you, I think.
3. Let's use the analytics to give us a list of all inbound GitHub links, then run pull-requests on those repos to fix any relevant links.

**Comment by terichadbourne** [comment]
I'd be surprised if we can keep the current site at `ipfs/docs`, archive it, and then rename `ipfs/ipfs-docs-v2` to `ipfs/docs`. My assumption is that we'd need to first rename `ipfs/docs` to `ipfs/docs-legacy` (or similar), archive it, and then rename `ipfs/docs-v2` to `ipfs/docs`.

**Comment by jessicaschilling** [comment]
@terichadbourne Good point, do you mind editing the HackMD accordingly?

**Comment by johnnymatthews** [comment]
Yeah you're right @terichadbourne! Just tried to archive a repo and then create a repo with the same name and GitHub wouldn't let me. Nice catch!

**Comment by terichadbourne** [comment]
Made some edits but I'm honestly quite confused about the order of operations more broadly. Like why would we be re-sorting the GH repos two days AFTER making the transition to showing v2 as the live website? I'm used to using GH Pages so maybe I'm not understanding how our infra works. 

Also, note that "Warning: If you create a new repository under your account with the same name as the transferred repository, existing redirects to the transferred repository will break. Instead, use a different name for the new repository."  (https://help.github.com/en/github/administering-a-repository/renaming-a-repository)

So in the plan we've just adapted to, where the new site's repo ends up named the thing the old site's repo used to be named, if you try to follow a link to ipfs/docs/something.md, instead of the default behavior of redirecting to ipfs/docs-legacy/something.md, it will instead keep attempting to direct to ipfs/docs/something.md (in the NEW contents of the reused-name repo). Do we expect every file people would link to in the repo to still exist, so that's okay, or is this a problem?

**Comment by johnnymatthews** [comment]
This could be a problem. Another solution could be to create a new branch called `new-docs`, and put everything in `ipfs/ipfs-docs-v2` into there and set `ipfs/docs:new-docs` as the _main_ branch. Then three months or so down the line remove everything from `ipfs/docs:master`, merge in everything from `ipfs/docs:new-docs`, and then set the `ipfs/docs:master` as the _main_ branch again. This way we don't lose any branch history and we get to keep all our issues.

**Comment by jessicaschilling** [comment]
One good thing about archiving ipfs/docs and NOT moving ipfs/ipfs-docs-v2 to that namespace means, as @terichadbourne pointed out, we can take advantage of GH's auto-redirecting, and the automatic "this repo has been archived" notices that GH posts in banners.

Teri's also got a really good point that URLs to .md documents (nor issue numbers) aren't going to remain consistent from legacy to new site, so there's maybe not point in moving ipfs/ipfs-docs-v2 ... and that it may do more harm than good.

It might be a good idea, though, to rename ipfs/ipfs-docs-v2 to something that sounds a little less transient or tied to a particular version ... maybe even just ipfs/documentation, heh.

I've updated the HackMD accordingly with those thoughts ... we don't have to make a decision right now, we just have to be prepared to make a decision when we start down this process. Capturing all these notes will help us make a choice when the time comes.

@terichadbourne -- as for order of events, this document was really just to capture rough timelines. Regarding why we'd change the repo names after the fact -- as I understand it, it doesn't really matter what the repo is *called* in terms of what the website user sees. We'll want to search the repo for instances of `ipfs-docs-v2` to make sure we aren't hard-linking to anything that will disappear (just added that item to the deprecation plan), but if I understand correctly, renaming the repo shouldn't break the site itself. @cwaring will have better info, though.

**Comment by terichadbourne** [comment]
@johnnymatthews do you mean that we'd essentially be merging the old site into the new one and overwriting it all, with the old site available in the history? I assume it would still have the same problem I raised, in that it would try to find a specific markdown file or whatnot that doesn't exist anymore, so may not be helpful unless I'm misunderstanding your goal. 

@jessicashilling I agree that if we determine we can't use `ipfs/docs`, `ipfs/documentation` would be better than `ipfs/docs-v2`. 

Are people really sharing links to the GH repo, though, as opposed to to the site itself? I can envision people sharing links to https://github.com/ipfs/docs or https://github.com/ipfs/docs/CONTRIBUTING.md - both of which would probably match the new repo's structure -  but not to https://github.com/ipfs/docs/blob/master/content/guides/guides/addressing.md - which is the type of link that would be less likely to end up in the same place.  They'd be sharing a link to the live site for something content-based like that, in which case my understanding is that we'll already have stuff in place to help with those website redirects or default to search if it fails. So overwriting the repo might not necessarily be a problem, and we could put a note on the main readme about where to find the legacy pages. ¯\_(ツ)_/¯ 

My thought about infra was that it's going to be a pain to ask someone to host a new site from GitHub onto however it's being hosted and then ask them to change it out to use a different repo as the source, whereas if we changed the repo name first they could just do it once. I may be off base here, though, or my proposal might involve a couple hours of having NO docs site live. Or maybe if we do the thing where the old repo and new repo use the same name it's magically much easier for the infra. I clearly have no idea. 😂

**Comment by johnnymatthews** [comment]
Yeah @terichadbourne I was misunderstanding the problem. My solution wouldn't work. But yeah, you bring up a good point, do people share GitHub links directly? If docs are available on a website I'll pretty much always share that link, rather than sift through GitHub repos for docs.

**Comment by jessicaschilling** [comment]
All -- this has been a super-useful discussion. It sounds like we're ready to call this phase of the effort done, with the knowledge that we're all mulling over what to do about the potential repo location switchery, and the understanding that we'll still need to make a final decision on that once we sync up this checklist with a real-world calendar.

I'm going to close this issue, since we'll be working with assigning the checklist to calendar dates in 2020, but please feel free to continue discussion here or in the [checklist itself](https://hackmd.io/-JU3CcXgSgmcXWszyku2PA) for posterity ... and of course feel free to re-open the issue should anything major arise. Thank you!
