### ISSUE TITLE
Features List: Examples of other projects with great documentation

### ISSUE THREAD

**Issue by TKorr** [ipfs/docs#31]
I thought I'd help out by giving a few links to other open source projects with great documentation that I have come across. Learning from good examples would be a good start. This list is by no means exhaustive so please add more...

[**Python**](https://docs.python.org/3/)
what to like: 
- simple
- good use of white space
- consistent style and format throughout
- can flip between versions
built with: Sphinx

[**Pandas**](http://pandas.pydata.org/pandas-docs/stable/)
what to like: 
- excellent examples
- whole section displayed in one page instead of multiple pages
- table of contents stays open (but doesn't track with the scroll bar which is a pain)
- can flip between versions
built with: Sphinx

[**scikit-learn**](http://scikit-learn.org/stable/documentation.html)
what to like: 
- lots of description for each section with examples, great for learning
- provides reference material in each section
- a [flowchart](http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html) to help guide
 starters
- can flip between versions
built with: Sphinx

[**Django**](https://docs.djangoproject.com/en/1.10/)
what to like: 
- starts with a tutorial
- consistent style
- provides a how-to-guide
- simple color pallette
- can flip between versions
built with: Sphinx

[**Trac**](https://trac.edgewall.org/wiki/TracGuide)
what to like:
- table of contents stays the same on every page so you can navigate around quickly
- very simple layout
- uses color in line with branding
built with: Trac Wiki

[**Ceph**](http://docs.ceph.com/docs/master/#)
what to like:
- use of a colour scheme that relates to the logo/branding
- mostly about setting it up getting it working quickly, separates details out to another section
- separate architecture section
built with: Sphinx, reST

[**Angular**](https://angular.io/docs/ts/latest/)
what to like:
- separated table of contents uses drop-downs to give users flexible navigation
- has a cheat sheet
built with: _not sure, couldn't find it in the docs!_

Others:
[**MongoDB**](https://docs.mongodb.com/manual/introduction/)
[**git**](https://git-scm.com/doc)
[**Chef**](https://docs.chef.io/)
[**Ansible**](http://docs.ansible.com/ansible/index.html)
[**D3**](https://github.com/d3/d3/wiki)

Further possible actions to take:
- [ ] Decide on a color scheme, how will it differ between projects/repo/components but still retain the IPFS brand
- [ ] Decide on a schema, or a "separation of concerns" for documentation. how do we separate out each area of communication for different users whilst maintaining consistency across the repos
- [ ] Decide on which set of tools to use, Sphinx, wiki, reST etc...

**Comment by cwaring** [comment]
Hi @TKorr, thanks for taking the time to list out these! We're gearing up for a new documentation upgrade so I've added your notes to our review list –perhaps a little late but appreciated all the same :)
