### ISSUE TITLE
Docs beta metrics collection: Implement

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#311]
Implement collection of the metrics defined in #310, including means of displaying/reporting on a twice-monthly basis.

See https://github.com/ipfs/docs/issues/310#issuecomment-562165787 for the list of metrics to be collected.

**Comment by johnnymatthews** [comment]
I take it we have a GA account for monitoring this stuff. Who's the point of contact for that? I might be able to link up the analytics and take some of the weight off you @cwaring if I can get access to the GA account.

**Comment by cwaring** [comment]
@johnnymatthews yep, GA is already setup. Electric can grant you account access if you ask nicely.

**Comment by johnnymatthews** [comment]
Nice, got access now. I'll start setting up the metrics from #310.

**Comment by jessicaschilling** [comment]
For reference, here's the list of things to be implemented per @johnnymatthews' report: https://github.com/ipfs/docs/issues/310#issuecomment-562165787

**Comment by jessicaschilling** [comment]
I've taken a first pass at setting up a Google Data Studio report here:
https://datastudio.google.com/open/1IfRhGSN06uVIHfjIG2Pn1n8s54yx35Kq
If you feel that you should be an admin on this report, but didn't receive an invitation, please let me know.

I was able to set up reporting for most of @johnnymatthews' parameters as listed in https://github.com/ipfs/docs/issues/310#issuecomment-562165787, though a few are somewhat inferred: e.g., user frequency isn't an explicit value but we can easily look at number of sessions, percentage of new sessions, new users, etc. **However, some items still need to be looked at/fixed/added by either @cwaring or @johnnymatthews:**
- I'm not sure if the average page load time (which appears in several tables) is set up correctly; can @cwaring or @johnnymatthews please take a look?
- @cwaring, can you please set up an event for page search bar terms and add the results to the report?
- @cwaring, can you please add results for the "is this useful?" and stub page prioritization buttons? I inserted some dummy screenshots for now based on the legacy docs reporting
- @cwaring, are you able to look at best ways to examine internal and outbound links, so we can improve common page interactions and see which channels are being used most when folks are leaving the site? I've added some notes in the report itself that you might find helpful.

This report is set to trigger an email every Wednesday; right now that's only going to the docs WG members, but happy to add others to the email once we have enough data aggregated for the report to be useful.

**Comment by jessicaschilling** [comment]
Update: https://github.com/ipfs/ipfs-docs-v2/pull/41 implements the track-ability necessary to include the remaining custom events in this report 😊
@cwaring, much appreciated, and let me know if I can take over any work on wrapping this issue up!

**Comment by cwaring** [comment]
✅📈

**Comment by jessicaschilling** [comment]
Thanks! Going to re-open the issue until we actually get these into the Data Studio report. Let me know how I can help, @cwaring.

**Comment by cwaring** [comment]
Good call it's on my radar but happy to keep this marker until it's working. The data should be visible tomorrow after the test events have propagated, so we can configure the report then.

**Comment by jessicaschilling** [comment]
Sounds great. If you have the time to teach me to fish, I'll go fishing.

**Comment by jessicaschilling** [comment]
Wrapped up the Data Studio dashboard in a good-for-MVP way; had to hedge a bit around approximating some of the metrics @johnnymatthews asked for, but this’ll give us a lot of good insight for a while. We can always refine later on. :blush: Calling the issue done … https://datastudio.google.com/u/0/reporting/1IfRhGSN06uVIHfjIG2Pn1n8s54yx35Kq
