### ISSUE TITLE
Make sure search works

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#317]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

**PRIOR TO BAREBONES BETA LAUNCH**
- Review all existing H2s in content and edit them to better optimize for out-of-the-box Vuepress search
- Keep in mind how people reacted or struggled in in-person testing
- If possible, re-test before launch

**LATER**
- Collect and test common keywords in order to be confident that search on the docs beta works correctly.
- Also discuss whether it's a good idea to collect search data temporarily after launch for purposes of optimizing our site as a whole.

**Comment by jessicaschilling** [comment]
cc @mohnjatthews, since I can't assign him yet 😊

**Comment by jessicaschilling** [comment]
For purposes of barebones beta launch milestone -- let's do a review of all existing H2s in content and see if they can be better optimized for the out-of-the-box Vuepress search. (We'll dig into better search, probably Algolia, later.)

@johnnymatthews, do you have time to take this on?

**Comment by jessicaschilling** [comment]
@johnnymatthews -- now that you've merged the PR, could you please confirm behavior is improved? Minimum is just doing it yourself 😊 but if there's time, ideally would be to confirm via a quick video call with observing someone else playing with it. Thank you!

**Comment by johnnymatthews** [comment]
Things are improved from my end, but as you pointed out it'd be good to get someone else outside of the docs project to test things.

**Comment by jessicaschilling** [comment]
For the sake of rapid iteration, perhaps you could have a quick conversation with @lidel or @mikeal or @jimpick to walk through the search (aka just ask them to play with it for a bit)? Is that something you might be able to do this week?

**Comment by jimpick** [comment]
I'd love to help out!

**Comment by johnnymatthews** [comment]
The reaction from the testing was very positive. The main feedback was that some pages (Merkel DAGs and Content Addressing and CIDs, for example) should separate into more digestible chunks. These topics are pretty complicated, so it makes sense to create more straightforward posts that are easier to understand.

However, from a searching stand-point, everything looks good!

**Comment by johnnymatthews** [comment]
> collect search data temporarily after launch

Probably not a terrible idea to just collect search data all the time, just a long as it's not tied to any particular user. I'll raise this point in #310.
