### ISSUE TITLE
Determine best-fit features voting mechanism

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#318]
**_This issue is part of [Epic 2D: Vote on and prioritize docs beta features](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+2d%22)._**

Determine the best tool to use for allowing internal and community users to vote on which [features](https://docs.google.com/spreadsheets/d/1YJ8yuzoNeunVr3ftvm7x2nIKsj7IlTrsfuy71ZnGg6Y/edit?usp=sharing) they'd like to see prioritized in future releases.

**Comment by ericronne** [comment]
[Gitbook's feature-request](https://gitbook.canny.io/) page is nice

**Comment by cwaring** [comment]
+ https://canny.io/
+ or similar: https://www.producthunt.com/alternatives/canny-3

**Comment by jessicaschilling** [comment]
I contacted Canny to see if we qualified for special pricing as an open-source project. Will update as I learn more ...

In the meantime, screenshot of their full-price pricing: 
![image](https://user-images.githubusercontent.com/1507828/66685355-8169db00-ec39-11e9-8b01-5626d0a3dd72.png)

**Comment by cwaring** [comment]
Great, thanks @jessicaschilling. I agree their base pricing a bit too steep so hopefully that have an OSS plan.

**Comment by jessicaschilling** [comment]
We've been given a free-access account from Canny (hurrah, thanks!) and I'm working on getting this set up ... it'll be at a URL based on https://ipfs.canny.io, but will post the follow-on details in #319. Closing this issue, thanks!
