### ISSUE TITLE
Populate/launch features voting mechanism

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#319]
**_This issue is part of [Epic 2D: Vote on and prioritize docs beta features](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+2d%22)._**

Once the best-fit voting mechanism has been decided upon per #318, populate an instance of it with the features from our [features list spreadsheet](https://docs.google.com/spreadsheets/d/1YJ8yuzoNeunVr3ftvm7x2nIKsj7IlTrsfuy71ZnGg6Y/edit?usp=sharing) and launch. This likely won't involve a lot of coding on our end, since it'll use a third-party service; however, may involve some visual design for continuity with our existing design language.

**Comment by jessicaschilling** [comment]
We've got a free-access account on Canny at https://ipfs.canny.io, but we still need to set up and populate the features list for voting. Watch this space!

**Comment by cwaring** [comment]
nice, would you mind sending me an invite? I'm wondering if we can setup multiple spaces for different projects otherwise `ipfs-docs.canny.io` might be a better url

**Comment by jessicaschilling** [comment]
@cwaring You should have an invite in the email already 😊

**Comment by cwaring** [comment]
⏳

**Comment by jessicaschilling** [comment]
Admin access should be fixed now -- if you don't have admin access and feel that you should, contact me!

**Comment by cwaring** [comment]
confirmed, thanks 🙌

**Comment by jessicaschilling** [comment]
I've populated https://ipfs.canny.io/docs-features with the features from last quarter's prioritized features list, minus the ones that we know we're already heavily prioritizing.

@cwaring @ericronne -- can you please take a look to see if it's complete, and then let's talk about best practices for launch? Thanks!

**Comment by jessicaschilling** [comment]
Notes from today's [WG meeting](https://docs.google.com/document/d/1EOD-pJi4GvRmGi9HHocgVV8uVHMFIZlyVgJDkvC3DQ4/edit#heading=h.5e2btnkzo00n) on launch socialization:
- Newsletter
- Social media
- Docs repo readme
- Beta site: API integration directly in the site?

**Comment by ericronne** [comment]
Can we swap in [this version of the logo](https://drive.google.com/open?id=1jHD0nSo356H5Xsdd0Noro3uYjvgtQAVu) (where IPFS isn't obscuring the symbol)?

**Comment by jessicaschilling** [comment]
@ericronne good call.
![image](https://user-images.githubusercontent.com/1507828/67694135-7f598900-f968-11e9-9e3f-edd775db5bde.png)

**Comment by jessicaschilling** [comment]
Quick status update on this one -- we don't intend to socialize this until the public beta launch, but in the interim, @cwaring is thinking on if we want a deeper integration of Canny into the docs itself rather than just linking to the external page. (As part of longer-term strategy than just this features prioritization effort, this could be really useful.)

**Comment by jessicaschilling** [comment]
@cwaring - can you please whatever branch has this in the header, so we can close it out?

**Comment by cwaring** [comment]
This is now linked from the beta as an MVP, closing for now.
