### ISSUE TITLE
Set up beta repo with VuePress app

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#327]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

Set up a temporary docs beta repo with a boilerplate VuePress app. Note that the contents of this beta repo will eventually be moved into the main ipfs/docs repo, so issues should continue to be placed in ipfs/docs, not the new repo.

**Comment by cwaring** [comment]
[📚✨](https://github.com/ipfs/ipfs-docs-v2)

**Comment by jessicaschilling** [comment]
@cwaring YAY! Where is it?

**Comment by cwaring** [comment]
follow the emojis...

**Comment by jessicaschilling** [comment]
Faaaaancy!
