### ISSUE TITLE
Set up CI and deployment for beta site

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#328]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

Set up deployment and continuous integration for docs beta site.

**Comment by cwaring** [comment]
Netlify is configured for the staging site, we will need to setup a `cname` record for our custom domain when we migrate to a public beta.
