### ISSUE TITLE
Create hi-fi wireframes for docs beta theme, with css adjustments

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#329]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

Create wireframes for theming the docs beta site, keeping in mind ... 
- How deep we want to go into full customization vs out-of-the-box theming
- Affordances for space required by future features

**Comment by jessicaschilling** [comment]
This is pretty: https://gridsome.org/docs/#alternatives

**Comment by ericronne** [comment]
Here's a kitchen-sink layout which illustrates some style options for discussion, desktop flavor.
**[Sketch file](https://drive.google.com/a/protocol.ai/file/d/1F-AIGHRfI3Bj-Hk_xWxTcCGpBt4dJl9S/view?usp=sharing)** on the drive

![ipfs-docs-style-tile-A](https://user-images.githubusercontent.com/9259185/68242374-0399b500-ffd6-11e9-8a10-2b5fd21048a3.png)

**Comment by jessicaschilling** [comment]
@ericronne -- Awesome! One question, one request ...
Question: Is the "S" in "IPFS" in the header weirdly big?
Request: I'm pasting in here the OOTB style for alerts/tips/etc. Do you want to tweak those at all, or alternatively, tweak the "related content" boxes in any way to play well with the alerts/tips?
![image](https://user-images.githubusercontent.com/1507828/68242571-0395b700-ffce-11e9-80a7-b70999f88a62.png)

**Comment by ericronne** [comment]
@jessicaschilling Sketch messed with the vectors, in its well-intended-but-poorly-implemented quest to make the entire universe align to a pixel grid. The svg will render fine when implemented.

Modest mods to the alert design are also on my radar!

**Comment by ericronne** [comment]
Styling for callout boxes.
Happy to create sep issues for these bits, for granular management. Issue getting bloated.

![callout boxes](https://user-images.githubusercontent.com/9259185/68612826-050a2800-0483-11ea-86e1-ca400eb62cbe.png)

**Comment by jessicaschilling** [comment]
@ericronne - thank you!
@cwaring - is this enough for you to get started on styling?

**Comment by jessicaschilling** [comment]
Update: A number of these ended up in individual issues related to https://github.com/ipfs/docs/milestone/3. I'll separate the remaining ones into their own issues for bite-size pieces to handle in Q1.
