### ISSUE TITLE
Content Enhancement: Make an FAQ in discourse by curating existing threads

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/docs#33]
Use an "FAQ" tag to flag threads that have good answers to common questions. Consider rewriting the titles of those threads to be appropriately descriptive -- often the good threads have completely unrelated or confusing titles.

**Comment by Mr0grog** [comment]
Is this different from the [“Old FAQ”](https://discuss.ipfs.io/c/help/Old-FAQ) label, or is that this and did we do it?

**Comment by Mr0grog** [comment]
@flyingzumwalt Can you provide any updates here?

- Is this effectively done or dropped and should be closed?
- Is it just really low priority? (Can/should other people help? How?)
- Are you coming back around to work on it soon?

**Comment by mikeal** [comment]
I haven't seen such an FAQ and we don't have bandwidth yet in my group (which is only me until we finish out some hiring) to write it today.

I'm +1 on creating this resource though. We should find a way to maximize the SEO on each question so that Google searches surface the right answers.

**Comment by jessicaschilling** [comment]
This is still a great idea -- but let's make sure that before we tackle it, we've got a good overall strategy for FAQ on docs.ipfs.io vs FAQ in Discourse. (That said, flagging important Discourse threads will help us no matter what we end up doing -- so if anyone wants to take on the flagging/tagging, please do!)

**Comment by jessicaschilling** [comment]
Closing this, since it's being addressed in #223.
