### ISSUE TITLE
Implement docs beta theme

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#332]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

Front-end implementation of the visual design artifacts for docs beta theming created under #330, including colors, fonts, etc.

**Comment by cwaring** [comment]
First stage complete.
