### ISSUE TITLE
Research Algolia search integration

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#336]
Research whether Algolia is a good fit for search integration for the docs VuePress site, particularly keeping in mind the benefits and/or drawbacks for offline search. If integrating Algolia emerges as a recommendation from this issue, capture the integration effort in a separate issue.

**Comment by cwaring** [comment]
I've applied to have the beta site indexed by Algolia and will update this once we've been accepted.

![CleanShot 2020-01-10 at 12 55 09](https://user-images.githubusercontent.com/106938/72154564-e9e76600-33a8-11ea-9664-6e3e8cd4c350.png)
