### ISSUE TITLE
Design/implement callout links between legacy and beta pages

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#341]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

Design and implement banners or similar callouts to appear on both the legacy and beta docs sites:
- On legacy site, invite users to view the same content on the beta site
- On beta site, inform users that they're on a beta, with opportunities to ...
     - Return to legacy site
     - Submit feedback on beta site
     - Volunteer as a tester or otherwise more engaged user for the beta effort

Related issue is #342 (stub content landing pages).

**Comment by jessicaschilling** [comment]
@ericronne Do you want to design this one?

**Comment by ericronne** [comment]
For sure!

**Comment by jessicaschilling** [comment]
@ericronne Re the legacy site -- I think just a callout box like we've been doing with the ProtoSchool callouts would be just fine, though maybe a bright background or something - see below for reference. I can hand-code these with a link to the equivalent content on the beta site ... I might as well be the one to do it, since I know better than anyone where all that stuff lives. 😊 

Suggested text: The new IPFS Docs beta is live, with easier-to-find content, search, and more! (link)Visit this page on the beta >(/link)

If you're down with this, I don't think we need any design done for the legacy site at all, just the new one.

![image.png](https://images.zenhubusercontent.com/5ce5bf88b1698b1ceb4ce811/72016f23-efa4-470f-bd93-83ac73a235e8)

**Comment by ericronne** [comment]
Here's a more customized design for the legacy callout that might pay off in the number of clicks it could draw, and a simple design for the pointer linking back to the legacy site _from_ the beta site …

## Callout on legacy site
![beta-pointer-for-legacy-site](https://user-images.githubusercontent.com/9259185/68799046-1e46dc00-061d-11ea-866a-7654dff417b6.png)

## Callout on beta site
This could be integrated into a footer, eg …

![footer-with-legacy-pointer](https://user-images.githubusercontent.com/9259185/68799442-c9579580-061d-11ea-8741-ec08472b8ed5.png)

**Comment by jessicaschilling** [comment]
@ericronne This is awesome, thank you! 
I might be inclined on the beta site to be more explicit in the text: "View this page on legacy site"?
Do you mind putting the icon for the legacy site somewhere in the legacy site repo, so I can build the callouts when we're ready? Probably here: https://github.com/ipfs/docs/tree/master/static/assets

@cwaring -- What are your thoughts on the best way to build this? Since it's one-off work, I'm happy to pick up the job of manually annotating the legacy site pages; there doesn't seem much point in templating that. For the beta site, it seems useful to template the footer callout in some way, but we'd probably need a variable in the front matter of each content .md document to specify where the equivalent page on the legacy site is? Or can you think of a better way? Thanks!

**Comment by ericronne** [comment]
Cool. @cwaring lmk if this image doesn't properly render …
https://github.com/ipfs/docs/blob/master/static/assets/thumbnail-beta-laptop.svg

**Comment by jessicaschilling** [comment]
@cwaring The form for becoming a tester is here: https://docs.google.com/forms/d/1LVaD1B2uyW6Ff0jfU_iQ5mCeyQcHfyQO6BDD99XAgK0

**Comment by jessicaschilling** [comment]
Filed https://github.com/ipfs/ipfs-docs-v2/pull/35 -- once this is approved/merged we can call this issue done (pending merge of #384 the night before launch).

**Comment by jessicaschilling** [comment]
Closed via https://github.com/ipfs/ipfs-docs-v2/pull/41 😊 
Please note that we will still need to merge #384 immediately prior to beta launch to fully take care of this effort — BUT as it's included in the checklist for the comms plan (see https://github.com/ipfs/docs/issues/351#issue-506051033), it won't get lost.
