### ISSUE TITLE
Design/implement landing page for beta-site content stubs

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#342]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

The new nav structure being designed for the docs beta (see #313) will result in stub pages for which content doesn't yet exist. Until it does, create and implement a common landing page to convey ...
- The content that should be on this page doesn't exist yet, because the site is in beta
- We'd love to work with contributors who would be interested in helping create this content sooner rather than later
- If this missing content is crucial to you, we'd like to know
- If you'd like to be part of collaborating on/testing/creating this content, here's how to join us (likely a link to a Google form or similar contact mechanism)

**Comment by ericronne** [comment]
I'll start wiring this up. Additionally, we _might_ be able to populate some of these pages with very-rough "starter content" — or at least simple "Click at Own Risk, There Be Demons" — pointers to third-party material, where a user might be able to find help until the content is ready to launch. I've started a hackmd doc to organize information surrounding all `NEW` content which needs to be created.

[**NEW IPFS docs content to generate**](https://hackmd.io/FA0beZhrRUCEkBdPq-FBKA?view)

**Comment by jessicaschilling** [comment]
Thank you for linking to the related issues!

**Comment by cwaring** [comment]
A cute (animated) illustration will be the secret ingredient here. Diffuse disappointment with the delight of warm n' fuzzies™

**Comment by ericronne** [comment]
Here's a somewhat high-fi draft for discussion. Let's discuss the content here, first and foremost. This doesn't represent the design,  but i'm curious to hear feedback on the illustration. Time permitting, it would be fun to animate it.

![no-content-here-page](https://user-images.githubusercontent.com/9259185/66677783-094ae780-ec30-11e9-8ba7-51a9599269d7.png)

**Comment by jessicaschilling** [comment]
I love this so much 😄 
A few thoughts?
- Under "Other resources", I believe it's "that" rather than "which" (since not preceded by comma)
- Under "Help us write this page", we may want to lead with something that's more explicitly community-powered: "Community contributors are invaluable to making IPFS docs great!" rather than "work with" language? We may also want to be more specific at the end: "... visit this page's GitHub issue and comment with how you'd like to get involved."
- Maybe "Be a docs beta tester" instead of "Be a tester"?
- In the "be a tester" content, the link can go to [this form](https://docs.google.com/forms/d/1LVaD1B2uyW6Ff0jfU_iQ5mCeyQcHfyQO6BDD99XAgK0/) with the text "Sign up now"

More generic question and request:
- I believe all the content here will need to be manually generated (progress "subway map" imagery, related resources, etc). Are we OK to manually support this during the transition period? (My inclination is yes, since it adds a lot of value.)
- Re animation ... using SVG animation to move the bubbles under the pencil-ship around wouldn't be too tough. Also subtle enough to be charming without annoying.
- Would you be amenable to making the pencil-ship pilot a little more gender-neutral?

**Comment by ericronne** [comment]
Requests sound 👌to me … ☑️
- No specific gender was intended, but made them more masculine.
- The paper animation would be the tricky part. Not sure if those make sense when the rocket is in space, but we can pick up the ani Q later

![no-content-here-page](https://user-images.githubusercontent.com/9259185/66786749-289f7a00-eea7-11e9-90bb-3a3237182677.png)

**Comment by jessicaschilling** [comment]
@ericronne Thanks!

**Comment by jessicaschilling** [comment]
We had some input on this page as part of our IPFS Colorado user testing (see #355) and @ericronne is making some minor edits. 😊

**Comment by ericronne** [comment]
Here's an update with rearrangements and minor copy edits. (Reminder: this doesn't reflect final page design.) **[Here's the illustration](https://drive.google.com/open?id=1McGEy7dw5Xr1G5B4gw4zrdb07J93c6U8)**. Animation would be great, but for now, i think it would be more useful to prioritize other issues.

![no-content-here-page](https://user-images.githubusercontent.com/9259185/67215979-09917280-f3e8-11e9-8e59-3831883566cf.png)

**Comment by jessicaschilling** [comment]
Awesome! Going to move this one into "blocked" at the moment until we're able to actually develop on it.

**Comment by cwaring** [comment]
Posting this here for implementation reference. I'm building this feature with the following priority for each component based on our discussions from last week.

![67215979-09917280-f3e8-11e9-8e59-3831883566cf](https://user-images.githubusercontent.com/106938/68148024-21faa480-ff33-11e9-8b05-ae73c371f519.png)

**Comment by cwaring** [comment]
@ericronne could you please upload a src file for the progress bar so I can generate necessary vectors? Thanks!

**Comment by ericronne** [comment]
**[Timeline sketch file](https://drive.google.com/open?id=1SDjE0kQQ79c_9viC4y_-rS-WC5FcxDkL)** is on the drive, @cwaring.

![timeline](https://user-images.githubusercontent.com/9259185/68157493-5c544980-ff13-11e9-89f3-0db2c7be4b3e.png)

Colors will change to match the styling i'm experimenting with right now.

**Comment by jessicaschilling** [comment]
Update: @cwaring is implementing, but needs related items for each stub from @johnnymatthews and @jessicaschilling. These should be stored in front matter -- @cwaring, can you think about pinning the format down exactly? Something like ...

related_items:
     "ProtoSchool video tutorial on a thing": https://foo.bar
     "Another link title": https://link.here

**Comment by jessicaschilling** [comment]
@johnnymatthews - I've started a Google sheet here where we can divide and conquer on related items for content stubs: https://docs.google.com/spreadsheets/d/11O0tW3JpSsTsh0zn2wenirVbCN5azNZnjxSJe7pLSGo/edit?usp=sharing

**Comment by johnnymatthews** [comment]
Just ran through that sheet. Nothing is _glaringly wrong_ from my perspective, you know the content better than I do at the point. One thing we should do is mark external links with an external-links-icon.

**Comment by jessicaschilling** [comment]
@johnnymatthews I believe those external links should all auto-add the external-links icon because VuePress witchery, but @cwaring can confirm?

**Comment by ericronne** [comment]
@cwaring take with a salt grain if you've already crafted one of your characteristically brilliant solutions, but here's some visual food for thought and discussion among all. For the sake of easy implementation — and Occam's Razor-izing things — I've removed the status bar in favor of a simple text invite to follow the progress on github. …

![no-content-here-page-beta-launch](https://user-images.githubusercontent.com/9259185/69749242-afcf4700-110f-11ea-920c-02ec5627d91d.png)

Personally leaning toward the text-only approach ☝️ for the alt-resources list

**Comment by cwaring** [comment]
@ericronne thank you, this is great and very similar to what I had in mind :). I'm implementing the visual layout now and after experimenting with the voting options I've settled on a way to merge the functionality with the "was this helpful" widget.

**Comment by johnnymatthews** [comment]
> @ericronne 
> Personally leaning toward the text-only approach ☝️ for the alt-resources list.

Yeah me to. Not a fan of a bunch of icons in the copy.

**Comment by cwaring** [comment]
With ipfs/ipfs-docs-v2/pull/28 merged has everything been captured to close/complete this issue?

💁‍♀️[Live preview url for your convenience](https://docs-beta.ipfs.io/essentials/bitswap/).

**Comment by ericronne** [comment]
:shipit: 🚀

**Comment by jessicaschilling** [comment]
Re-opening, because I need to actually implement the content for those landing page stubs.

**Comment by jessicaschilling** [comment]
Also, two other quick modifications from our sync call - @cwaring, are you still OK to implement these?
- Remove "edit on GitHub" footer content from these pages only
- Links for "check status" and "help with this page" (both the same destination, and driven from front matter) need to be a URL rather than a GitHub issue number, because they may refer to issues in other repos

**Comment by jessicaschilling** [comment]
Stub content is added in https://github.com/ipfs/ipfs-docs-v2/pull/29 ... @cwaring, can you please take a quick glance?

**Comment by jessicaschilling** [comment]
Closing this issue via https://github.com/ipfs/ipfs-docs-v2/pull/41 😊
