### ISSUE TITLE
Port existing docs content to beta-site repo

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#345]
**_This issue is part of [Epic 1A: Launch docs beta](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++epic+in%3Atitle)._**

Port content from existing docs site repo to beta-site repo, adjusting or adding front matter and other metadata as necessary.

**Comment by ericronne** [comment]
**First we'll need a template …**
- [ ] Create a set of markdown templates for content, which maps to new IA (#273) @cwaring 

**Then we can portage the content 🛶…**
- [ ] Populate templates with all current docs content refer  @ericronne / @jessicaschilling
  - [ ] What is IPFS?
  - [ ] How IPFS Works
  - [ ] Content-addressed file storage
  - [ ] Content addressing and CIDs
  - [ ] Cryptographic hashing
  - [ ] Persistence (pinning)
  - [ ] Merkle-DAGs
  - [ ] IPNS
  - [ ] libp2p
  - [ ] Mutable File System (MFS)
  - [ ] UnixFS
  - [ ] IPFS Gateway
  - [ ] DNSLink
  - [ ] Configure a node
  - [ ] Modify the peers list
  - [ ] Customize an ipfs repo (js-ipfs)⬈
  - [ ] Spawn a node and add a file to IPFS (js-ipfs)⬈
  - [ ] Deal with blocks
  - [ ] Pin files
  - [ ] Troubleshoot file transfers ⬈
  - [ ] Snapshots
  - [ ] Host a Git-style repo
  - [ ] Store and play videos
  - [ ] Resolve through IPLD graphs (js-ipfs) ⬈
  - [ ] Replicate large datasets ⬈
  - [ ] Observing peers
  - [ ] Circuit relay (js-ipfs) ⬈
  - [ ] Customize libp2p bundles (js-ipfs) ⬈
  - [ ] Host a website on IPFS
  - [ ] Explore the Ethereum blockchain with IPFS (js-ipfs) ⬈
  - [ ] Making Your Own IPFS Service (basic egs)
  - [ ] Developing Apps with the IPFS API ⬈
  - [ ] Solving distributed networking problems with libp2p ⬈
  - [ ] Addressing in browsers ⬈
  - [ ] Build a tiny browser app to exchange files between nodes ⬈
  - [ ] Build an application with IPFS PubSub Room  📹 ⬈
  - [ ] Build a collaborative editing application using CRDT  📹 ⬈
  - [ ] Stream video using ReadableStreams ⬈
  - [ ] Browserify ⬈
  - [ ] Parcel.js ⬈
  - [ ] Vue ⬈
  - [ ] WebPack ⬈
  - [ ] With a <script> tag ⬈
  - [ ] Electron ⬈
  - [ ] The Mutable File System in the browser (js-ipfs) ⬈
  - [ ] Using streams to add directories to ipfs in the browser (js-ipfs) ⬈
  - [ ] HTTP API dictionary (this may need to be separated by go and js)
  - [ ] Working with go-IPFS
  - [ ] api dictionary
  - [ ] core options API dictionary
  - [ ] coreiface API dictionary
  - [ ] core API dictionary
  - [ ] Working with IPFS in JS
  - [ ] JS core API dictionary ⬈
  - [ ] js-ipfs-api dictionary ⬈
  - [ ] CLI commands (this may need to be separated by go and js)
  - [ ] Forums ⬈
  - [ ] IRC
  - [ ] Community calls (& cal)
  - [ ] Meetups
  - [ ] ProtoSchool chapters
  - [ ] Community projects: Awesome IPFS ⬈
  - [ ] Contribute to IPFS
  - [ ] Code of conduct ⬈
  - [ ] Project & roadmap
  - [ ] IPFS specifications ⬈
  - [ ] Roadmap ⬈
  - [ ] IPFS team planning/management repo ⬈

**Comment by jessicaschilling** [comment]
- Migrated existing content
- Rearranged and reformatted as necessary to fit new IA
- Fixed all relative links
- Cleaned up a lot of miscellaneous typos, formatting issues, outdated links that I found along the way.

The beta site should be ready for a close-read audit now. Closing this issue!

**Comment by cwaring** [comment]
Superb milestone! Thanks for all you help getting this migrated 🙌💯
