### ISSUE TITLE
Content Enhancement: Import Implementation Status Page from ipfs/ipfs as Part of Build Process

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/docs#35]
As suggested in https://discuss.ipfs.io/t/libp2p-status-of-go-version-vs-js-version let's make a features matrix for the go and js (and possibly other) implementations of IPFS, libp2p, etc. I'll take lead on making this happen.

This will also give us the impetus to provide a clearer representation of how all the libraries fit together.

cc @whyrusleeping @diasdavid @mishmosh

**Comment by jomarip** [comment]
Awesome. I look forward to this! Just jumping in to things today, and anything conceptual and visual would be of significant help

**Comment by MichaelMure** [comment]
Also, as someone that implement a project on top of IPFS, it would be very helpful to track the progress (when can I switch to js-ipfs instead of spawning a go daemon ?). Data mining the github issues is instructive but ... I'd like to know what is considered stable, experimental, planned for short or long term.

**Comment by magik6k** [comment]
There is now https://github.com/ipfs/ipfs/blob/master/IMPLEMENTATION_STATUS.md

**Comment by lgierth** [comment]
> There is now https://github.com/ipfs/ipfs/blob/master/IMPLEMENTATION_STATUS.md

Great -- we should pull this into the docs page as part of the build, similar to how we pull in package docs.

**Comment by Mr0grog** [comment]
This should probably be part of the `make` scripts, similar to how we pull in and build API docs for `go-ipfs`: https://github.com/ipfs/docs/blob/bef3dfa40523d1a9dc9018cf5047bf5767f9fa95/Makefile#L47-L54

**Comment by jessicaschilling** [comment]
Closing this, since it's being addressed under #253, but making a note there to examine this issue's conversation for completeness.
