### ISSUE TITLE
[DOCS ISSUE] Page: DNSLink

### ISSUE THREAD

**Issue by dreamski21** [ipfs/docs#365]
**URL of the page in question:**
https://docs.ipfs.io/guides/concepts/dnslink/

**What's wrong with this page?**
The given example is outdated: `ipfs.io`'s TXT records don't contain a "dnslink=/ipfs/\*" value, but points to yet another domain: `website.ipfs.io` which doesn't have any TXT record. I ended up checking `_dnslink.website.ipfs.io` as mentioned in the "Publishing via a Subdomain" section and found what expected.

![screenshot-dag](https://user-images.githubusercontent.com/32184973/67874181-dd3acc00-fb34-11e9-8695-97bb26beffef.png)

**What would you like to have changed/amended/fixed in order to make things right?**
Change the example to use a domain that has a *direct* mapping between TXT and IPFS, or, if possible, move _dnslink.website.ipfs.io's content to website.ipfs.io.

**Would you be interested in helping fix this page?**
Yes, but I'm not sure what to do.

**Is there any other feedback you'd like to share about IPFS docs?**
No.

**Comment by jessicaschilling** [comment]
@daviddias -- Is this something we may be able to enlist your help on? @dreamski21 is correct -- none of our canonical examples (e.g. the ones in http://dnslink.io/#known-users ) are mapping correctly any more. Not sure what the best resolution here is. Thank you!

**Comment by daviddias** [comment]
@jessicaschilling is on the Infra/Bifrost team alley :)

**Comment by jessicaschilling** [comment]
@olizilla -- Is this something that your Bifrost folks can help address? @daviddias is blocked on having a look for a while. Thank you!

**Comment by olizilla** [comment]
We consistently use an _dnslink.<example.org> subdomain for publishing our dnslink txt records to. 

Perhaps we should just restructure this doc to explain and recommend using a subdomain first, and then finish with a footnote that explains that you can also publish the txt record to the exact domain, if you so wish.

**Comment by jessicaschilling** [comment]
@olizilla @dreamski21 -- see https://github.com/ipfs/docs/pull/369 for PR to address this. Oli, I've added you as a reviewer on the PR, if you don't mind. Thank you!

**Comment by jessicaschilling** [comment]
Closed via #369. Thanks, all!
