### ISSUE TITLE
[DOCS ISSUE] Link to forum is broken

### ISSUE THREAD

**Issue by timthelion** [ipfs/docs#371]
**URL of the page in question:**
https://docs.ipfs.io/community/

**What's wrong with this page?**
![ipfs](https://user-images.githubusercontent.com/1391608/68535157-9cf9fb80-0335-11ea-98b1-4a74adb6b53c.png)

**Comment by jessicaschilling** [comment]
Thanks for finding this, @timthelion! Fixed.
