### ISSUE TITLE
Design a glossary of IPFS-related terms

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#372]
Here are some design options for a glossary feature, for discussion. 

## A - Simple pop-up

![glossary-A](https://user-images.githubusercontent.com/9259185/68617407-df821c00-048c-11ea-825e-6feed7271623.png)

## B - Sliding panel

![glossary-B](https://user-images.githubusercontent.com/9259185/68617418-e315a300-048c-11ea-8e67-48c39f772340.png)

### Toggle visibility with nav button …
![glossary-B-button-action](https://user-images.githubusercontent.com/9259185/68617445-f0329200-048c-11ea-9713-5491ddc444b0.png)

### Or tab
![glossary-tab](https://user-images.githubusercontent.com/9259185/68617540-1d7f4000-048d-11ea-8a09-5ff93f2e722a.png)

## Related issues
[Define and implement tagging taxonomy for beta-site content](https://github.com/ipfs/docs/issues/347)
[Create concepts dictionary (meta-concept-doc) aka glossary](https://github.com/ipfs/docs/issues/56)

**Comment by ericronne** [comment]
My design is based on **[this code](https://github.com/18F/glossary)** by 18F.

[Live example](https://web.archive.org/web/20170406100258/https://useiti.doi.gov/)

**Comment by jessicaschilling** [comment]
@ericronne My personal favorite might just be the pop-ups (particularly considering mobile), but kind of want to leave this choice in @cwaring's hands vis-a-vis ease of implementation. They've all got their strengths, so I might be inclined to go with the simplest one to build.

**Comment by ericronne** [comment]
The 18f code is mobile friendly out of the box (not sure about vue-friendliness). +1 to @cwaring's call,  🙌 
![foLaM0rrNB](https://user-images.githubusercontent.com/9259185/68700900-554cbd00-054b-11ea-808b-85b99b7ea2bf.gif)

**Comment by terichadbourne** [comment]
If this is being built in VuePress, any chance it can be built to be compatible with Vue as well so it can be used on ProtoSchool? See this open issue: https://github.com/ProtoSchool/protoschool.github.io/issues/99

**Comment by cwaring** [comment]
I do love this idea but it could be an entire product by itself. As @terichadbourne pointed out the real value might come from a plugin that could work on any of our websites/apps. If we are considering i18n too it does start to get quite complex so we'll have to draft out the scope or MVP for testing on the docs site first.

**Comment by ericronne** [comment]
I would exclude the glossary from the beta launch and bump it to next q as an enhancement.

**Comment by jessicaschilling** [comment]
+1 - I think that was actually always the idea.

**Comment by jessicaschilling** [comment]
Closing this issue in favor of already-existing #56, and linking in #56 to this discussion so we can implement visuals when we start work on this project.
