### ISSUE TITLE
Design and implement "Refresh for updated content" feature

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#373]
Vuepress shows a sticky lower-right-corner refresh prompt when local content is outdated. Here's a non-sticky design that's less obtrusive, but might be sufficiently obvious. If this seems reasonable and easy to implement, let's test.

- [x] Initial design
- [ ] Review
- [ ] Update design
- [ ] Test with users
- [ ] Update design if necc
- [ ] Implement

## Desktop
![refresh.png](https://images.zenhubusercontent.com/555b449c4f7a08fbb7f2de17/1ce30981-2f7c-4ce7-aafa-f9c4e3132aed)

## Mobile
![refresh-mobile.png](https://images.zenhubusercontent.com/555b449c4f7a08fbb7f2de17/28238051-2eaf-4287-a507-272bfba3069f)

@jessicaschilling @cwaring

**Comment by jessicaschilling** [comment]
I dig! Should we make the text more explicit?
"New content available! (link)Refresh(/link)"

**Comment by cwaring** [comment]
Nice. I feel that the desktop variant could get a little lost but we might be able to do something with animations to make it more visible. Work has been started in ipfs/ipfs-docs-v2/pull/20, currently there are some limitations that we should discuss in more detail over a call to ensure we get the interaction correct.

**Comment by jessicaschilling** [comment]
Closing, since this is outside the scope of IPFS-hosted docs at present. We can reopen later if feasible. Thanks!
