### ISSUE TITLE
[DOCS ISSUE] Page: Content Identifiers (CIDs)

### ISSUE THREAD

**Issue by fulldecent** [ipfs/docs#377]
The IPFS documentation on CID should explain which CID types are supported by IPFS clients.

Documentation should answer these questions:
* Is every file just SHA256 hashed and then CID is a way of expressing that fact?

And maybe also
* Who decides when new hash types will be accepted?
* When new hash formats are accepted will clients disallow uploading/storing files of the old hash format?

**Comment by jessicaschilling** [comment]
@johnnymatthews -- are you able to take this on next week? Thank you!

**Comment by terichadbourne** [comment]
The "Anatomy of a CID" section of Core Course A from IPFS Camp might be helpful for some of this. https://www.youtube.com/watch?v=Z5zNPwMDYGg

**Comment by johnnymatthews** [comment]
Hey @fulldecent. You've brought up a good point, mainly the policy/process for deciding new hashing types. I've made a [thread to discuss it over on the IPFS forum](https://discuss.ipfs.io/t/who-decides-what-hashing-algorithms-ipfs-allows/6742).

**Comment by fulldecent** [comment]
Thank you. PR added here https://github.com/ipfs/docs/pull/395

**Comment by jessicaschilling** [comment]
Closed via #395 - thanks!
