### ISSUE TITLE
[beta design nit] navigation scrolling is a bit funky

### ISSUE THREAD

**Issue by Stebalien** [ipfs/docs#383]
Scrolling the main page leaves the navigation where it is but scrolls up the header. I'd expect one of:

* The header to be sticky.
* The navigation to scroll up.
* The navigation to scroll up with the header until the header is off the page, then stick to the top.
* The navigation to continue to the top (and "own" the logo).

![out](https://user-images.githubusercontent.com/310393/69564563-d73fdb80-0f78-11ea-9d1e-0bcaf43caa59.gif)

**Comment by jessicaschilling** [comment]
@Stebalien, thanks for bringing this up -- we've had a round of discussions among the team and haven't reached a consensus yet about best solution (ha!) but please be assured it's on the radar. Thanks for capturing it in its own issue! We may not nail this for initial beta release but it's now in the queue ...

**Comment by Stebalien** [comment]
Thanks! Yeah, it's definitely a low-priority polish issue.

**Comment by jessicaschilling** [comment]
This has been fixed in the last round of theme edits 😊
