### ISSUE TITLE
Barebones CSS edits for beta launch

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#385]
Distill the essentials from #329 for visual changes we feel are absolutely necessary for December launch.

@ericronne to identify changes required
@cwaring to implement them

UPDATE: Bug found by @jimpick:
"Make the the input field in the search box is a minimum of 16px ... otherwise iPhones will automatically zoom the viewport which wrecks the responsive layout - it looks like it's currently font-size: 0.9rem"

**Comment by jessicaschilling** [comment]
UPDATE: Bug found by @jimpick:
"Make the the input field in the search box is a minimum of 16px ... otherwise iPhones will automatically zoom the viewport which wrecks the responsive layout - it looks like it's currently font-size: 0.9rem"

@cwaring and @ericronne, is it possible to get a fix for this included in this round of edits?

**Comment by ericronne** [comment]
☝️ requires the chops of @cwaring

**Comment by jessicaschilling** [comment]
🚢 🚢🚢
It's so beautiful I could cry 😊 . 😢
