### ISSUE TITLE
[NEW CONTENT] [BOUNTY] High-level doc of usage ideas and examples

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#387]
**This issue is one of the prioritized recommendations in the [Q1 2020 IPFS Ecosystem Audit](https://github.com/ipfs/community/tree/master/ecosystem-audit) for execution in Q2/Q3 2020. Tagging it with `$auditrecommendation` means it's searchable! See [all tagged issues](https://github.com/ipfs/docs/issues?q=is%3Aissue+%22%24auditrecommendation%22+) in this repo.**

## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
As identified by Q3/Q4 2019 user testing, create a high-level document offering ideas for use cases of IPFS, as well as active/prominent/standout examples of these use cases in action, when they exist.

It may also be useful to provide direction to the best repos to look at for someone considering a common use case. @eshon provides Twitter Open Source's projects page as an example for how to potentially present this info: https://twitter.github.io/projects.html

The target audience for this may not be the hardcore or dweb-experienced developer: it may be more useful to keep in mind the technically proficient, but not necessarily in-the-weeds active, technologist or engineering manager who needs to understand where IPFS can help them achieve their existing goals and where it might fit into their overall tech stack. To this end, it'll be helpful to use the [IPFS goal-based personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf) as a starting point.

## Deliverable
A concise, high-level high-level document offering ideas for use cases of IPFS, as well as active/prominent/standout examples of these use cases in action, when they exist

**Content should take the form of a Markdown document, supplemented by diagrams or other appropriate helper content as embedded images.** File locations should be as follows:
- MD content should live here (lease make a PR against the existing placeholder document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/usage-ideas-examples.md
- Images can live in the MD content's parent directory; we'll move them before final merge
- For videos, just post temporarily on the platform of your choice, and we'll sort out on a case-by-case basis

## Guidelines
- Please use the [IPFS Docs Contributor Guidelines](https://github.com/ipfs/docs/blob/master/CONTRIBUTING.md ) as your north star — **adherence to these guidelines are crucial when it comes to awarding potential bounty**!
- Also, please keep in mind our [core user personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf). If a piece of content serves one or more personae in particular, make sure it checks out with that persona's attributes.

**Comment by vasa-develop** [comment]
> MD content should live here (lease make a PR against the existing placeholder document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/essentials/usage-ideas-examples.md

Seems like this link is broken.

I think I can pick this one up.

**Comment by jessicaschilling** [comment]
@vasa-develop -- just fixed the link above, but its: https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/usage-ideas-examples.md

**Comment by vasa-develop** [comment]
@jessicaschilling who should I contact you to get feedback on my drafts of this task?

**Comment by jessicaschilling** [comment]
@vasa-develop That’d be @johnnymatthews 😊

**Comment by johnnymatthews** [comment]
Hi @vasa-develop, sorry I've just gotten around to this. The best way to post your drafts is to create a fork of `ipfs/ipfs-docs-v2` and share that fork here. Then I'll be able to add comments directly in your fork. Once everything's good to go, you can make a PR into `ipfs/ipfs-docs-v2` and we can get things merged.

**Comment by jessicaschilling** [comment]
@vasa-develop -- what's the status on this? Would like to open up this bounty issue to other contributors if you're no longer interested. Thank you!

**Comment by bertrandfalguiere** [comment]
I can take this on if @vasa-develop has no time available for the time being.

**Comment by jessicaschilling** [comment]
@vasa-develop -- please let us know by Wednesday 5 Feb if you're available to work this. If not or we don't hear from you, we'll re-assign to @bertrandfalguiere so he can get to work. Thanks both!

**Comment by jessicaschilling** [comment]
Un-assigning @vasa-develop in absence of his confirmation he's still available to work on this issue. @bertrandfalguiere, assigning if you if you'd still like to work on this. Please confirm.

**Comment by bertrandfalguiere** [comment]
I'm on it. Thanks for the assignation.

**Comment by vasa-develop** [comment]
Hey! 
Sorry for not updating the progress here. 
Somehow, I didn't get notifications.
@bertrandfalguiere I can send you the material that I worked on. Maybe you can use that.

**Comment by bertrandfalguiere** [comment]
@vasa-develop Yes, why not, that's kind :)

**Comment by johnnymatthews** [comment]
Hi @bertrandfalguiere, how's things going with this? If you need any extra support, let us know here!

**Comment by johnnymatthews** [comment]
Re-opening this issue. If you're still working on things @bertrandfalguiere, I'll re-assign it to you.

**Comment by bertrandfalguiere** [comment]
Yeah, sorry, I got lost in the tens and tens of uses cases. 😬 Expect a first PR tomorrow or Saturday.

**Comment by johnnymatthews** [comment]
Ok cool, thanks for the update.
