### ISSUE TITLE
[NEW CONTENT] [BOUNTY] Quick overview of libp2p with deep linking to its docs

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#388]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
A quick, high-level explainer of libp2p that doesn't seek to replace any of the excellent [libp2p docs](https://docs.libp2p.io/), but rather provides topically specific entry points to key content in those docs for folks who want to dig deeper. In other words, we'd like a 10k-foot overview of libp2p on the IPFS docs for those who don't know what it is yet -- but we don't want to simply link the reader to libp2p docs without any initial context.

## Deliverable
A concise, high-level description of this IPFS concept. It should answer the following, **supplemented whenever possible by diagrams, videos and/or code examples**:

- **What** is this?
- How does it **relate** to the rest of IPFS?
- What are some **generic use cases** for this — how might it meet a need in someone's project/goal?
- How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not necessarily* use it based on your use case or the current state of the tech.)
- **Where** do you go to learn more?
- What is the **current state** of this concept or technology?

**Content should take the form of a Markdown document, supplemented by diagrams as embedded images.** File locations should be as follows:
- MD content should live here (please make a PR against the existing placeholder document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/libp2p.md
- Images can live in the MD content's parent directory; we'll move them before final merge
- For videos, just post temporarily on the platform of your choice, and we'll sort out on a case-by-case basis

## Guidelines
- Please use the [IPFS Docs Contributor Guidelines](https://github.com/ipfs/docs/blob/master/CONTRIBUTING.md ) as your north star — **adherence to these guidelines are crucial when it comes to awarding potential bounty**!
- Also, please keep in mind our [core user personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf). If a piece of content serves one or more personae in particular, make sure it checks out with that persona's attributes.

**Comment by vasa-develop** [comment]
@jesseclay 

> MD content should live here (please make a PR against the existing placeholder document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/essentials/libp2p.md

The link to the placeholder link seems to be broken.

> How can (or should?) you use it? (Note: sometimes the answer is that you should understand it, but not necessarily use it based on your use case or the current state of the tech.)

I didn't get this. Can you elaborate a bit on this point?

**Comment by jessicaschilling** [comment]
@vasa-develop - thanks for catching that broken link, it should be https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/libp2p.md 

As for the second bit: This really means just to remember that a variety of levels of expertise will be reading this piece of documentation. Some folks just want to know what libp2p is at the most basic level; others want to know how it might be useful to them without having to dig too deep into dev-specific details; others want those deep details. In the case of the libp2p page on the IPFS docs, since there's already an entire libp2p documentation site out there on libp2p.io, we want to give them a high-level explainer of libp2p, but if they want to go deeper, give them good, meaty, contextual deep links into specific useful areas in the libp2p docs.

**Comment by bertrandfalguiere** [comment]
If @vasa-develop doesn't take this on, I can do it.

**Comment by jessicaschilling** [comment]
@bertrandfalguiere -- any other open issues for new content that catch your fancy? You can see them all here: https://github.com/ipfs/docs/labels/Category%3A%20Content

**Comment by bertrandfalguiere** [comment]
I have a good understanding of the concepts and how things work together but haven't dug into the code. So the only issues I can work on are this one, the [Glossary](https://github.com/ipfs/docs/issues/56) and the usage [examples](https://github.com/ipfs/docs/issues/387).
I wish to work on any of them.

**Comment by jessicaschilling** [comment]
@bertrandfalguiere -- This is a bit off-topic, but might you be interested in this issue? https://github.com/ipfs/website/issues/352
(cc @johnnymatthews)

**Comment by jessicaschilling** [comment]
@edgo914 - looks like you’ve claimed this. Assigning.

**Comment by edgo914** [comment]
@jessicaschilling thanks, I'm on it

**Comment by johnnymatthews** [comment]
Closed through [PR 122](https://github.com/ipfs/ipfs-docs-v2/pull/122).

**Comment by momack2** [comment]
@johnnymatthews / @jessicaschilling can you ensure we pay this out and move to the "paid" column of the [bounty board](https://github.com/ipfs/devgrants/projects/1)?
