### ISSUE TITLE
Design and create video content to reflect written content.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#390]
**Note: This issue was opened as a result of the November 2019 close-reading audit captured in #326.**

Right now the docs are pretty much just a wall of text, with a few images thrown in here and there. What IPFS needs is something like the [Laravel Docs](https://laravel.com/). They have their [standard documentation](https://laravel.com/docs/6.x), which is great. But they also have [Laracasts](https://laracasts.com/), a bunch of video courses that explore the topics discussed in the documentation, and _show_ the user how to do stuff.

Let's use this issue to pick a handful of concepts and tutorials to build a video series around. This should probably wait until after we implement the more structured hierarchy for the docs. Once we have the videos identified, each one should be tracked and managed in its own issue.

**Comment by jessicaschilling** [comment]
Proposing that we close this issue (please feel free to re-open if you disagree!) in favor of selecting specific items [labeled for new content or content enhancement](https://github.com/ipfs/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22OKR+1%3A+Content+improvement%22), and moving discussion on integrating diagrams and/or video into those items' issues. Note as well that many of those issues also include some tentative diagrammatic content generated during poster sessions from the 2018 Berlin developer conference -- so some may have some degree of the work already taken care of. 😊
