### ISSUE TITLE
Create detailed and interesting diagrams to supplement the written content.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#391]
**Note: This issue was opened as a result of the November 2019 close-reading audit captured in #326.**

The vast majority of content in the IPFS documentation is just text. This is an issue for visual learners. Having a few diagrams thrown in there to explain more complex and technical concepts can help visual learners understand what's going on. When designing the new hierarchy we should keep this issue in mind and plan out illustrations and diagrams to go along with the written content.

Potential approaches:
- Supplement existing content items (which ones?) with diagrams, if we can identify items that would substantially benefit from them
- Specify including diagrams in new content items for content items that would benefit (so, probably all content items)

Let's use this issue as an umbrella for discussing the best approach, as well as identifying specific content items for which we want to include content items. Once we have those pinned down, each content item should be tracked and managed in its own issue.

**Comment by terichadbourne** [comment]
Just flagging that some of the visuals we create for docs will also prove useful in ProtoSchool or vice versa. For example, I think there were some useful graphics created for core course slide decks at IPFS Camp that we could steal for both places. (See issue reviewing camp content for usefulness, still WIP: https://github.com/ProtoSchool/protoschool.github.io/issues/261)

**Comment by johnnymatthews** [comment]
I completely agree. There's going to be a bunch of images/diagrams/code-blocks/examples/jokes we can use across both platforms. I'll try to loop you in @terichadbourne when we're creating something that could be useful for ProtoSchool.

**Comment by jessicaschilling** [comment]
Proposing that we close this issue (please feel free to re-open if you disagree!) in favor of selecting specific items [labeled for new content or content enhancement](https://github.com/ipfs/docs/issues?q=is%3Aissue+is%3Aopen+label%3A%22OKR+1%3A+Content+improvement%22), and moving discussion on integrating diagrams and/or video into those items' issues. Note as well that many of those issues also include some tentative diagrammatic content generated during poster sessions from the 2018 Berlin developer conference -- so some may have some degree of the work already taken care of. 😊
