### ISSUE TITLE
create default social media card graphics

### ISSUE THREAD

**Issue by cwaring** [ipfs/docs#396]
TLDR; I'd recommend we use **1200x630 as PNG**, each network will crop and recompress to suit.

Spec details:

"For Twitter, images must be a minimum dimension of 300x157 or maximum of 4096x4096 pixels and must be less than 5MB in size.

Facebook recommends images that are at least 1200 x 630 pixels for the best display on high-resolution devices. At the minimum, use images that are 600 x 315 pixels to display link page posts with larger images."

More info: https://iamturns.com/open-graph-image-size/

**Comment by jessicaschilling** [comment]
Related issue: #343 for the meta text in front matter.

**Comment by ericronne** [comment]
https://makeawebsitehub.com/social-media-image-sizes-cheat-sheet/

**Comment by jessicaschilling** [comment]
I needed to add a draft social sharing card so I could test the SEO optimization stuff in #343 -- the result is here: https://raw.githubusercontent.com/ipfs/ipfs-docs-v2/master/docs/.vuepress/public/images/social-card.png

@ericronne, I assume you'll want to change the actual visuals. Please, when you do, just keep the image dimensions, name etc. Thanks!

**Comment by jessicaschilling** [comment]
@ericronne FWIW, you can see how the existing one is cropped in Twitter as below.
![image](https://user-images.githubusercontent.com/1507828/70283714-6b7f1f00-177f-11ea-842e-dbdd8acbf023.png)

Facebook, on the other hand, doesn't crop:
![image](https://user-images.githubusercontent.com/1507828/70283732-7a65d180-177f-11ea-98eb-27a941044906.png)

I'd suggest something that plays well in both settings, if at all possible.

**Comment by jessicaschilling** [comment]
If you want to try the sharing tools, they're here:
https://developers.facebook.com/tools/debug/sharing/
https://cards-dev.twitter.com/validator

You'll need to use a deploy preview from https://github.com/ipfs/ipfs-docs-v2/pull/36 since it's not merged yet. This one should work: https://deploy-preview-36--ipfs-docs-v2.netlify.com/concepts/dht/

**Comment by ericronne** [comment]
Given the crazy range of potential cropping that sites will perform, simplest is probably best for now …
![image](https://user-images.githubusercontent.com/9259185/70326220-9c9c3580-17f9-11ea-8242-66e4453fb218.png)

**Comment by jessicaschilling** [comment]
Thank you! Closing this issue. 😊
