### ISSUE TITLE
[CONTENT IMPROVEMENT] Refactor docs homepage

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#398]
Augment the docs home page to include:
- A more complete welcome message including a very basic intro to IPFS, and click-through to the "what is IPFS" content that already exists

Content should be located here: https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/README.md

_Note: This issue was generated as a result of Nov 2019 internal user testing. Background can be found in the [summary](https://hackmd.io/gdRqxFZoRy-U-xB1DHitIA?view) (source: #315)._

**Comment by johnnymatthews** [comment]
A bunch of people mentioned that our homepage is pretty lack-luster at the moment. I've thrown this sketch together to suggest some things that we might do.

![Rough sketch on paper of a potential layout for the homepage.](https://user-images.githubusercontent.com/9611008/70538637-70055800-1b30-11ea-97a5-b2453e1752ef.jpg)

The main three sections I want to bring up here:

1. We're not wasting the only `h1` on the screen for _IPFS Documentation_. The user should know where they are. Let's tell the user what they can _do_ while they're on this page. _Educate yourself_ works pretty well here.
2. Let's give novice users something juicy to jump into straight away. If we're targeting web developers, let's show them something they're comfortable with: _Host a website on IPFS_. This way, we can slowly introduce DWeb concepts to them alongside stuff they already know.
3. The _Sample projects_ are there for slightly more advanced users who want to start hacking on stuff, but need a helping hand to get there.

The only section we won't be able to create right now is the _Sample projects_ part, but everything else can be drafted.

@ericronne, it'd be great to get your input on this at some point, probably after New Years'.

**Comment by johnnymatthews** [comment]
Here's some copy to go along with the homepage. Pasting here for history:

---

Educate Yourself
Whether you're a tiny startup or a massive company, you need to learn how to protect yourself from the dangers of a centralized internet. This website contains a bunch of articles and guides to help you, your company, and your product grow.

Host your website on IPFS
Protect your site from a single point of failure by uploading it to the IPFS network, and benefit from decentralized infrastructure. If you're new to IPFS, this is an excellent place to start learning how to build on the decentralized web.

Sample projects
Pick up one of these pre-built sample projects and get hacking! These self-contain packages have every you need to build something quickly while teaching yourself about IPFS.

Useful tools
Build your apps and services quicker with these tools built for IPFS.

Decentralized Web
Want to know more about the decentralized web and how it's changing the internet? These resources will give you a clearer understanding of the DWeb movement and how it's improving the world.

Community
IPFS has a bustling community of designers, developers, writers, and activists who are all helping to improve the project. You can join in by attending a meetup, helping out at a conference, or chatting online through IRC and the IPFS forum.

**Comment by jessicaschilling** [comment]
@johnnymatthews This is great! Are you comfortable building the page after you and @ericronne discuss? It’s a fairly simple layout, so would be awesome if we could avoid invoking the powers of @cwaring unless/until necessary.

**Comment by johnnymatthews** [comment]
Yeah sure, can't be too hard. Great ready for some conflicting inline styles and `!important` flags!

**Comment by cwaring** [comment]
@johnnymatthews 👀

**Comment by terichadbourne** [comment]
If we're going to use "host a website" as the example use case, let's be very clear to use an extremely static website as the example and in all labelling "host a STATIC website". There's too much ongoing confusion around support for modern web apps right now to venture into that territory and reinforce existing misconceptions about core strengths of IPFS.

**Comment by johnnymatthews** [comment]
Yeah good point @terichadbourne. Here's a very hacked-together preview of what things _could_ look like. The wording is likely going to change, but this gives us an idea of spacing and general _flow_.

![getting-started-homepage-hack](https://user-images.githubusercontent.com/9611008/70564050-7100ae80-1b5d-11ea-8958-773212c715e4.png)

**Comment by jessicaschilling** [comment]
This is awesome 😊 One thing you wouldn't have any reason to know, but ... we try to avoid using "upload" in favor of more generic words like "add", just because "upload" has a lot of centralized hosting connotations.

**Comment by johnnymatthews** [comment]
> "upload" has a lot of centralized hosting connotations

That's a good point, didn't think of that! I'll make a note to look out for that in future.

**Comment by lidel** [comment]
@johnnymatthews I really like the _Educate yourself_ approach, and starting with _Host a static website on IPFS_  is the right way to frame it right now :ok_hand: (thanks @terichadbourne!)

>  "upload" has a lot of centralized hosting connotations

Yes, "add" and "import" are much better choices (_import_ is what Filecoin uses)
FYSA in our browser extension we [switched from _upload_ to _import_](https://github.com/ipfs-shipyard/ipfs-companion/issues/817) in effort to remove "upload" from UIs across the  project.

**Comment by jessicaschilling** [comment]
Sounds like standardizing on “import” is the best move. 😊

**Comment by johnnymatthews** [comment]
This issue is being addressed in [`ipfs/ipfs-docs-v2:refactor-homepage`](https://github.com/ipfs/ipfs-docs-v2/tree/refactor-homepage).

**Comment by jessicaschilling** [comment]
Closed by https://github.com/ipfs/ipfs-docs-v2/pull/116.
