### ISSUE TITLE
Make expanded navigation subheads sticky?

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#399]
On the docs beta, should we make expanded navigation subheads sticky, so users always know what sections they are viewing?

This issue provides a space to discuss and possibly implement.

_Note: This issue was generated as a result of Nov 2019 internal user testing. Background can be found in the [summary](https://hackmd.io/gdRqxFZoRy-U-xB1DHitIA?view) (source: #315)._

**Comment by ericronne** [comment]
When we're able to implement in-page right nav, that should help resolve this issue for users.

**Comment by jessicaschilling** [comment]
Closing this, since adding the in-page nav is being discussed in #400.
