### ISSUE TITLE
Automate websites deployment

### ISSUE THREAD

**Issue by lgierth** [ipfs/docs#4]
So that the draft-to-production path is as short as possible.

**Comment by lgierth** [comment]
Status update:

- [x] Jenkins (ci.ipfs.team) builds each commit on any branch, and adds the resulting `public/` dir to ipfs: https://ci.ipfs.team/blue/organizations/jenkins/IPFS%2Fdocs/activity
- [ ] Jenkins reports hash/url to Github's commit status API, so that each commit links to https://ipfs.io/ipfs/hash as kind of a preview.
- [ ] Jenkins updates the dnslink record for docs.ipfs.io when the master branch is built.

**Comment by VictorBjelkholm** [comment]
This task is done but I have one concern about the structure of docs. The docs for other projects are being built when ipfs/docs is built, which means changes to for example js-ipfs won't automatically deploy new changes to the docs. Either we trigger ipfs/docs builds from ipfs/js-ipfs, or we find a way of linking docs and each project will build the docs by themselves. The latter also gives us the benefit of projects being able to build their docs locally, which might be useful in offline scenarios.
