### ISSUE TITLE
Prev/Next nav: Solve for off-site content

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#404]
In order to implement our previous/next footer navigation (#403), we must first remedy the problem of left-nav items which link directly to content on other websites. 

It's user-unfriendly for the left nav to have as many offsite links as it currently does anyway, so let's solve this problem.

**Comment by ericronne** [comment]
One solution would be to make a docs page for each of these links. That page would include brief info gleaned from the destination content, and of course, the link itself.

**Comment by jessicaschilling** [comment]
One thought - as we migrate a lot of go-ipfs and js-ipfs content out of their respective repos and onto the docs site, a TON of those external links are going to vanish.

**Comment by jessicaschilling** [comment]
Folding this back into #403 for ease of discussion; we can separate back into two separate issues if we feel it's helpful later.
