### ISSUE TITLE
Remove feature-request button from header

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#406]
Remove the link from the header, since [this pr](https://github.com/ipfs/ipfs-docs-v2/pull/35) shifts it to the callout box at the bottom of the page.

![image](https://user-images.githubusercontent.com/9259185/70483789-4ce69400-1aaf-11ea-956b-79bce0b6df49.png)

**Comment by jessicaschilling** [comment]
@cwaring, do you mind implementing this one? Thank you!

**Comment by jessicaschilling** [comment]
Closing this issue via https://github.com/ipfs/ipfs-docs-v2/pull/41 😊
