### ISSUE TITLE
Relabel "Help us improve this page on GitHub"

### ISSUE THREAD

**Issue by ericronne** [ipfs/docs#407]
This unit is being generated on the beta site via **[PR 35](https://github.com/ipfs/ipfs-docs-v2/pull/35)**:
![image](https://user-images.githubusercontent.com/9259185/70538245-63303680-1b27-11ea-8ff1-0607b724f7c4.png)

Looking at it in the context of the footer makes me wonder about "Help us improve this page on GitHub." That phrasing might lead some to think it's a link to make an issue. The above callout box covers that territory in a very user-friendly matter, so I think a more explicit (and shorter yay) label would be more effective: ```Edit this page on GitHub```

![image](https://user-images.githubusercontent.com/9259185/70538893-75f73b00-1b28-11ea-81c5-57a6fe1f5d93.png)

**Comment by ericronne** [comment]
"Assigning" to gather the group for discussion

**Comment by jessicaschilling** [comment]
@ericronne Fine by me. Make a PR for the change?

**Comment by terichadbourne** [comment]
I also prefer your new wording. 🏆

**Comment by cwaring** [comment]
👌 with me, your proposed copy is closer to the default text too.

It can be changed here: https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/.vuepress/config.js#L41

**Comment by cwaring** [comment]
Implementing this in https://github.com/ipfs/docs/issues/306
