### ISSUE TITLE
[DOCS ISSUE] Page: Configuring Your Node

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/docs#413]
**URL of the page in question:** https://docs.ipfs.io/guides/examples/config/

**What's wrong with this page?**

Should link to https://github.com/ipfs/go-ipfs/blob/master/docs/config.md and https://github.com/ipfs/go-ipfs/blob/master/docs/experimental-features.md (for go-ipfs).

In general needs revisiting to make a more in-depth review of current configuration options.

**Comment by johnnymatthews** [comment]
I've partially addressed this issue with in 7afd7f067cbaa3504da8d010b4a9b25d1aa5e793. I'm hesitant to include a link to experimental features directly into this page right now. It makes sense to let reader know these features exist, but this might not be the right place.

There's going to be a huge push in Q0 2020 to change, reformat, and generally update a lot of IPFS content. So this page will get revisited then.

**Comment by jessicaschilling** [comment]
@johnnymatthews Thanks for jumping on this! Can you please duplicate those edits in the beta site too? It’s a pain but only a temporary one 😊

**Comment by johnnymatthews** [comment]
> @johnnymatthews Thanks for jumping on this! Can you please duplicate those edits in the beta site too? It’s a pain but only a temporary one 😊

Will do! Thanks for the reminder.

**Comment by johnnymatthews** [comment]
Had to [make a PR](https://github.com/ipfs/ipfs-docs-v2/pull/51) because I don't have write access to that repo:
