### ISSUE TITLE
[CONTENT MIGRATION] Cool links don't break

### ISSUE THREAD

**Issue by lidel** [ipfs/docs#414]
_(apologies if this was already discussed, but don't want us to miss this)_

> What makes a cool URI?
> A cool URI is one which does not <del>change</del> break
>
> – https://www.w3.org/Provider/Style/URI

### Motivation

Various blog posts, docs, tutorials, posts on forums and StackOverflow link to our docs. There is a big value in that. Those HTTP links should continue to work and deliver user (and crawlers) to related content in docs-v2 where possible.

### Implementation

This is specific to `http://` transport on regular web, so we should handle this at Nginx level. The most popular paths should return HTTP 301 to content in the new website.

**Question:** Do we have analytics on docs-v1? Are we able to tell which pages are visited the most? I imagine we don't need to add rules for all pages, only a small set of the most popular ones.

**Comment by jessicaschilling** [comment]
@lidel - Yep, this is all covered in the deprecation plan here: https://hackmd.io/-JU3CcXgSgmcXWszyku2PA

Feel free to add to that document if you see anything missing. 

We do have metrics in the legacy site, and will be using those to prioritize redirects and if possible reaching out to common referrers. Thanks!

**Comment by lidel** [comment]
Fantastic! Added some comments / references there.
