### ISSUE TITLE
Scroll position not always reset to top of page when changing section

### ISSUE THREAD

**Issue by olizilla** [ipfs/docs#418]
To recreate:
- in Firefox 71 (Chrome does seem to reset the scroll position)
- go to: https://docs-beta.ipfs.io
- scroll to bottom
- click on **Concepts** in the sidebar nav
- I see the page still scrolled to the bottom, so I see _Still don't see what your looking for_ rather than the concepts intro which is scolled out of view above.

<img width="1392" alt="Screenshot 2020-01-07 at 13 42 06" src="https://user-images.githubusercontent.com/58871/71899437-a2b46780-3153-11ea-8153-a265909ec391.png">

**Comment by cwaring** [comment]
This appears to be an issue with how FireFox handles the smooth scrolling. I'll add a hook locally and then patch upstream

**Comment by johnnymatthews** [comment]
Looks like it's fixed on my end! Nice one @cwaring.
