### ISSUE TITLE
Enhancement: Give user feedback when there are no search results

### ISSUE THREAD

**Issue by terichadbourne** [ipfs/docs#419]
**THIS FEEDBACK APPLIES TO THE BETA SITE ONLY:** 

When using a search feature, I'm accustomed to hitting return to tell the search gods that I'm done typing. The search feature on the new site seems to auto-load a list of options as you type, so two potential issues here: 

- If I type something that exists as a search result and hit return, it goes to whatever was highlighted, not a list of options. (I presume this is 100% intentional, and it's okay if people are attentive.)

- If I type something that doesn't exist in the search results and hit return, absolutely nothing happens. I'd like to see it flagged that there are no results in some way, options including:
   - a) As I'm typing, show a "no results for that search term" message in the same dropdown place you're usually showing results
    - b) Once I hit return, show a temporary message that there are no results for that term. 
    - c) Once I hit return, scroll me down to the "suggest new content" button while also showing me a note that nothing was returned for my search.

**Comment by jessicaschilling** [comment]
@cwaring - how difficult would this be to implement?

**Comment by jessicaschilling** [comment]
We discussed this in a sync meeting today and are proposing deferring this issue in favor of #336, since that kills more birds with one stone. Closing this issue - thank you!
