### ISSUE TITLE
[DOCS ISSUE] sidebar menu item click-ed state behavior confusing

### ISSUE THREAD

**Issue by momack2** [ipfs/docs#420]
I notice the first time I click on a sidebar title (ex "concept") it expands a list of sub menu items - however if I click away to "install" that submenu stays open and navigating back to "concept" actually *collapses* the submenu view. This is confusing behavior (would expect clicking away to install would also un-expand the sub menu by default, and re-clicking would re-expand) without some sort of expand/collapse affordance that I can see move between clicks that indicates the state of this submenu. Could we either add an affordance to show if submenu expanded/collapsed, or by default un-expand the menu when other menu item is clicked?

**Comment by jessicaschilling** [comment]
@cwaring, we'd discussed this in the past. Can you please investigate? Thank you!

**Comment by cwaring** [comment]
Agree to keep this on the todo list! This is mostly a problem because "Install IPFS" is currently not a group section like the other menu items, there are plans to change this in an upcoming content re-org so this may become a "Getting Started" section containing "Install IPFS", which would then make the navigation behave consistently.

Additionally I could apply a patch to disable the ability to collapse the menu if we don't wish to take advantage of this functionality in the future.

Let's discuss in the next design review to iron these quirks out :)

**Comment by jessicaschilling** [comment]
We *could* separate out the https://docs-beta.ipfs.io/install/  page into three separate pages in the interim, which is a little bit of overkill considering they don't each have a ton of content on them, but it would effectively fix the expand/collapse issue. I'd suggest leaving that top-level install page as it is, but blow out each of its sub-sections (dip your toes, host/share files on your own, host/share at scale, integrate into your app) into its own page, with additional content on them.

@johnnymatthews - what do you think? Are you amenable to writing some additional content foe each of those pages/do you have time right now?

**Comment by johnnymatthews** [comment]
**Install IPFS** is going to end up in a section called **Getting Started**, so it'll act exactly the same as the other _group sections_. Here's the revamped docs map as a refresher (will change over time).

![Map Revamp](https://user-images.githubusercontent.com/9611008/72093496-7844e480-32e2-11ea-800c-dd5ebd465762.png)

**Comment by jessicaschilling** [comment]
Good point -- and Getting Started content is a high-ish priority, correct? Closing this issue to keep things tidy. Thanks!

**Comment by ericronne** [comment]
@johnnymatthews before implementing, if we haven't already done so, it'd be wise to test the new structure with users to confirm that they can find what they need, that categories and labels make sense :bowtie:

you can use workflowy for lightweight IA tests on docs (even though that's not what it's designed to do), like we've done previously for the beta site …
https://workflowy.com/s/ipfs-docs-eric/Z0bburAwrxtbpKTh

or something like treejack, which has the benefit of a fancy [explainer video](https://www.optimalworkshop.com/treejack)
https://www.optimalworkshop.com/solutions/information_architecture

**Comment by johnnymatthews** [comment]
So I _did_ build the site with the new sidebar mapping, but I foolishly cloned over it during the Christmas break. I'll throw it all together again over the weekend for testing again.

**Comment by jessicaschilling** [comment]
And we've already got a bunch of users you can test with from the [beta testing Google form](https://docs.google.com/forms/d/1LVaD1B2uyW6Ff0jfU_iQ5mCeyQcHfyQO6BDD99XAgK0/edit) 😊

**Comment by johnnymatthews** [comment]
Didn't get a chance this weekend to build the side-nav, mainly due to the NFL playoffs. I've got a 2 hour train journey this evening though, so I'll be able to get it done then.
