### ISSUE TITLE
[DOCS ISSUE] (Simplify introduction paragraph to IPFS)

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#426]
**URL of the page in question:**
https://docs-beta.ipfs.io/concepts/what-is-ipfs/

**What's wrong with this page?**
The following paragraph is fairly convoluted and contains formatting errors that don't fit with this projects contribution guidelines:

> What does that mean, exactly? Let’s say you’re doing some research on aardvarks. (Just roll with it; aardvarks are cool! Did you know they can tunnel 3 feet in only 5 minutes?) You might start by visiting the Wikipedia page on aardvarks at

**What would you like to have changed/amended/fixed in order to make things right?**
Simplify the paragraph so that it's easier to read. Also, remove the brackets causing the formatting and grammar issues.

**Comment by alex-example** [comment]
I'll take this one.
