### ISSUE TITLE
[BUG]: Firefox doesn't jump to #links

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#429]
Firefox 72.0.2 (64-bit) doesn't jump to `#links` in the [beta docs site](https://docs-beta.ipfs.io/concepts/glossary). The gif below explains the issue a bit better. The first browser is Firefox, and the second is Brave 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit).

![firefox-scroll-bug](https://user-images.githubusercontent.com/9611008/73007100-dccf6b80-3dd9-11ea-9a4c-d55f3555f8d0.gif)

## Recreate bug

1. Open Firefox. 
2. Go to the [Glossary page in the docs beta site](https://docs-beta.ipfs.io/concepts/glossary).
3. Click on any of the letter at the top of the page.
4. Firefox does not auto-scroll to that letter's heading.

## Expected

Firefox should auto-scroll down to the applicable letter's heading in the same way that other browsers do (Chrome and Brave as examples). 

## Other notes

I've not tested this on other browsers Opera or Edge.

**Comment by bertrandfalguiere** [comment]
Confirmed on my Firefox 72.0.2 (64-bit).... but it's working if I click twice on the same letter (no necessarily a double-click).

**Comment by bertrandfalguiere** [comment]
In fact, it's working if you click on a letter, and then on another letter (goes to this second letter).

**Comment by johnnymatthews** [comment]
Yeah you're right @bertrandfalguiere, clicking on a letter _twice_ seems to work.

**Comment by cwaring** [comment]
Yes, this appears to be another issue with how Firefox interacts with [`vuepress-plugin-smooth-scroll`](https://github.com/vuepress/vuepress-plugin-smooth-scroll) in the default theme. I have an idea of how to implement this differently so let's label it as a 🐞 and I'll experiment soon.

**Comment by bertrandfalguiere** [comment]
I get both smooth scroll and one-click jump on FF Android (Jumps didn't work on mobile either). I haven't re‐tested the desktop.

**Comment by johnnymatthews** [comment]
Looks like you've fixed it @cwaring! Works on my end. There's no smooth-scrolling, but I can live without that to be honest.
