### ISSUE TITLE
[CONTENT REQUEST] Migration of the IPFS repository to a different computer

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/docs#442]
**What's the subject of the item you're requesting?**

How to migrate the IPFS repository to a different computer

**What's the content of the item you're requesting?**

Instructions on how to move the ipfs repository to a different computer.

**What will the user know how to do after going through this item?**

How to migrate. I don't know if we should have a canonical way (copy the folder), or actually list several ways of migrating.

**Would you be interested in helping create this item?**

No.

**Is there any other feedback you'd like to share about IPFS docs?**

This question is asked and answered again and again and again in the forums.

**Comment by jessicaschilling** [comment]
@hsanjuan Do you have an example of this being answered in the forums that would make good source material for someone to produce this material?

**Comment by johnnymatthews** [comment]
Judging from [the issue it's coming from](https://github.com/ipfs/go-ipfs/issues/3696), it looks like this is something new that's cropped up. I had a quick look and couldn't see anything in the forums. We'll likely need @hsanjuan or someone from `ipfs/go-ipfs` to walk us through the process.

**Comment by jessicaschilling** [comment]
@johnnymatthews -- I was the one who marked it as high-priority, because of @hsanjuan's statement about appearing in the forums again and again, but if that's not entirely the case, you may want to deprioritize.

**Comment by johnnymatthews** [comment]
Ah right you are! Not had tea this morning...

**Comment by jessicaschilling** [comment]
These may help:
https://github.com/ipfs/fs-repo-migrations
https://github.com/ipfs/js-ipfs-repo-migrations

**Comment by hsanjuan** [comment]
the most recent https://discuss.ipfs.io/t/ipfs-node-data-migration/7208

Will have to make a list of possible options:

* full migration with identity and config: copy  the folder
* full migration of content only: copy the folder, reinitialize the config (there might be pitfalls here)
* full migration of content only over ipfs: ipfs refs local method + ipfs block get
* migration of pinned items only over ipfs: ipfs pin ls --type=recursive + ipfs pin add (repeat with direct pins)
* migration of mfs items only: ?
* Rsync?

---

> These may help:
> https://github.com/ipfs/fs-repo-migrations
> https://github.com/ipfs/js-ipfs-repo-migrations

these are not related, these refer to repository-format migrations between versions.

**Comment by johnnymatthews** [comment]
Seems fairly simple, for the first two at least. I'm assuming it's cross-platform as well, right? An `.ipfs` folder from a Windows machine will work fine when copied over to a Unix machine?

**Comment by johnnymatthews** [comment]
Working branch here: [`ipfs/copy-ipfs-to-computer`](https://github.com/ipfs/ipfs-docs-v2/tree/copy-ipfs-to-computer).

**Comment by hsanjuan** [comment]
> Seems fairly simple, for the first two at least. I'm assuming it's cross-platform as well, right? An `.ipfs` folder from a Windows machine will work fine when copied over to a Unix machine?

Probably, but there might be some edge cases. @Stebalien can you say?

**Comment by Stebalien** [comment]
Yes. An IPFS folder _should_ port across platforms fine (untested).

**Comment by johnnymatthews** [comment]
I've tested: 

1. MacOS Catalina -> Windows 10
1. Windows 10 -> Windows Subsystem for Linux
1. Windows Subsystem for Linux ->
1. Ubuntu -> MacOS

Figured that was enough.

**Comment by ribasushi** [comment]
> An IPFS folder should port across platforms fine (untested).

@Stebalien what about case-insensitive FSes ? Do we store anything in non-base32 in a version of an `/.ipfs` format?

**Comment by hsanjuan** [comment]
the keystore files I think, but I'm not sure those go on flatfs. There's a migration almost ready to fix this.

**Comment by hsanjuan** [comment]
Actually yes, the keystore files go on disk.

**Comment by johnnymatthews** [comment]
Is it worth mentioning that there might be issues with moving things to Windows then? I didn't encounter any, but if it's something that could potentially trip people up then we might want to point that out. No sure what the _fix_ would be if Windows does start complaining.

**Comment by hsanjuan** [comment]
Not worth, because that potential issue will be fixed by 0.5.0

**Comment by johnnymatthews** [comment]
Sounds good. I'll close this issue for now then.
