### ISSUE TITLE
[DOCS ISSUE] Add link to Anatomy of a CID tutorial on ProtoSchool

### ISSUE THREAD

**Issue by terichadbourne** [ipfs/docs#446]
We can now add a link from https://docs-beta.ipfs.io/concepts/content-addressing/#identifier-formats (or any other spots you recommend) to the new ProtoSchool tutorial Anatomy of a CID: https://proto.school/#/anatomy-of-a-cid

**Comment by johnnymatthews** [comment]
Nice. I'll add links into the [`ipfs/ipfs-docs-v2:protoschool-cid-tutorial` branch](https://github.com/ipfs/ipfs-docs-v2/tree/protoschool-cid-tutorial).
