### ISSUE TITLE
Wrong installation instruction on deployed site

### ISSUE THREAD

**Issue by ibnesayeed** [ipfs/docs#46]
Currently, at https://ipfs.io/docs/install/ the install instruction on Mac OS X and Linux suggests to run the following command after downloading.

```
tar xvfz go-ipfs.tar.gz
./go-ipfs/install.sh
```

This fails because `install.sh` script is programmed to move `ipfs` directory of the current directory into the binpath. That `ipfs` directory is not in the current working directory yet. To fix this, either the install script can be updated to locate `ipfs` directory from within its current directory, not the current working directory or the instructions can be changed as following:

```
tar xvfz go-ipfs.tar.gz
cd go-ipfs
./install.sh
```

That said, the documentation at https://github.com/ipfs/docs/blob/master/content/start/install.md is correct as it does not use the install script.

I don't how where is the source of the deployed site, but instruction on https://ipfs.io/docs/install/ needs to be updated.

/CC @diasdavid

**Comment by diasdavid** [comment]
@whyrusleeping @lgierth can you check this?

**Comment by VictorBjelkholm** [comment]
This was fixed in https://github.com/ipfs/website/pull/249
