### ISSUE TITLE
[DOCS ISSUE] Page: IPNS

### ISSUE THREAD

**Issue by kevincox** [ipfs/docs#466]
**URL of the page in question:** https://docs-beta.ipfs.io/concepts/ipns/

**What's wrong with this page?**
It contains no information about creating, backing up and restoring keypairs.

**What would you like to have changed/amended/fixed in order to make things right?**
I would add that information!

**Comment by johnnymatthews** [comment]
Thanks for bringing this up @kevincox. These issues are being addressed in [`ipfs/ipfs-docs-v2` PR 82](https://github.com/ipfs/ipfs-docs-v2/pull/82).

**Comment by johnnymatthews** [comment]
Gonna close this issue as it's mostly a duplicate of #90. Feel free to re-open if you think this is a significantly different issue.
