### ISSUE TITLE
File Upload on Windows Failed

### ISSUE THREAD

**Issue by tulaneadam** [ipfs/docs#468]
The file upload on Windows failed and produced the following error:
"Failed to add files to IPFS. Please try again".  The developer console in chrome is showing the error to be API related.  A gif/video is attached to show how to reproduce the issue.

![screen-capture](https://user-images.githubusercontent.com/5349553/76808629-b7018a00-67be-11ea-8044-c840c27677bf.gif)

**Comment by tulaneadam** [comment]
I've tested the app in the same way on mac and linux (Debian) and had no issue uploading a file.

**Comment by jessicaschilling** [comment]
Hi @tulaneadam -- this sounds like a question for the IPFS forums, where you'll have access to input from folks across the IPFS community (this repo is for documentation-specific issues). Can you please post there? https://discuss.ipfs.io/
I'll close this issue in the meantime. Thanks!

**Comment by tulaneadam** [comment]
Hi Jessica,
Sure, will do.  Sorry for posting in the wrong place.  Love the
application/project!

**Comment by jessicaschilling** [comment]
Thanks @tulaneadam! Appreciate your raising this!
