### ISSUE TITLE
Go-IPFS 0.5 release

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#470]
This is the _epic_ issue for the Go-IPFS 0.5 release. Closing the following issues closes this epic: #471, #472, #473, #474.

This 0.5 release is slated to be the biggest release since the Go-IPFS project started. See the [Road to 0.5 issue in `ipfs/go-ipfs`](https://github.com/ipfs/go-ipfs/issues/6776) for more details regarding the release.

With the release of Go-IPFS 0.5 coming up, we need to create a place for major update docs to sit. Below is a solution that should work just fine, but can be altered in the future if needed. I'd rahter not spend too much time discussing and deliberating over this layout since 0.5 is due to be released in early April, and so we need this out the door by then.

```
Install IPFS    <--- Main dropdown label
    Desktop    <--- Page
    Browser
    Terminal
Updates    <--- Main dropdown label
    Go-IPFS 0.5 release    <--- Bold label
        Overview    <--- Page
        Update procedure
        Features
            IPNS    <--- H2 in page
            IPFS subdomain gateway
            Bitswap
            Data stores (Badger)
            ...
        Fixes
        Troubleshooting
            Node discoverability
```

Here is an example screenshot from the ipfs-docs-v2 beta to demonstrate the labeling system:

![label-header-example](https://user-images.githubusercontent.com/9611008/76996007-22ff0200-6927-11ea-9004-ed8c21847945.png)

**Comment by johnnymatthews** [comment]
See [`ipfs/ipfs-docs-v2:go-ipfs-0.5`](https://github.com/ipfs/ipfs-docs-v2/tree/go-ipfs-0.5) branch.

**Comment by johnnymatthews** [comment]
Here's a screen cap the sidebar.

![Annotation 2020-03-19 131501](https://user-images.githubusercontent.com/9611008/77095016-b6960880-69e3-11ea-9f71-358b78fbc782.png)

Having *Go-IPFS 0.5* one of the bolded labels, this gives us room to expand for other major releases like JS-IPFS, or Rust when that comes out.

**Comment by jessicaschilling** [comment]
Awesome 😊 
Would "Release notes" make more sense than "Updates"?

**Comment by johnnymatthews** [comment]
Yeah, although it's not all strictly release notes. _Releases_ might work better.

**Comment by jessicaschilling** [comment]
"Recent releases"?
Just to make it really clear that it's not somewhere you can get ALL the releases ... that's the dist.ipfs.io site.

**Comment by johnnymatthews** [comment]
Good point. Yeah ok, let's go with _Recent releases_.

**Comment by momack2** [comment]
Awesome! Thank you.

**Comment by johnnymatthews** [comment]
Go-IPFS 0.5 released!
