### ISSUE TITLE
Deprecate legacy docs site

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/docs#475]
Deprecate the legacy docs site in accordance with the plan created here: https://hackmd.io/-JU3CcXgSgmcXWszyku2PA

**This issue is one of the prioritized recommendations in the [Q1 2020 IPFS Ecosystem Audit](https://github.com/ipfs/community/tree/master/ecosystem-audit) for execution in Q2/Q3 2020. Tagging it with `$auditrecommendation` means it's searchable! See [all tagged issues](https://github.com/ipfs/docs/issues?q=is%3Aissue+%22%24auditrecommendation%22+) in this repo.**

**Comment by hugomrdias** [comment]
whats DoD here ?

**Comment by hugomrdias** [comment]
All items from here https://hackmd.io/-JU3CcXgSgmcXWszyku2PA have been handled. 

Please refer to https://github.com/ipfs/ipfs-docs/issues/240 if we have missed something.

Thank you.
