### ISSUE TITLE
[CONTENT REQUEST] Reading list: papers to understand IPFS

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/docs#479]
**This issue is one of the prioritized recommendations in the [Q1 2020 IPFS Ecosystem Audit](https://github.com/ipfs/community/tree/master/ecosystem-audit) for execution in Q2/Q3 2020. Tagging it with `$auditrecommendation` means it's searchable! See [all tagged issues](https://github.com/ipfs/docs/issues?q=is%3Aissue+%22%24auditrecommendation%22+) in this repo.**

Is there an item missing from IPFS documentation that would be helpful to you? Please use this template to let us know!

**What's the subject of the item you're requesting?**

Papers to understand IPFS

**What's the content of the item you're requesting?**

Move https://github.com/ipfs/reading-list to somewhere in the docs site.

**What will the user know how to do after going through this item?**

Reference papers that are really important and that form the base of the IPFS/libp2p design choices. List should be kept small (not a dump of all p2p related papers).

**Comment by johnnymatthews** [comment]
Nice find! Didn't even know we had that repo!

This would probably fit best under the **Concepts** section, likely in a sub-section called **Further reading**:

![Annotation 2020-03-26 132926](https://user-images.githubusercontent.com/9611008/77677278-d8543a00-6f65-11ea-9261-bbf103e1ca92.png)

This could be a very quick win, for anyone who wants to pick it up:

1. Create a new sub-section called **Further reading** under **Concepts**.
1. Create a new page called **Academic papers**.
1. List the papers found in [`ipfs/reading-list`](https://github.com/ipfs/reading-list).
1. Add a short summary for each paper.
1. Add page and section to sidebar.

**Comment by jessicaschilling** [comment]
Note that this is currently mid-ranked in our ecosystem audit recommendations. See:
https://airtable.com/tbl21O1nXqFA7ADcT/viws9P58CvH333ZAW/recQtSEQ9FCcotGAH

**Comment by johnnymatthews** [comment]
Nice. That recommendation is to add the reading list into the `ipfs.io` website, not the docs. Is this still the case? If so I'll close this issue. No sense in having the same list in two places.

**Comment by jessicaschilling** [comment]
@johnnymatthews Let's add to the docs, not the website. Please keep this issue open and we'll work it here.

**Comment by johnnymatthews** [comment]
Ok cool, I'll leave it in here then :)

**Comment by johnnymatthews** [comment]
No idea why I closed that...
