### ISSUE TITLE
CLI docs outdated

### ISSUE THREAD

**Issue by hsanjuan** [ipfs/docs#482]
**URL of the page in question:**
https://docs-beta.ipfs.io/reference/cli/

**What's wrong with this page?**
Outdated

**What would you like to have changed/amended/fixed in order to make things right?**

Good question, can we run the script or do we need to upgrade the script to produce this format?

**Would you be interested in helping fix this page?**
I guess

**Comment by RubenKelevra** [comment]
@hsanjuan well, wrong repo, but I fixed it:

https://github.com/ipfs/ipfs-docs-v2/pull/155
