### ISSUE TITLE
[DOCS ISSUE] broken sidenav link

### ISSUE THREAD

**Issue by momack2** [ipfs/docs#483]
"Traverse IPLD graphs" in the docs v2 side nav has a broken link: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/examples/

**Comment by momack2** [comment]
so is https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/examples/custom-libp2p

**Comment by momack2** [comment]
and https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/examples/circuit-relaying

**Comment by momack2** [comment]
Can we do an audit of all the outbound links (and also reconsider whether they SHOULD be outbound links or directly included in the docs website)?

**Comment by jessicaschilling** [comment]
Closed via https://github.com/ipfs/ipfs-docs-v2/pull/158
Looks like a bunch of linked .md documents in the js-ipfs repo were recently moved. Links have been updated to their new locations.

There's already an issue open to bring the instructional materials in the js-ipfs repo into the docs themselves: https://github.com/ipfs/docs/issues/456. @johnnymatthews, you may wish to prioritize this.

**Comment by johnnymatthews** [comment]
Agreed.
