### ISSUE TITLE
[DOCS ISSUE] Page: The IPFS project

### ISSUE THREAD

**Issue by momack2** [ipfs/docs#487]
**URL of the page in question:**
https://docs-beta.ipfs.io/project/

**What's wrong with this page?**
All the content here is very out of date and confusingly orthogonal to the info in github.com/ipfs/roadmap

**What would you like to have changed/amended/fixed in order to make things right?**
Where needed, merge this into ipfs/roadmap, and then deprecate these pages and replace with docs about our actual project roadmap.

**Comment by jessicaschilling** [comment]
Are you actually talking about this page?
https://docs-beta.ipfs.io/project/roadmap/
If so:
- That was material from the old ipfs/ipfs repo
- Suggest removing that page entirely and replacing it with a link out to https://github.com/ipfs/roadmap/blob/master/README.md

**Comment by momack2** [comment]
Good point. That is easier and faster than trying to integrate the roadmap in here - and less participatory.

**Comment by johnnymatthews** [comment]
Marking this as closed as the link's been added. Feel free to re-open this is you think it needs more info/details.
