### ISSUE TITLE
[DOCS ISSUE] Page: Command-line quick start

### ISSUE THREAD

**Issue by DavidBurela** [ipfs/docs#494]
**URL of the page in question:**
https://docs-beta.ipfs.io/how-to/command-line-quick-start/#install-ipfs

**What's wrong with this page?**
The install quickstart jumps from *"just download the binary"* to advanced *"have a Go dev environment configured"*

**What would you like to have changed/amended/fixed in order to make things right?**
I think the entire system about having a Go environment configured should be removed, and replaced with a link, the same with "building from source". Same with building from source.

Instead the install details progression should be:

1. Fastest: download go-ipfs binaries
2. use ipfs-ipdate

sample install steps for ipfs-update

```bash
# download ipfs-update. Replace with latest version from https://dist.ipfs.io/#ipfs-update
wget https://dist.ipfs.io/ipfs-update/v1.6.0/ipfs-update_v1.6.0_linux-amd64.tar.gz

# extract 
tar -zxvf ipfs-update_v*

# go into folder and install
cd ipfs-update/
sudo ./install.sh

# ipfs-update should now be installed
ipfs-update help

# install latest version of ipfs
sudo ipfs-update install latest
```

**Would you be interested in helping fix this page?**
I forked and started editing, but thought the changes might be a bit too drastic, so started an issue instead.

I've posted an ipfs-update quickstart to my own blog while the discussion takes places https://davidburela.wordpress.com/2020/04/26/installing-ipfs-via-ipfs-update-on-linux-or-wsl/

**Comment by DavidBurela** [comment]
Some of the same documentation may be used in this similar issue #465

**Comment by johnnymatthews** [comment]
Thanks for raising this @DavidBurela. Let's continue this conversation over in #465.
