### ISSUE TITLE
Add “this URL will be changing” messaging to beta site pages.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#502]
All URLs in the `docs-beta.ipfs.io` site will be changing to `docs-ipfs.io`. We need a call-out on all pages for this.

**Comment by cwaring** [comment]
we shouldn't need a callout for this because we can auto [301 redirect](https://en.wikipedia.org/wiki/HTTP_301) `docs-beta.ipfs.io/*` -> `docs.ipfs.io/*` as part of the switchover plan and all urls will follow across.

**Comment by jessicaschilling** [comment]
We don't *need* one, but it's a good courtesy to the reader: heads up, these URLs are changing soon.

**Comment by cwaring** [comment]
I think that's just confusing though, the end user won't really notice anything different?

**Comment by jessicaschilling** [comment]
Yes and no? It's useful to draw people's attention to the change (particularly for folks who rely on auto-complete in their URL bars, ha), but we don't want to draw TOO much attention.

**Comment by johnnymatthews** [comment]
What are everyone's thoughts on something like this:

![Screenshot of potential call-out at bottom of a docs page.](https://user-images.githubusercontent.com/9611008/81007552-6eaa3400-8e1f-11ea-8d42-f85a90de0d18.png)

It's not too obtrusive, points out what's going to happen, and re-uses existing code so I don't have to fight with VuePress too much.

**Comment by jessicaschilling** [comment]
Unfortunately I think it'll get ignored at the bottom of the page.
But, you could really easily duplicate the logic behind that box and put another box at the top of every page that contains the note. If you wanted to be really consistent, you could change the background color to warning yellow, as in here: https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers

**Comment by johnnymatthews** [comment]
Here's a hacky PR I threw together: https://github.com/ipfs/ipfs-docs-v2/pull/198
