### ISSUE TITLE
Prepare the necessary redirects and create a master redirect list.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#503]
- [x] Document the needed redirects from legacy site to their final destinations post-deprecation (URL on legacy docs.ipfs.io -> another URL on “new” docs.ipfs.io)
- [x] Document the needed redirects from beta site to the final URLs post-deprecation (docs-beta.ipfs.io/foo/bar -> docs.ipfs.io/foo/bar)
- [ ] Double-check throughout for duplication or collision
- [x] Investigate how we’re actually going to implement the redirects; who in infra needs to help? 

Note that the legwork of finding equivalent URLs has already been done in each site’s callout boxes cross-linking between legacy and beta.

**Comment by cwaring** [comment]
🎁 - these are the primary redirects that need to be implemented on `docs.ipfs.io` to accommodate the migration to the new site: https://docs.google.com/spreadsheets/d/1tTU4g06G2Wm3RYIUow-23__oAEJ6v0-MBZfgsi9Dix0/edit#gid=1026868835

**Comment by cwaring** [comment]
(hat tip to @jessicaschilling for helping compile this)

**Comment by hugomrdias** [comment]
https://github.com/protocol/bifrost-infra/pull/763 this PR deploys the list to beta domain, deploy to production will be tracked here https://github.com/ipfs/ipfs-docs/issues/238
