### ISSUE TITLE
Check for old legacy site redirects.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#504]
Are there any old, existing redirects on the legacy site that will be overwritten by our other redirect work? If so, remedy.

**Comment by johnnymatthews** [comment]
Messaged Infra to see if there are any existing redirects. If there are, we just need to add them into the main redirect list (if they're still applicable).

**Comment by hugomrdias** [comment]
can we close this ?

**Comment by hugomrdias** [comment]
i have checked this and theres no redirects in the production domain.

closing
