### ISSUE TITLE
Examine top inbound-links referrers for proactive-fix opportunities.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#506]
- [x] Examine top referrers for inbound links to see if there are any opportunities to directly contact those referrers and ask links to be changed
- [x] Find GitHub repos and add pull-requests to change and relevant links.
- [x] Make forks.
- [ ] Merge after site goes live.

**Comment by johnnymatthews** [comment]
The overwhelming majority of inbound links into `docs-beta.ipfs.io` are coming from GitHub, specifically the `ipfs/ipfs-docs-v2` and `ipfs/docs` repos. All these links will get caught in the `docs-beta.ipfs.io` -> `docs.ipfs.io` redirect rules in #503.

**Comment by jessicaschilling** [comment]
What about links to docs-beta from our own codebases -- not so much thinking of links that live within people just clicking on things in GitHub, but things like the "read more" links within IPFS Companion's prefs? I understand that they'll get redirected ... it's just kind of poor optics if we have out-of-date links in our own products.

**Comment by autonome** [comment]
With a release manager hat on, I'd characterize this as "non-blocking mustfix"

* doesn't need to block the release, because redirects are in place
* must be fixed as post-release cleanup

**Comment by jessicaschilling** [comment]
If we're tentatively pushing to the 27th (to avoid collision with another release @cwaring is critical in), there might still be time to wrap this up before then -- if not, completely agree with @autonome.

**Comment by johnnymatthews** [comment]
[This spreadsheet](https://cryptpad.fr/sheet/#/2/sheet/view/xRL1ZlR9H2AdOeN-0xkdMVlaXjlmB2EixsEWnvLU+pk/) lists all the IPFS and Protocol org repos with links to `docs-beta`.

**Comment by hugomrdias** [comment]
What else needs to be done here ?

**Comment by hugomrdias** [comment]
Since the only repo from the above sheet is infra, im closing this.
Refer to https://github.com/ipfs/ipfs-docs/issues/240 for the launch task list.

**Comment by jessicaschilling** [comment]
https://github.com/search?q=org%3Aipfs+docs-beta.ipfs.io&type=Code = 34 inbound links from the IPFS org. Some are within the docs repos themselves, but the other ones should be fixed.

**Comment by jessicaschilling** [comment]
It doesn't look as though the spreadsheet is complete. There are links to docs-beta in multiple places throughout repos in the IPFS GitHub org.

**Comment by jessicaschilling** [comment]
I'll just fix those myself.
