### ISSUE TITLE
Determine what needs to be done regarding metrics.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#508]
We don’t want to lose our old analytics figures, because we want to use them for comparison. Let's find out how to keep all our data in one place.

**Comment by hugomrdias** [comment]
can you add me to ga production and beta please? 
what do you want to do here ? production will have the old docs plus new and you can see by date and beta will keep having beta.

**Comment by johnnymatthews** [comment]
Requested access for you @hugomrdias. 

I think we discussed merging the Docs Beta analytics into the legacy stuff, so that everything's accessible from one place. Right? Then if we need to see legacy stats we can just select a date range _before 27th May 2020_.

**Comment by hugomrdias** [comment]
can we close this ?

**Comment by cwaring** [comment]
We can keep the beta GA profile, just rename it and disable the old one.

**Comment by hugomrdias** [comment]
can't we keep both, make them "production" and "staging"?

**Comment by cwaring** [comment]
We don't log a staging for GA or require it - the reason I suggest keeping
the current beta profile is that we have dashboards and auto reports setup
already, along with even tracking for the requested and helpful / not
helpful topics. We can't migrate this data so it would be lost if we
switched to a different profile.

**Comment by hugomrdias** [comment]
We keep beta account to track production.

Refer to https://github.com/ipfs/ipfs-docs/issues/240 for launch
