### ISSUE TITLE
Increase urgency of deprecation alerts on legacy content.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#509]
This issue should be completed one week before deprecation.

- [ ] make background red
- [ ] replace laptop image with alert triangle

**Comment by hugomrdias** [comment]
whats the status on this ?

**Comment by johnnymatthews** [comment]
I put it on the back-burner while we worked on other stuff. It's not super vital, but feel free to tackle it if you're looking for something to do.

**Comment by hugomrdias** [comment]
cool gonna close this then.
