### ISSUE TITLE
Submit new sitemaps to search providers.

### ISSUE THREAD

**Issue by johnnymatthews** [ipfs/docs#513]
This is a follow up from #505. We need to give the new site maps over to Google, Bing, DuckDuckGo, and any other _major_ search providers so they're up to date.

- [x] Install [Vuepress Sitemap plugin](https://github.com/ekoeryanto/vuepress-plugin-sitemap).
- [x] Generate sitemap.
- [x] Add sitemap location to `robots.txt`, something like `Sitemap: http://example.com/sitemap_location.xml`. More [info from Google here](https://support.google.com/webmasters/answer/183668?hl=en).
- [x] Ping Google to re-crawl the site: `http://www.google.com/ping?sitemap=https://example.com/sitemap.xml`.

**Comment by cwaring** [comment]
there is currently no sitemap generated for the docs beta due to the beta crawler visibility. [this plugin](https://github.com/ekoeryanto/vuepress-plugin-sitemap) needs to be installed and configured.

**Comment by johnnymatthews** [comment]
Lovely. Added that step to the top comment.

**Comment by cwaring** [comment]
grand, I'm trying to follow along to add context where I can

**Comment by hugomrdias** [comment]
this is done, everything will be updated when we release to production
