### ISSUE TITLE
[DOCS ISSUE] (CLI help says output of ipfs ls is in JSON)

### ISSUE THREAD

**Issue by dadepo** [ipfs/docs#515]
Did you find a bug, typo or other issue in an item of IPFS documentation? Please use this template to let us know!

**URL of the page in question:**
https://docs-beta.ipfs.io/reference/cli/#ipfs-ls

**What's wrong with this page?**
Technically this is not about the documentation itself but the help text in the CLI. The help text says that:

> The JSON output contains type information.

but when I use `ipfs ls` the output I get is not in JSON. For example

```
$ ./ipfs ls /ipfs/QmQPeNsJPyVWPFDVHb77w8G42Fvo15z4bG2X8D2GhfbSXc
QmQy6xmJhrcC5QLboAcGFcAE1tC8CrwDVkrHdEYJkLscrQ 1681 about
QmYCvbfNbCwFR45HiNP45rwJgvatpiW38D961L5qAhUM5Y 189  contact
QmU5k7ter3RdjZXu3sHghsga1UQtrztnQxmTL22nPnsu3g 311  help
QmejvEPop4D7YUadeGqYWmZxHhLc4JBUCzJJHWMzdcMe2y 4    ping
QmQGiYLVAdSHJQKYFRTJZMG4BXBHqKperaZtyKGmCRLmsF 1681 quick-start
QmPZ9gcCEpqKTo6aq61g2nXGUhM4iCL3ewB6LDXZCtioEB 1091 readme
QmQ5vhrL7uv6tuoN9KeVBwd4PwfQkXdVVmDLUZuTNxqgvm 1162 security-notes
```

**What would you like to have changed/amended/fixed in order to make things right?**
Remove the line about the JSON output if that is not indeed the case. Or fix the output to be JSON so as to match the help text.

**Would you be interested in helping fix this page?**
Yes, if there is clarity on exactly what is wrong and the acceptable fix

**Is there any other feedback you'd like to share about IPFS docs?**

**Comment by johnnymatthews** [comment]
This page is generated automatically by [a script](https://github.com/ipfs/docs/blob/master/scripts/cli.sh) and shouldn't be modified by hand. Since this output comes from Go-IPFS, They're really appreciate it if you [raise the issue there](https://github.com/ipfs/go-ipfs).

I'll close this issue for now. Feel free the re-open this if you think there's more to discuss.
