### ISSUE TITLE
[CONTENT REQUEST] Add CTA to signup for IPFS Newsletter

### ISSUE THREAD

**Issue by renrutnnej** [ipfs/docs#520]
We should prompt visitors to join the weekly newsletters so we can keep them up to date on project and community news, via [the list on the Community page](https://docs-beta.ipfs.io/community/).

I can provide an embed or integration via Mailchimp.

**Comment by johnnymatthews** [comment]
Sounds like a good idea. Do you have links to the Mailchimp integration?

**Comment by jessicaschilling** [comment]
@johnnymatthews @renrutnnej Not sure if embeds or integrations will work correctly in this context. The quickest means to achieve this would be to:
1. Add a short paragraph to the paragraphs on https://docs-beta.ipfs.io/community/ linking to the newsletter signup page
2. Add a link to the newsletter signup page in the left nav under "Community", in the same position as it appears on the community page itself

**Comment by renrutnnej** [comment]
This link: https://ipfs.us4.list-manage.com/subscribe?u=25473244c7d18b897f5a1ff6b&id=cad54b2230 will take you to the Mailchimp signup.

**Comment by johnnymatthews** [comment]
[`/project` might be a better location](https://docs-beta.ipfs.io/project/). Depends on how much of the content of the newsletter is about the IPFS community as a whole, and how much is dedicated to just the IPFS project. I'll lean on your judgement here @renrutnnej.

**Comment by renrutnnej** [comment]
I think community is best, the blog is the official platform for the project.

**Comment by renrutnnej** [comment]
Not sure how long of a blurb you need but here's some language:

Sign up for the IPFS Weekly newsletter to get project updates, community news, event details, and more. In your inbox, each Tuesday.

**Comment by johnnymatthews** [comment]
> Sign up for the IPFS Weekly newsletter to get project updates, community news, event details, and more. In your inbox, each Tuesday.

That'll do!

**Comment by johnnymatthews** [comment]
Here we go.

![image](https://user-images.githubusercontent.com/9611008/81137810-f67e6400-8f2d-11ea-805c-b81eee444062.png)

Had to double-check that newsletter is a single word.
