### ISSUE TITLE
[DOCS ISSUE] Page: Hashing - Proprietary Hosting Instead of IPFS

### ISSUE THREAD

**Issue by edu-cated** [ipfs/docs#521]
Did you find a bug, typo or other issue in an item of IPFS documentation? Please use this template to let us know!

**URL of the page in question:**
_e.g. https://docs.ipfs.io/introduction/usage/_

**What's wrong with this page?**
The page links to an IPFS instructional video hosted on a proprietary site:
https://www.youtube.com/watch?v=Z5zNPwMDYGg

**What would you like to have changed/amended/fixed in order to make things right?**
This content was created at an IPFS camp. It should have been hosted on a canonical IPFS website and presented to the user as an IPFS hash by default. If the video creators wish to addditionally  support distribution of IPFS content using http, that ought to be an extra, rather than the only option.

**Would you be interested in helping fix this page?**
This issue needs to be fixed upstream of the page as the same thing will be happening all over the documentation. It should become a policy that IPFS content be  a) pinned and b) presented as a hash. That ought to be mandatory for documentation. http links to content should be optional.

**Is there any other feedback you'd like to share about IPFS docs?**
Greater attention to whether services are Free or non-Free ought to be made.

This is IPFS! What is the point of IPFS sharing files using http? It is like your Internet Service Provider writing to you using letters instead of email. Also, if current options for video hosting using IPFS are not yet adequate, then hopefully insisting on it will help encourage developers.

Try Peergos:
https://peergos.org/

**Comment by momack2** [comment]
Hey there! I hear your point - we should totally put these videos up on IPFS! Will work on that ASAP. For starters we'll pin a folder for folks to browse, but would be great to have others collaboratively host IPFS videos too.

However, ALSO making these videos available on YouTube is critical to reaching a wider audience and giving all the presenters at IPFS Camp discoverability with the many folks who browse or find IPFS through services with broad reach like YouTube. We're very committed to using both IPFS-powered tooling AND other services that reach a variety of audiences (both those that do and don't already know about IPFS!) 🤗
