### ISSUE TITLE
docs/content/README.md broken youtube links

### ISSUE THREAD

**Issue by EricLScace** [ipfs/docs#526]
ipfs-docs-v2/docs/concepts/README.md

[Sorry but ipfs-docs-v2 does not have an accessible issues list.]

**What's wrong with this page?**
lines 15 & 17 refer to YouTube videos but the links are incomplete.

**What would you like to have changed/amended/fixed in order to make things right?**
Replace with correct link.

**Would you be interested in helping fix this page?**
sure...

**Comment by johnnymatthews** [comment]
Fixed in [PR 213](https://github.com/ipfs/ipfs-docs-v2/pull/213).
