### ISSUE TITLE
[NEW CONTENT] [BOUNTY] Glossary

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#56]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
Create a glossary that provides a brief and clear definition of major concepts in IPFS, plus links to longer explainers when they exist. Note that we will be pulling these definitions into hover-style tool tips in the future, so please keep definitions fairly brief and written in such a way that the first *n* characters can be excerpted into a complete tool tip.

Regarding future use in tool tips: Visual design work has already been done on this effort. Please see #372 for mockups and resulting discussion; it'll help you determine how best to proceed with excerpting tool-tip content.

Below are initial terms to seed with. Please add others as you see fit. See as well prior art for [“concepts and terms that trip people up”](https://gateway.ipfs.io/ipns/ipfs-docs-research.robbrackett.com/html/General-Notes.html#concepts--terms-that-trip-people-up).

- DWeb
- DHT 
- Graph
- DAG
- Merkle Tree/DAG
- Merkle “Forest”
- Hash
- Gateway
- Pinning
- Transport
- Swarm 
- Information Space
- MFS
- UnixFS (lots of confusion out there on whether this is the same or different from MFS) 
- (Cryptographic) Signing
- Peer
- Peer ID 
- CRDT 
- Repo
- DataStore
- Node, Daemon 
- CID (v0, v1, …)
- Path/Address 
- DNSLink
- CBOR
- Bitswap 
- Blocks
- Bootstrap Node
- Listening
- Dialing
- Announcing
- Relay
- GC/Garbage Collection
- Pubsub
- Filestore
- IPLD (and selectors) 
- Libp2p
- Multihash
- IPNS
- SFS
- Blockchain
- Bittorrent
- GraphSync
- pubsub
- filestore
- IPLD
- Libp2p
- multihash
- IPNS
- SFS
- Blockchain
- Bittorrent
- IPLD Selectors
- GraphSync

## Deliverable
**Content should take the form of a Markdown document.** File locations should be as follows:
- MD content should live here (lease make a PR against the existing placeholder document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/glossary.md
- Images, if appropriate, can live in the MD content's parent directory; we'll move them before final merge
- For videos, just post temporarily on the platform of your choice, and we'll sort out on a case-by-case basis

## Guidelines
- Please use the [IPFS Docs Contributor Guidelines](https://github.com/ipfs/docs/blob/master/CONTRIBUTING.md ) as your north star — **adherence to these guidelines are crucial when it comes to awarding potential bounty**!
- Also, please keep in mind our [core user personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf). If a piece of content serves one or more personae in particular, make sure it checks out with that persona's attributes.

**Comment by MichaelMure** [comment]
- pubsub
- filestore
- IPLD
- Libp2p
- multihash

**Comment by Mr0grog** [comment]
Wow, I totally thought IPNS was on the list! Thanks.

**Comment by eocarragain** [comment]
Also:

- IPRS (see https://github.com/libp2p/specs/blob/master/IPRS.md and https://discuss.ipfs.io/t/confusion-about-ipns/1414)
- IPLD-Next

**Comment by eocarragain** [comment]
IPLD Selectors
GraphSync

**Comment by vmx** [comment]
@eocarragain The current documentation for IPLD Selectors and GraphSync is: "TBD", there isn't much else yet :)

**Comment by jessicaschilling** [comment]
Referencing this issue for benefit of @lidel and @ericronne and some of the IA-based discussion we've had about including a basic glossary (with deeplinks) at a high level of the new docs beta.

**Comment by jessicaschilling** [comment]
See libp2p's new pubsub docs here: https://docs.libp2p.io/concepts/publish-subscribe/

**Comment by edgo914** [comment]
I will begin work on this, Assign me!

**Comment by jessicaschilling** [comment]
Looks like this issue can be (or is close to being able to be) closed under https://github.com/ipfs/ipfs-docs-v2/pull/70 ... @johnnymatthews, can you please wrap things up with @edgo914 vis-a-vis bounty reward? Thanks!

**Comment by johnnymatthews** [comment]
Yeahp, the content is all good to go! I'm going to wait until the payment has been sent before closing bounty issues.

**Comment by parkan** [comment]
nice work @edgo914! we'll process your reward shortly

**Comment by parkan** [comment]
@edgo914 could you please open a [Bounty Claim] issue in [the grants repo](https://github.com/ipfs/devgrants/issues/new/choose) so we can track your payment? (the issue template will also instruct you to send your payment info via email)

@johnnymatthews please close this issue -- we'll use that as confirmation of successful completion for sending the reward

**Comment by jessicaschilling** [comment]
@parkan -- I'll close this issue on Johnny's behalf as he's away/sporadic for the next few weeks.

cc @edgo914 @johnnymatthews

**Comment by edgo914** [comment]
Away for a few days, will get to this on Monday
