### ISSUE TITLE
PM for this Sprint

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#6]
@diasdavid I would be happy to be the PM for this sprint.  I have been the PM for the test-lab sprint but I'm sure that I'm doing a very good job.   My goal with the IPFS community is to stay involved and spend as much time as I can. However, I spend about 50 hours a week writing code on a project that pays the bills.  If my work as PM on the test-lab was acceptable then I'm ready go.  If you think someone else could do a better job then thats OK as well. Just let me know.

**Comment by SidHarder** [comment]
@diasdavid One concern I have is that I would not be able to attend stand ups every day.

**Comment by diasdavid** [comment]
@SidHarder thank you so much for volunteering for this! I'm sure that we can make it work, however, I might not be the best person to make the call right now as I was two weeks out (so much backlog! woa). @flyingzumwalt can probably guide you better in the goals for that Sprint and update in anything that has been talked about.

Nevertheless, as you may already know, for the PM of the sprint, we expect:

- Someone that collects all the goals
- A prep session call to expand the goals into tasks that then can be assigned to the different individuals participating in the sprint
- A constant check in (standups or check ins through issues) ensuring that everyone feels empowered and knows exactly the work they should be focused every day.

You can find some examples of:

- Super well described - https://github.com/ipfs/in-web-browsers/issues
- More concise - https://github.com/ipfs/pm/issues/310

**Comment by SidHarder** [comment]
@diasdavid I'm not sure what the protocol is, do we need to have a meeting for Friday to discuss sprint objectives or do we wait until Monday?

**Comment by diasdavid** [comment]
Yes, a meeting on Friday will increase the odds of a successful sprint.
