### ISSUE TITLE
Discourse, to kill or not to kill

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#7]
We need to decide if we want to move discussions to discourse.  If not then we need to take it off the table.  

See also:
* **original discussion** Discourse - Better community building https://github.com/ipfs/community/issues/69
* Discourse: Evaluation Checklist https://github.com/ipfs/community/issues/213
* *.ipfs.io domain for discourse https://github.com/ipfs/ops-requests/issues/33
* Try out discourse.org for Community Forums  https://github.com/ipfs/community/issues/190
* Merge ipfs/ipfs, ipfs/community and ipfs/pm https://github.com/ipfs/community/issues/191

Action Items:
- [ ] get discuss.ipfs.io subdomain set up
- [ ] collect implementation factors -- "to host or not to host"
- [ ] gather list of pros + cons
- [ ] plan to phase out the github repositories

**Comment by Kubuxu** [comment]
Yes, we can't stay in that quasi state. We have to either decide for one or not?

What we can do is: migrate issues to discourse, set the repositories private, update all references to support/faq and so on.

**Comment by Kubuxu** [comment]
If we decide to go with discourse we need someone who will captain it, maintain and so on (DRI).

**Comment by flyingzumwalt** [comment]
- [ ] get discuss.ipfs.io subdomain set up
- [ ] collect implementation factors -- "to host or not to host"
- [ ] gather list of pros + cons
- [ ] plan to phase out the github repositories

**Comment by lgierth** [comment]
assigning myself for the subdomain setup

**Comment by flyingzumwalt** [comment]
Redirecting all "whether to pull the trigger" discussion to https://github.com/ipfs/community/issues/69 so we can close out that long-running issue.

**Comment by flyingzumwalt** [comment]
I've made a decision document that we can use to _finally_ pull the trigger on this decision https://github.com/ipfs/community/pull/246
