### ISSUE TITLE
Content Enhancement: Support subdirectories when generating Go package docs

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#72]
The package documentation script for Go [doesn’t descend into subdirectories](https://github.com/ipfs/docs/blob/master/scripts/pkg2md.sh#L31), which leaves us with incomplete documentation. For example, we get `coreapi`, but not `coreapi/interface`, which is kind of critical.

In constrast, godoc.org does this and links the subdirectores [at the bottom](https://godoc.org/github.com/ipsn/go-ipfs/core/coreapi#pkg-subdirectories).

**Comment by jessicaschilling** [comment]
Migrated to godoc under #276 ... closing this issue.
