### ISSUE TITLE
Write guide to implementing IPFS in a new language

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#73]
Since you pointed out ipfs/community#177, would you or @flyingzumwalt be interested in translating this into a doc for the “guides” section here, @diasdavid? (After #68 merges.)

**Comment by Mr0grog** [comment]
I’m thinking it might be something as simple as:

1. Implement Libp2p, then IPFS
2. Dependency tree of important modules/bits of code (like what you posted in that community issue)
3. Links to relevant specs?

**Comment by diasdavid** [comment]
Better focus on writing the specs first, they should be self-sufficient to create another IPFS implementation. Any guide to "here is how to implement IPFS" will be quickly out of date and it will be most "copy these modules".

**Comment by Mr0grog** [comment]
Ok.
