### ISSUE TITLE
Improve table-of-contents experience

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#75]
We currently auto-generate a table of contents in the navigation sidebar for the current page. Some pages also have a built-in table of contents (e.g. the CLI and HTTP API docs; godocs), which is a bit redundant.

We should probably:

- Get rid of the table of contents at the top of any documents.
- Either make the TOC in the sidebar collapsible or move it to a right-side column.
- Auto-highlight the current TOC item when you click/scroll.
- Maybe generate it with JavaScript on the client rather than bake it into the page?

**Comment by Mr0grog** [comment]
You can see where the TOC is currently built in `layouts/partials/nav.html`: https://github.com/ipfs/docs/blob/ab798cdfafd56f34e428fe25d066580795ff6298/layouts/partials/nav.html#L132-L191

**Comment by meiqimichelle** [comment]
I'm picking this up as part of the IPFS Cluster docs revamp. My hope is that whatever solution we develop there can be migrated to our IPFS docs.

**Comment by jessicaschilling** [comment]
Going to close this one, since "have a decent TOC or similar navigation" is definitely part of our specifications under #195.
