### ISSUE TITLE
[question] Tool to render graphs

### ISSUE THREAD

**Issue by schomatis** [ipfs/docs#78]
Which tool are we using (if any) to render DAGs in examples? I'm looking for a simple format I could work on with a text editor and have different output formats, e.g., Graphviz. Any recommendations?

**Comment by Mr0grog** [comment]
There’s no standard tool in use right now. I think the best we’ve got is [this guide to using `graphmd`](https://ipfs.io/docs/examples/example-viewer/example#../graphmd/README.md), which is built on top of [Graphviz](http://www.graphviz.org).

**Comment by Mr0grog** [comment]
http://asciiflow.com is not quite the tool I want for ASCII diagrams in code comments, but still seems like one of the better things I’ve seen so far. (Found at https://unix.stackexchange.com/questions/126630/creating-diagrams-in-ascii)

(Note: I think we should try and make diagrams here in the docs *site* actual images. ASCII is more for code comments.)

**Comment by Mr0grog** [comment]
@schomatis did we resolve this and I can close this issue, or do we need to find a place to list this info? (e.g. should this be part of #79 or something similar? Or should we archive it in https://discuss.ipfs.io?) I’m keen on keeping issues here as things we can solve or complete.

**Comment by schomatis** [comment]
http://asciiflow.com seems like the best choice at the moment, but in general we should have most of the graphics in the docs site as actual images, we can leave the ascii format for the most simple diagrams that can be included in the code (otherwise the best option is to just include a reference to the docs site).
