### ISSUE TITLE
"Getting Started" page  improvements

### ISSUE THREAD

**Issue by SidHarder** [ipfs/docs#8]
@victorbjelkholm This was assigned to you from here https://github.com/ipfs/docs/blob/master/meeting-notes/2017-03-03-pre-prep-call.md.  Could you add some details to this.

**Comment by VictorBjelkholm** [comment]
Sure. Many of our modules are missing a "Getting Started" page, kind of like a Quickstart, where first-time users can understand how you initially use the module. This is a problem in both go and js implementation of IPFS, where you would be forced to look at the tests to even see the most basic usage.

Also, together with that, we're lacking some more advanced, specific examples on how to achieve certain things in the best way, the examples.

**Comment by SidHarder** [comment]
@VictorBjelkholm Thanks :)

**Comment by Mr0grog** [comment]
I’m closing this in favor of #60, which is a little newer and has more specifics. Please feel free to post here if we should re-open this.
