### ISSUE TITLE
[NEW CONTENT] [BOUNTY] Bitswap

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#85]
## This issue has a bounty!
Successfully closing this issue by producing a production-ready piece of documentation can earn you not only the undying love of the IPFS community — it can net you a financial reward. [See the current list of bounty issues and their values here.](https://github.com/ipfs/devgrants/projects/1)

## The need in brief
A high-level explainer of Bitswap.

Context/supporting materials: At the IPFS developer summit in Berlin in July 2018, we had poster-making sessions where people explored various IPFS concepts. This Bitswap poster could ideally be expanded into a basic diagram of what Bitswap is and how it works, supplemented by written content.

![bitswap](https://user-images.githubusercontent.com/74178/43230914-f818dab2-901e-11e8-876b-73ba6a084f76.jpg)

## Deliverable
A concise, high-level description of this IPFS concept. It should answer the following, **supplemented whenever possible by diagrams, videos and/or code examples**:

- **What** is this?
- How does it **relate** to the rest of IPFS?
- What are some **generic use cases** for this — how might it meet a need in someone's project/goal?
- How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not necessarily* use it based on your use case or the current state of the tech.)
- **Where** do you go to learn more?
- What is the **current state** of this concept or technology?

**Content should take the form of a Markdown document, supplemented by diagrams as embedded images.** File locations should be as follows:
- MD content should live here (lease make a PR against the existing placeholder document) https://github.com/ipfs/ipfs-docs-v2/blob/master/docs/concepts/bitswap.md
- Images can live in the MD content's parent directory; we'll move them before final merge
- For videos, just post temporarily on the platform of your choice, and we'll sort out on a case-by-case basis

## Guidelines
- Please use the [IPFS Docs Contributor Guidelines](https://github.com/ipfs/docs/blob/master/CONTRIBUTING.md ) as your north star — **adherence to these guidelines are crucial when it comes to awarding potential bounty**!
- Also, please keep in mind our [core user personae](https://app.mural.co/t/protocollabs6957/m/protocollabs6957/1564779785852/cf7669f3c1773508a811a3fa0eadfb99efb310bf). If a piece of content serves one or more personae in particular, make sure it checks out with that persona's attributes.

**Comment by edgo914** [comment]
I'm interested, assign me for this one!

**Comment by johnnymatthews** [comment]
It's all yours @edgo914!

**Comment by edgo914** [comment]
Sent PR

**Comment by jessicaschilling** [comment]
See https://github.com/ipfs/ipfs-docs-v2/pull/78 for PR.

**Comment by johnnymatthews** [comment]
Closed through [PR 122](https://github.com/ipfs/ipfs-docs-v2/pull/122).

**Comment by momack2** [comment]
@johnnymatthews / @jessicaschilling can you ensure we pay this out and move to the "paid" column of the [bounty board](https://github.com/ipfs/devgrants/projects/1)?
