### ISSUE TITLE
[NEW CONTENT] MultiKey

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#87]
At the IPFS developer summit in Berlin in July 2018, we had poster-making sessions where people explored various IPFS concepts. We should expand on the MultiKey poster by adding a doc in the [`content/guides/concepts`](https://github.com/ipfs/docs/tree/master/content/guides/concepts) folder.

![multikey](https://user-images.githubusercontent.com/74178/43231058-98f3b538-901f-11e8-9af0-0c00824d788f.jpg)

This is a subtask of #56.

---

Concept docs are concise, high-level descriptions of various core concepts in IPFS. They live in the `content/guides/concepts` folder and should strive to answer:

1. **What** is this?
2. How does it **relate** to the rest of IPFS?
3. How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not* use it. *Bitswap* is probably a good example.)
4. **Where** do you go to learn more?
5. What is the **current state** of affairs?

**Comment by jessicaschilling** [comment]
Closing this issue per https://github.com/ipfs/specs/issues/58 - ongoing work may yet impact this content.
