### ISSUE TITLE
Sharing application data using CRDTs

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#88]
Right now, the docs site links out to [this tutorial](https://www.youtube.com/watch?v=-kdx8rJd8rQ) on building a collaborative editing app using CRDTs, but it's lacking context -- and links directly out from docs to third-party sites are less than ideal anyway.

At the IPFS developer summit in Berlin in July 2018, we had poster-making sessions where people explored various IPFS concepts. We should expand on the poster that attempted to describe CRDTs and sharing data for applications (using Peerpad as a case study) by adding a doc explaining this a little better, and linking to the YouTube tutorial as well.

![peerpad](https://user-images.githubusercontent.com/74178/43231169-189c0e98-9020-11e8-9827-f78d5fced3e7.jpg)

**Comment by johnnymatthews** [comment]
This issue was created 2 years ago and may not be relevant anymore. I'll close this issue. Feel free to open it again if anyone thinks it's still relevant.
