### ISSUE TITLE
[CONTENT IMPROVEMENT] Pinning

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#94]
At the Berlin developer summit, we decided *pinning* was important to write a [concept doc](https://github.com/ipfs/docs/tree/master/content/guides/concepts) about.

Here was the original draft:

> # Pinning
>
> IPFS nodes treat the data they store like a cache: in theory it could be thrown out at any time and re-retrieved from another node. “Pinning” a CID tells IPFS never to throw out the data associated with that CID — mainly, that means it sicks around after running garbage collection.

Some concerns:

- [x] Note that `ipfs add <filename>` automatically pins, while other commands do not.
- [x] Note that GC is not automatic?
- [ ] ~Should this talk about future plans around named pins and/or MFS-based pins?~ (Too speculative, but it should cover MFS “best effort” pinning.)
- [x] Should this talk about pinning services?
- [ ] Would it be helpful to discuss how you might load some content through the public gateway, but then not be able to do so again a few hours later as an example?

/cc @Stebalien @hsanjuan who were also in this session

This is a subtask of #56.

---

Concept docs are concise, high-level descriptions of various core concepts in IPFS. They live in the `content/guides/concepts` folder and should strive to answer:

1. **What** is this?
2. How does it **relate** to the rest of IPFS?
3. How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not* use it. *Bitswap* is probably a good example.)
4. **Where** do you go to learn more?
5. What is the **current state** of affairs?

**Comment by hsanjuan** [comment]
LGTM

**Comment by Mr0grog** [comment]
@rjharmon made major improvements in #105. I think we still want to make another pass to address the items about examples with the public gateway and how MFS is like pinning (it’s “best effort” pinned: GC determines MFS attachment by walking down from files in MFS, but if a block in the middle of your tree gets deleted with `ipfs block rm`, that can orphan all the child nodes and they might get garbage collected because they are technically no longer attached to your MFS).

**Comment by jessicaschilling** [comment]
Closing this issue, since substantial edits have been made in the interim - see https://github.com/ipfs/ipfs-docs-v2/edit/master/docs/concepts/persistence.md .
