### ISSUE TITLE
Write concept doc on peers and peer IDs

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/docs#96]
**_This issue is part of [Epic 3B: Fixes from legacy issue queue](https://github.com/ipfs/docs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++%22epic+3b%22+)._**

At the Berlin developer summit, we decided *Peers* and *Peer IDs* were important to write a [concept doc](https://github.com/ipfs/docs/tree/master/content/guides/concepts) about.

These are tightly related enough that we could probably just have one doc covering both and name it “Peers and Peer IDs,” “Peer/Peer ID,” “Peer(ID),” or something along those lines.

We did not have time to write a rough draft, so this needs to be written from scratch.

This is a subtask of #56.

---

Concept docs are concise, high-level descriptions of various core concepts in IPFS. They live in the `content/guides/concepts` folder and should strive to answer:

1. **What** is this?
2. How does it **relate** to the rest of IPFS?
3. How can (or should?) you **use** it? (Note: sometimes the answer is that you should understand it, but *not* use it. *Bitswap* is probably a good example.)
4. **Where** do you go to learn more?
5. What is the **current state** of affairs?

**Comment by jessicaschilling** [comment]
libp2p has addressed this - see https://github.com/libp2p/docs/issues/35 .

**Comment by jessicaschilling** [comment]
Closing this issue, since it's been addressed by the libp2p folks (https://docs.libp2p.io/concepts/peer-id/) and we're including some form of a basic libp2p guide in the docs beta: cf https://github.com/ipfs/ipfs-docs-v2
